force-app/main/default/objects/Cause__c/Cause__c.object-meta.xml
<CustomObject>
    <label>Cause</label>
    <nameField>
        <displayFormat>CAU{0000}</displayFormat>
        <label>Cause Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Causes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cause__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cause Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL{0000}</displayFormat>
        <label>Classification Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Classification Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <displayFormat>GR{0000}</displayFormat>
        <label>Group Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Group Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/Issue_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Issue Hierarchy</label>
    <nameField>
        <displayFormat>IH{0000}</displayFormat>
        <label>Issue Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cause</label>
    <referenceTo>Cause__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Product_Line__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reason</label>
    <referenceTo>Reason__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Survey_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Survey_Requirements__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Survey Requirements</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reason__c/Reason__c.object-meta.xml
<CustomObject>
    <label>Reason</label>
    <nameField>
        <displayFormat>REA{0000}</displayFormat>
        <label>Reason Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reason__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>SurveyId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF( EndDate__c &lt; Today(), false, true)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Survey_Name__c.field-meta.xml
<CustomField>
    <fullName>Survey_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Survey Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/SurveyIssueHierRequirements__c.field-meta.xml
<CustomField>
    <fullName>SurveyIssueHierRequirements__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SurveyIssueHierRequirements</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/issueSurveyRequired.cls
/*
Functionality to get the survey list
08/20/2016 Infogain – Created.
*/

Public class issueSurveyRequired{    
    
    //Function to check survey required or not for Selected Issue Hierarchy    
    public Boolean surveyRequired(string issueHierId){
        Map<id,Survey__c> surveyMap = new Map<id,Survey__c>(); 
        surveyMap  = getsurveyList(issueHierId);
        
        if(!surveyMap.isEmpty() && surveyMap.size() >0){
            return true;
        }else{
            return false;
        }
    }
    
    //Function to get the survey list for Selected Issue Hierarchy
    public Map<id,Survey__c> getsurveyList(String issueHierId){
        Map<id,Survey__c> surveyMap = new Map<id,Survey__c>();          
        System.debug('test issueHierId'+issueHierId);       
        if(issueHierId != null){
        
            List<Issue_Hierarchy__c> issueData = new List<Issue_Hierarchy__c>([Select id,Survey_Requirements__c,Classification__r.Description__c,Cause__r.Description__c,group__r.Description__c,reason__r.Description__c,Product_Line_Name__c
                                            from Issue_Hierarchy__c  
                                            Where id =: issueHierId
                                            and ((Survey_Requirements__c != null  and Survey_Requirements__c != '' and Survey_Requirements__c != 'NULL' and Survey_Requirements__c != '0')
                                                 or Classification__r.Description__c =  'APE'
                                                 or Classification__r.Description__c = 'Select APE'
                                                 or Cause__r.Description__c like '%NPRM%'
                                                 or group__r.Description__c  like '%NPRM%'
                                                 or reason__r.Description__c  like '%NPRM%')]);
            
            if(!issueData.isEmpty()){
                String Condition = '';
                
                if(issueData[0].Survey_Requirements__c != null && issueData[0].Survey_Requirements__c != '' && issueData[0].Survey_Requirements__c != 'NULL' && issueData[0].Survey_Requirements__c != '0'){
                    
                    if(issueData[0].Survey_Requirements__c.length() == 1){
                        Condition = ' SurveyIssueHierRequirements__c = \'0'+ issueData[0].Survey_Requirements__c +'\'';
                    }else{
                        Condition = ' SurveyIssueHierRequirements__c = \''+ issueData[0].Survey_Requirements__c +'\'';
                    }                    
                }
                
                if(issueData[0].Classification__r.Description__c != null && issueData[0].Classification__r.Description__c != '' 
                && (issueData[0].Classification__r.Description__c == 'APE' || issueData[0].Classification__r.Description__c == 'Select APE')&& issueData[0].Product_Line_Name__c != 'Heated Tobacco'){
                    if(Condition.trim()  == ''){
                        Condition = '  SurveyIssueHierRequirements__c= \'APE\'';
                    }else{
                        Condition += ' or  SurveyIssueHierRequirements__c = \'APE\'';
                    }            
                }
                
                //ggcutchon 10/1/2018: RITM2135197 - Implementation  for SCR 18-09-24 2018 PMI APE Survey
                if(issueData[0].Classification__r.Description__c != null && issueData[0].Classification__r.Description__c != '' 
                && (issueData[0].Classification__r.Description__c == 'APE' || issueData[0].Classification__r.Description__c == 'Select APE') && issueData[0].Product_Line_Name__c == 'Heated Tobacco'){
                    if(Condition.trim()  == ''){
                        Condition = '  SurveyIssueHierRequirements__c= \'IQOS APE\'';
                    }else{
                        Condition += ' or  SurveyIssueHierRequirements__c = \'IQOS APE\'';
                    }            
                }
                //end of RITM2135197-------------------
                
                if(issueData[0].Cause__r.Description__c.toUpperCase().Contains('NPRM') || issueData[0].group__r.Description__c.toUpperCase().Contains('NPRM') || issueData[0].reason__r.Description__c.toUpperCase().Contains('NPRM')){
                    if(Condition.trim()  == ''){
                        Condition = '  SurveyIssueHierRequirements__c= \'NPRM\'';
                    }else{
                        Condition += ' or  SurveyIssueHierRequirements__c= \'NPRM\'';
                    }            
                }
                
                List<Survey__c> surList  = new List<Survey__c>();
                          
                if(Condition.trim() != ''){                     
                    surList = Database.query('Select id,Survey_Name__c from Survey__c where active__c = true and ( '+Condition+' ) order by Survey_Name__c asc'); 
                }
                
                
                if(!surList.isEmpty()){
                    for(Survey__c suv :surList){
                        surveyMap.put(suv.id,suv);
                    }
                }
            } 
        } 
        
        return surveyMap;
    }   
    
}