force-app/main/default/objects/Cause__c/Cause__c.object-meta.xml
<CustomObject>
    <label>Cause</label>
    <nameField>
        <displayFormat>CAU{0000}</displayFormat>
        <label>Cause Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Causes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cause__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cause Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL{0000}</displayFormat>
        <label>Classification Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Classification Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <displayFormat>GR{0000}</displayFormat>
        <label>Group Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Group Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/Issue_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Issue Hierarchy</label>
    <nameField>
        <displayFormat>IH{0000}</displayFormat>
        <label>Issue Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cause</label>
    <referenceTo>Cause__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cust_Cons_Flag__c.field-meta.xml
<CustomField>
    <fullName>Cust_Cons_Flag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CustConsFlag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issue Type</label>
    <referenceTo>Issue_Type__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reason</label>
    <referenceTo>Reason__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Type__c/Issue_Type__c.object-meta.xml
<CustomObject>
    <label>Issue Type</label>
    <nameField>
        <displayFormat>IT{0000}</displayFormat>
        <label>Issue Type  Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IssueTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Issue Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reason__c/Reason__c.object-meta.xml
<CustomObject>
    <label>Reason</label>
    <nameField>
        <displayFormat>REA{0000}</displayFormat>
        <label>Reason Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reason__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFN__c/TFN__c.object-meta.xml
<CustomObject>
    <label>TFN</label>
    <nameField>
        <displayFormat>TFN-{0000}</displayFormat>
        <label>TFN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Toll Free Number</relationshipLabel>
    <relationshipName>Toll_Free_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/Transaction_Management__c.object-meta.xml
<CustomObject>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Management__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/TFN__c.field-meta.xml
<CustomField>
    <fullName>TFN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DNIS</label>
    <referenceTo>TFN__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IssueHierarchyControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
/*
Test Class for Issue Hierarchy Controller
07/19/2016 Infogain – Created.
*/

@isTest
    private class IssueHierarchyControllerTest {
    
        //Validate Reset method
        static testMethod void validateReset() {
            Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
            insert testOpCo;
            Classification__c testClsfy = TestDataSetup.createClassify('Test Classification');
            insert testClsfy;
            Product_Line__c testPL = TestDataSetup.createPL('', 'Test PL1', testOpCo);
            insert testPL;
            Issue_Type__c testIT = TestDataSetup.createIT('');
            insert testIT;
            Group__c testGroup = TestDataSetup.createGroup('Test Group');
            insert testGroup;
            Cause__c testCause = TestDataSetup.createCause('test des');
            insert testCause;
            Reason__c testReason = TestDataSetup.createReason('');
            insert testReason;
            Issue_Hierarchy__c testIH = TestDataSetup.createIH(testClsfy, testPL, testIT, testGroup, testCause, testReason,false);
            insert testIH;
            //ApexPages.currentPage().getParameters().put('issueHierId',testIH.Id); 
            Test.startTest();
                IssueHierarchyController obj=  new IssueHierarchyController(new ApexPages.StandardController(testIH));
                //System.AssertEquals(null,obj.reset());
            Test.stopTest();
       
            System.AssertEquals(null,obj.reset());
        }
        //Validate data reset for OnChangeProductLine method
        static testMethod void validateOnChangePL() {
            Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
            insert testOpCo;
            Classification__c testClsfy = TestDataSetup.createClassify('Test Classification');
            insert testClsfy;
            Product_Line__c testPL = TestDataSetup.createPL('', 'Test PL2', testOpCo);
            insert testPL;
            Issue_Type__c testIT = TestDataSetup.createIT('');
            insert testIT;
            Group__c testGroup = TestDataSetup.createGroup('Test Group');
            insert testGroup;
            Cause__c testCause = TestDataSetup.createCause('test des');
            insert testCause;
            Reason__c testReason = TestDataSetup.createReason('');
            insert testReason;
            Issue_Hierarchy__c testIH = TestDataSetup.createIH(testClsfy, testPL, testIT, testGroup, testCause, testReason,false);
            insert testIH;
            //ApexPages.currentPage().getParameters().put('issueHierId',testIH.Id); 
            Test.startTest();
            IssueHierarchyController obj=  new IssueHierarchyController(new ApexPages.StandardController(testIH));
            Test.stopTest();
            System.AssertEquals(null,obj.onChangeproductLine());
           
           //System.AssertEquals(null,obj.deleteStore());
        }
    
        //  Validate IssueHierarchyDataOnLoad method
          static testMethod void validateIssueHierarchyDataOnLoad() {
            Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
            insert testOpCo;
            Classification__c testClsfy = TestDataSetup.createClassify('Test Classification');
            insert testClsfy;
            Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL3', testOpCo);
            insert testPL;
            Issue_Type__c testIT = TestDataSetup.createIT('Test Issue Type');
            insert testIT;
            Group__c testGroup = TestDataSetup.createGroup('Test Group');
            insert testGroup;
            Cause__c testCause = TestDataSetup.createCause('Test Cause');
            insert testCause;
            Reason__c testReason = TestDataSetup.createReason('Test Reason');
            insert testReason;
            Issue_Hierarchy__c testIH = TestDataSetup.createIH(testClsfy, testPL, testIT, testGroup, testCause, testReason, true);
            insert testIH;
            ApexPages.currentPage().getParameters().put('issueHierId',testIH.Id);
            ApexPages.currentPage().getParameters().put('firstParam',testReason.Id);
            ApexPages.currentPage().getParameters().put('secondParam',testCause.Id);
            ApexPages.currentPage().getParameters().put('productParam',testPL.Id); 
            
            Test.startTest();
               IssueHierarchyController obj=  new IssueHierarchyController(new ApexPages.StandardController(testIH));
               obj.IssueHierarchyDataOnLoad();
            Test.stopTest();
               
               //Assertions
               System.AssertEquals('Test Issue Type',obj.selectedIssueType);
               System.AssertEquals('Test Reason',obj.reasonStr);
               System.AssertEquals('Test Cause',obj.causeStr);
           
        }
    
        // Validate GetReasonStatic method
        static testMethod void validateGetReasonStatic() {
            Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
            insert testOpCo;
            Classification__c testClsfy = TestDataSetup.createClassify('Test Classification');
            insert testClsfy;
            Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL4', testOpCo);
            insert testPL;
            Issue_Type__c testIT = TestDataSetup.createIT('Test Cause');
            insert testIT;
            Group__c testGroup = TestDataSetup.createGroup('Test Group');
            insert testGroup;
            Cause__c testCause = TestDataSetup.createCause('Test Cause');
            insert testCause;
            Reason__c testReason = TestDataSetup.createReason('Test Reason');
            insert testReason;
            Issue_Hierarchy__c testIH = TestDataSetup.createIH(testClsfy, testPL, testIT, testGroup, testCause, testReason, true);
            insert testIH;
            ApexPages.currentPage().getParameters().put('issueHierId',testIH.Id);
            ApexPages.currentPage().getParameters().put('firstParam',testReason.Id);
            ApexPages.currentPage().getParameters().put('secondParam',testCause.Id);
            ApexPages.currentPage().getParameters().put('productParam',testPL.Id); 
            //String tempReason = IssueHierarchyController.getReasonStatic(testPL.Name, testIT.Description__c, testCause.Description__c);
            Test.startTest();
              IssueHierarchyController obj=  new IssueHierarchyController(new ApexPages.StandardController(testIH));
              IssueHierarchyController.getReasonStatic('Test Product Line', 'Test Issue Type', 'Test Cause','Consumer');
            Test.stopTest();
             
             System.AssertEquals('Test Reason',obj.reasonStr);
            
        }
    
        // Validate GetCauseStatic method
        static testMethod void validateGetCauseStatic() {
            Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
            insert testOpCo;
            Classification__c testClsfy = TestDataSetup.createClassify('Test Classification');
            insert testClsfy;
            Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL5', testOpCo);
            insert testPL;
            Issue_Type__c testIT = TestDataSetup.createIT('Test Cause');
            insert testIT;
            Group__c testGroup = TestDataSetup.createGroup('Test Group');
            insert testGroup;
            Cause__c testCause = TestDataSetup.createCause('Test Cause');
            insert testCause;
            Reason__c testReason = TestDataSetup.createReason('Test Reason');
            insert testReason;
            Issue_Hierarchy__c testIH = TestDataSetup.createIH(testClsfy, testPL, testIT, testGroup, testCause, testReason, true);
            insert testIH;
            ApexPages.currentPage().getParameters().put('issueHierId',testIH.Id);
            ApexPages.currentPage().getParameters().put('firstParam',testReason.Id);
            ApexPages.currentPage().getParameters().put('secondParam',testCause.Id);
            ApexPages.currentPage().getParameters().put('productParam',testPL.Id); 
            
            Test.startTest();
               IssueHierarchyController.getCauseStatic('Test Product Line', 'Test Issue Type', 'Test Reason','Consumer');
            Test.stopTest();
           
        }
    
        //Validate GetIssueHierarchyData method
        static testMethod void validateGetIssueHierarchyData() {
            Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
            insert testOpCo;
            Classification__c testClsfy = TestDataSetup.createClassify('Test Classification');
            insert testClsfy;
            Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL7', testOpCo);
            insert testPL;
            Issue_Type__c testIT = TestDataSetup.createIT('Test Issue Type');
            insert testIT;
            Group__c testGroup = TestDataSetup.createGroup('Test Group');
            insert testGroup;
            Cause__c testCause = TestDataSetup.createCause('Test Cause');
            insert testCause;
            Reason__c testReason = TestDataSetup.createReason('Test Reason');
            insert testReason;
            Issue_Hierarchy__c testIH = TestDataSetup.createIH(testClsfy, testPL, testIT, testGroup, testCause, testReason, true);
            insert testIH;
            ApexPages.currentPage().getParameters().put('issueHierId',testIH.Id);
            ApexPages.currentPage().getParameters().put('firstParam',testCause.Id);
            ApexPages.currentPage().getParameters().put('secondParam',testReason.Id);
            
            Test.startTest();
                IssueHierarchyController obj=  new IssueHierarchyController(new ApexPages.StandardController(testIH));
                obj.getIssueHierarchyData();
            Test.stopTest();
           
        }
    
        //Validate GetIssueHierarchyData method 
        static testMethod void validateGetIssueHierarchyData1() {
            
            Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
            insert testOpCo;
            Classification__c testClsfy = TestDataSetup.createClassify('Test Classification');
            insert testClsfy;
            Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL8', testOpCo);
            insert testPL;
            Issue_Type__c testIT = TestDataSetup.createIT('Test Issue Type');
            insert testIT;
            Group__c testGroup = TestDataSetup.createGroup('Test Group');
            insert testGroup;
            Cause__c testCause = TestDataSetup.createCause('Test Cause');
            insert testCause;
            Reason__c testReason = TestDataSetup.createReason('Test Reason');
            insert testReason;
            Issue_Hierarchy__c testIH = TestDataSetup.createIH(testClsfy, testPL, testIT, testGroup, testCause, testReason, true);
            testIH.Cust_Cons_Flag__c = 'ALL';
            insert testIH;
            TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
            insert testTFN;
            Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
            insert testTM;
            Cookie tranId = ApexPages.currentPage().getCookies().get('tranId');
            Cookie customerRecType = ApexPages.currentPage().getCookies().get('customerRecType');
            tranId = new Cookie('tranId',testTM.id,null,-1,false);
            customerRecType = new Cookie('customerRecType','Consumer',null,-1,false);
            ApexPages.currentPage().setCookies(new Cookie[]{tranId});
            ApexPages.currentPage().setCookies(new Cookie[]{customerRecType});
            ApexPages.currentPage().getParameters().put('issueHierId',testIH.Id);
            ApexPages.currentPage().getParameters().put('firstParam',testCause.Id);
            ApexPages.currentPage().getParameters().put('secondParam',testReason.Id);
             
            Test.startTest();
                //IssueHierarchyController.causeWrapper wrapObj=  new IssueHierarchyController.causeWrapper(True,testIH);
                IssueHierarchyController obj=  new IssueHierarchyController(new ApexPages.StandardController(testIH));
                obj.getIssueHierarchyData();
            Test.stopTest();
           
        }
    
    
    }