force-app/main/default/objects/Cause__c/Cause__c.object-meta.xml
<CustomObject>
    <label>Cause</label>
    <nameField>
        <displayFormat>CAU{0000}</displayFormat>
        <label>Cause Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Causes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL{0000}</displayFormat>
        <label>Classification Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <displayFormat>GR{0000}</displayFormat>
        <label>Group Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IHNL_Association__c/IHNL_Association__c.object-meta.xml
<CustomObject>
    <label>IHNL Association</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>IHNL Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IHNL Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IHNL_Association__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <formula>Issue_Hierarchy__r.Cause__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cause</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <formula>Issue_Hierarchy__r.Classification__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Classification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <formula>Issue_Hierarchy__r.Group__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Issue_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Issue_Hierarchy__c</fullName>
    <label>Issue Hierarchy</label>
    <referenceTo>Issue_Hierarchy__c</referenceTo>
    <relationshipLabel>IHNL Associations</relationshipLabel>
    <relationshipName>IHNL_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <formula>Issue_Hierarchy__r.Issue_Type__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Issue Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Natural_Language__c.field-meta.xml
<CustomField>
    <fullName>Natural_Language__c</fullName>
    <label>Natural Language</label>
    <referenceTo>Natural_Language__c</referenceTo>
    <relationshipLabel>IHNL Associations</relationshipLabel>
    <relationshipName>IHNL_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>Issue_Hierarchy__r.Product_Line__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <formula>Issue_Hierarchy__r.Reason__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reason</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/Issue_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Issue Hierarchy</label>
    <nameField>
        <displayFormat>IH{0000}</displayFormat>
        <label>Issue Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cause</label>
    <referenceTo>Cause__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cust_Cons_Flag__c.field-meta.xml
<CustomField>
    <fullName>Cust_Cons_Flag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CustConsFlag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issue Type</label>
    <referenceTo>Issue_Type__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reason</label>
    <referenceTo>Reason__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Type__c/Issue_Type__c.object-meta.xml
<CustomObject>
    <label>Issue Type</label>
    <nameField>
        <displayFormat>IT{0000}</displayFormat>
        <label>Issue Type  Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IssueTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Natural_Language__c/Natural_Language__c.object-meta.xml
<CustomObject>
    <label>Natural Language</label>
    <nameField>
        <displayFormat>NL-{0000}</displayFormat>
        <label>Natural Language ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Natural Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Natural_Language__c/fields/Natural_Language__c.field-meta.xml
<CustomField>
    <fullName>Natural_Language__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Natural Language</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reason__c/Reason__c.object-meta.xml
<CustomObject>
    <label>Reason</label>
    <nameField>
        <displayFormat>REA{0000}</displayFormat>
        <label>Reason Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IHNLAssociationListControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
/*
Test Class for Issue Hierarchy Controller
12/21/2016 Infogain – Created.
*/
@isTest(seealldata = true)
private class IHNLAssociationListControllerTest {
    
    static testMethod void IHNLAssociationController1() {
        
        	
            Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
            insert testOpCo;
            Classification__c testClsfy = TestDataSetup.createClassify('Test Classification');
            insert testClsfy;
            Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL7', testOpCo);
            insert testPL;
            Issue_Type__c testIT = TestDataSetup.createIT('Test Issue Type');
            insert testIT;
            Group__c testGroup = TestDataSetup.createGroup('Test Group');
            insert testGroup;
            Cause__c testCause = TestDataSetup.createCause('Test Cause');
            insert testCause;
            Reason__c testReason = TestDataSetup.createReason('Test Reason');
            insert testReason;
            Issue_Hierarchy__c testIH = TestDataSetup.createIH(testClsfy, testPL, testIT, testGroup, testCause, testReason, true);
        	testIH.Cust_Cons_Flag__c='ALL';
            insert testIH;
        
        	Natural_Language__c natlangTest=New Natural_Language__c();
            natlangTest.Natural_Language__c='Natural Language';
        	insert natlangTest;
        
        	IHNL_Association__c IHNLTest=New IHNL_Association__c();
        	IHNLTest.Issue_Hierarchy__c=testIH.id;
        	IHNLTest.Natural_Language__c=natlangTest.id;
        	insert IHNLTest;
            ApexPages.currentPage().getParameters().put('issueHierId',testIH.Id);
            ApexPages.currentPage().getParameters().put('firstParam',testCause.Id);
            ApexPages.currentPage().getParameters().put('secondParam',testReason.Id);
        	
            
            Test.startTest();
                IHNLAssociationListController obj=  new IHNLAssociationListController(new ApexPages.StandardController(natlangTest));
        		IHNLAssociationListController.IssueHierWrapper IHNLWrapper=new IHNLAssociationListController.IssueHierWrapper(); 
                obj.IssueHierarchyDataOnLoad();
        		obj.IssueHierList();
        		obj.reset();
        		obj.onChangeproductLine();
        		IHNLAssociationListController.natLangList(testPL.Name,testIT.Name);
            Test.stopTest();
           
        }

}