force-app/main/default/objects/Cause__c/Cause__c.object-meta.xml
<CustomObject>
    <label>Cause</label>
    <nameField>
        <displayFormat>CAU{0000}</displayFormat>
        <label>Cause Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Causes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cause__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cause Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL{0000}</displayFormat>
        <label>Classification Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Classification Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <displayFormat>GR{0000}</displayFormat>
        <label>Group Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Group Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/IHNL_Association__c.object-meta.xml
<CustomObject>
    <label>IHNL Association</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>IHNL Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IHNL Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IHNL_Association__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <formula>Issue_Hierarchy__r.Cause__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cause</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <formula>Issue_Hierarchy__r.Classification__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Classification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <formula>Issue_Hierarchy__r.Group__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Issue_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Issue_Hierarchy__c</fullName>
    <label>Issue Hierarchy</label>
    <referenceTo>Issue_Hierarchy__c</referenceTo>
    <relationshipLabel>IHNL Associations</relationshipLabel>
    <relationshipName>IHNL_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <formula>Issue_Hierarchy__r.Issue_Type__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Issue Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Natural_Language__c.field-meta.xml
<CustomField>
    <fullName>Natural_Language__c</fullName>
    <label>Natural Language</label>
    <referenceTo>Natural_Language__c</referenceTo>
    <relationshipLabel>IHNL Associations</relationshipLabel>
    <relationshipName>IHNL_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>Issue_Hierarchy__r.Product_Line__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IHNL_Association__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <formula>Issue_Hierarchy__r.Reason__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reason</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/Issue_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Issue Hierarchy</label>
    <nameField>
        <displayFormat>IH{0000}</displayFormat>
        <label>Issue Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cause</label>
    <referenceTo>Cause__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cust_Cons_Flag__c.field-meta.xml
<CustomField>
    <fullName>Cust_Cons_Flag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CustConsFlag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issue Type</label>
    <referenceTo>Issue_Type__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reason</label>
    <referenceTo>Reason__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Type__c/Issue_Type__c.object-meta.xml
<CustomObject>
    <label>Issue Type</label>
    <nameField>
        <displayFormat>IT{0000}</displayFormat>
        <label>Issue Type  Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IssueTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Issue Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Natural_Language__c/Natural_Language__c.object-meta.xml
<CustomObject>
    <label>Natural Language</label>
    <nameField>
        <displayFormat>NL-{0000}</displayFormat>
        <label>Natural Language ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Natural Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Natural_Language__c/fields/Natural_Language__c.field-meta.xml
<CustomField>
    <fullName>Natural_Language__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Natural Language</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Natural_Language_Knowledge_Junction__c/fields/Article_ID__c.field-meta.xml
<CustomField>
    <fullName>Article_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Article ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Natural_Language_Knowledge_Junction__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reason__c/Reason__c.object-meta.xml
<CustomObject>
    <label>Reason</label>
    <nameField>
        <displayFormat>REA{0000}</displayFormat>
        <label>Reason Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reason__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IHNLAssociationListController.cls
public class IHNLAssociationListController {
    
    public List<IssueHierWrapper> ihnlList{get;set;}
    public List<KnowledgeWrapper> knowledgeList{get;set;}
    private Natural_Language__c natlangObj;
    public String selectedProductLine {get; set;} /* String to hold Product Line data */
    public String selectedIssueType {get; set;} /* String to hold Issue Type data */
    public String natlang{get;set;}
    public string customerRecType{get;set;}
    public List<SelectOption> productLineList {get; set;} /* List to hold Product Line data */
    public List<SelectOption> issueTypeList {get; set;} /* List to hold Issue Type data */
    private String productLine = Apexpages.currentpage().getparameters().get('productlinecode');
    public String issueHierId {get; set;} /* String to hold Issue Hierarchy ID */
    public string natlangHtml {get; set;}
    public string ArticleId {get; set;}
    
    //Controller method for IHNLAssociationListController class.
    public IHNLAssociationListController(ApexPages.StandardController stdController){
        
        
        this.natlangObj = (Natural_Language__c)stdController.getRecord();
        ihnlList=new List<IssueHierWrapper>();
        knowledgeList=new  List<KnowledgeWrapper>();
        Cookie counter = ApexPages.currentPage().getCookies().get('customerRecType');
        ArticleId = '';
        if(counter != null) {
            customerRecType = counter.getValue();
        }
        issueHierId =  apexpages.currentpage().getparameters().get('issueHierId');
        if(apexpages.currentpage().getparameters().get('productlineName')  !=  null)
            selectedProductLine = apexpages.currentpage().getparameters().get('productlineName');    
            
        productLineListData();
        if(issueHierId != null && issueHierId  != '')
        IssueHierarchyDataOnLoad(); 
    }

    
    public pageReference reset(){
        selectedProductLine = '';
        selectedIssueType = '';
        issueHierId = '';
        natlang = '';
        natlangHtml  = '';
        ihnlList=new List<IssueHierWrapper>();
        knowledgeList=new  List<KnowledgeWrapper>();
        issueTypeListData();        
        return null;
    }

    /* Reset values on change of Product Line */
    public pageReference onChangeproductLine(){
        selectedProductLine = '';
        selectedIssueType = '';
        issueHierId = '';
        issueTypeList.clear();
        return null;
    }
    
     /* Create the Product Line List from Issue Hierarchy data using aggregate method */
    private void productLineListData()
    {    
        productLineList = new List<SelectOption>();     
        
        if(selectedProductLine != null && selectedProductLine != ''){
            productLineList.add(new SelectOption(selectedProductLine, selectedProductLine));
        }else{
            productLineList.add(new SelectOption('0', '--Select Product Line--'));
            
            List<Product_Line__c> productLineObj = new List<Product_Line__c>([Select id, Name from Product_Line__c where isActive__c = true]);  
            
            for(Product_Line__c pl :productLineObj){
                productLineList.add(new SelectOption(pl.name, pl.name));
            } 
        }
        issueTypeListData();
    }

    /* Create the Issue Type List from Issue Hierarchy data when Product Line item is selected using aggregate method */
    public void issueTypeListData()
    {   
        If(selectedProductLine != null && selectedProductLine != ''){ 
            issueTypeList = new List<SelectOption>(); 
            issueTypeList.add(new SelectOption('0', '--Select Issue Type--')); 
            
            string product =Apexpages.currentPage().getParameters().get('productParam');                                                 
                                                
            String query = 'Select Count(id), Issue_Type__r.Description__c From Issue_Hierarchy__c Where Active__c = true and Issue_Type__c != null';
        
            query += ' and Product_Line__r.Name = \''+ selectedProductLine +'\'';
            
            if(customerRecType != ''){
                if(customerRecType == 'consumer')    
                    query += ' and (Cust_Cons_Flag__c = \'ALL\' or Cust_Cons_Flag__c = \'CONS\') '; 
                else
                    query += ' and (Cust_Cons_Flag__c = \'ALL\' or Cust_Cons_Flag__c = \'CUST\') '; 
            }
                                                
            query += ' Group by Issue_Type__r.Description__c';
            
            system.debug('test query  res'+query );    
            string issueType;            
            for (AggregateResult ar : (List<AggregateResult>)Database.query(query)){
                issueType = String.ValueOf(ar.get('Description__c'));
                issueTypeList.add(new SelectOption(String.ValueOf(ar.get('Description__c')), String.ValueOf(ar.get('Description__c'))));
            }
            if(issueTypeList.size() == 2 && issueHierId != null && issueHierId !=  ''){
                selectedIssueType = issueType.trim();
            }
        } 
    }
    
     /* Get Issue Hierarchy data on page load */
    public PageReference IssueHierarchyDataOnLoad(){
            
        List<IHNL_Association__c> ihnlListdata = new List<IHNL_Association__c>();
        List<Issue_Hierarchy__c> IHMasterData=new List<Issue_Hierarchy__c>();
        List<IHNL_Association__c> selectedIssueHierarchy = new List<IHNL_Association__c>();
        ihnlList = new List<IssueHierWrapper>();
        selectedIssueHierarchy  = new List<IHNL_Association__c>([
                                      select id,Issue_Hierarchy__c,Natural_Language__r.Natural_Language__c,
                                        Issue_Hierarchy__r.Name,Issue_Hierarchy__r.Group__r.Description__c,Issue_Hierarchy__r.Classification__r.Description__c,
                                      Issue_Hierarchy__r.Product_Line__r.Name,Issue_Hierarchy__r.Issue_Type__r.Description__c,Issue_Hierarchy__r.Reason__r.Description__c,
                                      Issue_Hierarchy__r.Cause__r.Description__c
                                      from IHNL_Association__c 
                                      Where Issue_Hierarchy__c =:issueHierId
                                      Limit 1
                                      ]);
                                      
        if(!selectedIssueHierarchy.isEmpty() && selectedIssueHierarchy.size() >0){
        
            selectedProductLine = selectedIssueHierarchy[0].Issue_Hierarchy__r.Product_Line__r.Name;
            
            issueTypeListData();
             
            selectedIssueType = selectedIssueHierarchy[0].Issue_Hierarchy__r.Issue_Type__r.Description__c;
            natlangHtml = selectedIssueHierarchy[0].Natural_Language__r.Natural_Language__c;
            natlang = selectedIssueHierarchy[0].Natural_Language__r.Natural_Language__c;
            
        if(customerRecType != ''){
            //create a string
            String ntData = natlang;
            
            //add wildcards around it to be more flexible in the search
            ntData = '%' + ntData + '%';
             
                if(customerRecType == 'consumer') 
                     ihnlListdata.addAll([
                      select id,Issue_Hierarchy__c,Natural_Language__r.Natural_Language__c
                      from IHNL_Association__c 
                      where Issue_Hierarchy__r.Product_Line__r.Name =: selectedProductLine 
                      and Issue_Hierarchy__r.Issue_Type__r.Description__c =: selectedIssueType 
                      and Natural_Language__r.Natural_Language__c LIKE :ntData
                      and (Issue_Hierarchy__r.Cust_Cons_Flag__c = 'ALL' or Issue_Hierarchy__r.Cust_Cons_Flag__c = 'CONS') 
                      Limit 1000]);
                else
                     
                     ihnlListdata.addAll([
                      select id,Issue_Hierarchy__c,Natural_Language__r.Natural_Language__c
                      from IHNL_Association__c 
                      where Issue_Hierarchy__r.Product_Line__r.Name =: selectedProductLine 
                      and Issue_Hierarchy__r.Issue_Type__r.Description__c =: selectedIssueType 
                      and Natural_Language__r.Natural_Language__c LIKE :ntData
                      and (Issue_Hierarchy__r.Cust_Cons_Flag__c = 'ALL' or Issue_Hierarchy__r.Cust_Cons_Flag__c = 'CUST') 
                      Limit 1000]);
            }
            
            Map<Id, set<String>> natlangMap = new Map<id, set<String>>();
            
           for(IHNL_Association__c ihnlObj:ihnlListdata){
               set<String> nlData = new set<String>();
               if(!natlangMap.containsKey(ihnlObj.Issue_Hierarchy__c)){
                   nlData.add(ihnlObj.Natural_Language__r.Natural_Language__c);
                   natlangMap.put(ihnlObj.Issue_Hierarchy__c, nlData);
               }else{               
                   set<String> nl = natlangMap.get(ihnlObj.Issue_Hierarchy__c); 
                   if(!nl.Contains(ihnlObj.Natural_Language__r.Natural_Language__c))
                   natlangMap.get(ihnlObj.Issue_Hierarchy__c).add(ihnlObj.Natural_Language__r.Natural_Language__c);    
               }
           }
           
           IHMasterData= new List<Issue_Hierarchy__c>([Select id,Name,Group__r.Description__c,Classification__r.Description__c,
                             Product_Line__r.Name,Issue_Type__r.Description__c,Reason__r.Description__c,
                             Cause__r.Description__c
                             from Issue_Hierarchy__c where id in :natlangMap.keyset()]);
       
       
            if(!IHMasterData.isEmpty()){                           
                for(Issue_Hierarchy__c ih : IHMasterData){  
                    if(ih.id == selectedIssueHierarchy[0].Issue_Hierarchy__c)
                        ihnlList.add(new IssueHierWrapper(true,ih,natlangMap.get(ih.id)));  
                    else
                        ihnlList.add(new IssueHierWrapper(false,ih,natlangMap.get(ih.id))); 
                    
                }
            }
            knowledgeArticleList();  
        }                                     
        return null;
    }
    
    //get All Naturatl Language Names.
    @RemoteAction
    public static set<string> natLangList(String produtLine, String issueType){
        List<IHNL_Association__c> ihnlListdata = new List<IHNL_Association__c>([select id,Natural_Language__c
                                                                              from IHNL_Association__c 
                                                                              where Issue_Hierarchy__r.Product_Line__r.Name =: produtLine and 
                                                                              Issue_Hierarchy__r.Issue_Type__r.Description__c =: issueType]);
        Set<id> ids = new Set<Id>();
        Set<String> NLData = new Set<String>();
        if(!ihnlListdata.isEmpty()){
            for(IHNL_Association__c ih : ihnlListdata){
                if(ih.Natural_Language__c != null)
                    ids.add(ih.Natural_Language__c);
            }        
        }    
        //Natural_Language__r.Natural_Language__c   
        List<Natural_Language__c> natLangList=new List<Natural_Language__c>();
        if(!ids.isEmpty()){
            for(Natural_Language__c ih : [select id,Natural_Language__c from Natural_Language__c where id in: ids]){
               NLData.add(ih.Natural_Language__c);                  
            }
        }
        
        
        return NLData;
        
    }
    
    //Method to get all the related Issue Hierarchy.
    public PageReference IssueHierList(){
        List<IHNL_Association__c> ihnlListdata =new List<IHNL_Association__c>();
        List<Issue_Hierarchy__c> IHMasterData=new List<Issue_Hierarchy__c>();
        ihnlList = new List<IssueHierWrapper>();
        if(customerRecType != '' && natlang.length() >1){
            //create a string
            String ntData = natlang;
            
            //add wildcards around it to be more flexible in the search
            ntData = '%' + ntData + '%';
            System.debug('test ntData '+ntData +','+selectedProductLine+',' +selectedIssueType );
                if(customerRecType == 'consumer') 
                     ihnlListdata.addAll([
                      select id,Issue_Hierarchy__c,Natural_Language__r.Natural_Language__c
                      from IHNL_Association__c 
                      where Issue_Hierarchy__r.Product_Line__r.Name =: selectedProductLine 
                      and Issue_Hierarchy__r.Issue_Type__r.Description__c =: selectedIssueType 
                      and Natural_Language__r.Natural_Language__c LIKE :ntData
                      and (Issue_Hierarchy__r.Cust_Cons_Flag__c = 'ALL' or Issue_Hierarchy__r.Cust_Cons_Flag__c = 'CONS') 
                      Limit 1000]);
                else
                     
                     ihnlListdata.addAll([
                      select id,Issue_Hierarchy__c,Natural_Language__r.Natural_Language__c
                      from IHNL_Association__c 
                      where Issue_Hierarchy__r.Product_Line__r.Name =: selectedProductLine 
                      and Issue_Hierarchy__r.Issue_Type__r.Description__c =: selectedIssueType 
                      and Natural_Language__r.Natural_Language__c LIKE :ntData
                      and (Issue_Hierarchy__r.Cust_Cons_Flag__c = 'ALL' or Issue_Hierarchy__r.Cust_Cons_Flag__c = 'CUST') 
                      Limit 1000]);
            }
        
       Map<Id, Set<String>> natlangMap = new Map<id, Set<String>>();
       System.debug('test ihnlListdata '+ihnlListdata); 
       for(IHNL_Association__c ihnlObj:ihnlListdata){
           set<String> nlData = new set<String>();
           if(!natlangMap.containsKey(ihnlObj.Issue_Hierarchy__c)){
               nlData.add(ihnlObj.Natural_Language__r.Natural_Language__c);
               natlangMap.put(ihnlObj.Issue_Hierarchy__c, nlData);
           }else{               
               Set<String> nl = natlangMap.get(ihnlObj.Issue_Hierarchy__c); 
               if(!nl.Contains(ihnlObj.Natural_Language__r.Natural_Language__c))
                   natlangMap.get(ihnlObj.Issue_Hierarchy__c).add(ihnlObj.Natural_Language__r.Natural_Language__c);
           }
       }
       
       IHMasterData= new List<Issue_Hierarchy__c>([Select id,Name,Group__r.Description__c,Classification__r.Description__c,
                         Product_Line__r.Name,Issue_Type__r.Description__c,Reason__r.Description__c,
                         Cause__r.Description__c
                         from Issue_Hierarchy__c where id in :natlangMap.keyset()]);
                          
        if(!IHMasterData.isEmpty()){                           
            for(Issue_Hierarchy__c ih : IHMasterData){                
                ihnlList.add(new IssueHierWrapper(false,ih,natlangMap.get(ih.id))); 
            }
        }
        return null;
    }
    
    //Method to get all the related article.
    public PageReference knowledgeArticleList(){
        knowledgeList = new List<KnowledgeWrapper>();
        if(natlang.length() >1){
            List<IHNL_Association__c> ihnlListdata = new List<IHNL_Association__c>([select id,Natural_Language__c
                                                                                  from IHNL_Association__c 
                                                                                  where Issue_Hierarchy__r.Product_Line__r.Name =: selectedProductLine and 
                                                                                  Issue_Hierarchy__r.Issue_Type__r.Description__c =: selectedIssueType]);
            Set<id> ids = new Set<Id>();
            Set<String> NLData = new Set<String>();
            if(!ihnlListdata.isEmpty()){
                for(IHNL_Association__c ih : ihnlListdata){
                    if(ih.Natural_Language__c != null)
                        ids.add(ih.Natural_Language__c);
                }        
            }    
            //Natural_Language__r.Natural_Language__c   
            List<Natural_Language__c> natLangList=new List<Natural_Language__c>();
            if(!ids.isEmpty()){
                for(Natural_Language__c ih : [select id,Natural_Language__c from Natural_Language__c where id in: ids]){
                   NLData.add(ih.Natural_Language__c);                  
                }
            }
            system.debug('test natlang '+natlang);
            //create a string
            String ntData = natlang;
            
            //add wildcards around it to be more flexible in the search
            ntData = '%' + ntData + '%';
            List<Natural_Language_Knowledge_Junction__c> knowledgeListData = [select id,Article_ID__c,Title__c
                                                                              from Natural_Language_Knowledge_Junction__c 
                                                                              where Natural_Language__c in: ids
                                                                              and Natural_Language__r.Natural_Language__c LIKE :ntData];
            
            if(knowledgeListData.size()>0){
                for(Natural_Language_Knowledge_Junction__c k :knowledgeListData){
                    KnowledgeWrapper kp = new KnowledgeWrapper();
                    kp.titleWithSpace = k.Title__c;
                    kp.articleId = k.Article_ID__c;
                    
                    knowledgeList.add(kp);
                }
            }
        }
        return null;
    }
    
    public class KnowledgeWrapper{
        public string titleWithSpace {get;set;}
        public string articleId {get;set;}        
    }
    
    /* Wrapper Class */
    Public class IssueHierWrapper{
        Public Boolean radio{get;set;}
        Public String groupName{get;set;}
        Public String classification{get;set;}
        Public String cause{get;set;}
        Public String issuetype {get;set;}
        Public String reason {get;set;}
        Public String natlang{get;set;}
        Public Integer nlSize{get;set;}
        public set<String> nlDataList {get;set;}
        Public Issue_Hierarchy__c issuehierarchyObj{get;set;}
        Public IssueHierWrapper(Boolean radio,Issue_Hierarchy__c ih, set<String> nlData){
            this.radio=false;
            this.issuehierarchyObj = ih;
            this.reason = '';
            nlSize = 0;
            nlDataList = new set<String>();
            nlDataList = nlData;
            nlSize = nlDataList.size();
            this.reason = ih.Reason__r.Description__c.replace('\'','\\'+'\'');
            this.cause = ih.Cause__r.Description__c.replace('\'','\\'+'\'');    
            this.groupName = ih.Group__r.Description__c.replace('\'','\\'+'\'');
            this.classification = ih.Classification__r.Description__c.replace('\'','\\'+'\'');
            this.issuetype = ih.Issue_Type__r.Description__c.replace('\'','\\'+'\'');
        }
        Public IssueHierWrapper(){}          
    } 
        
}