force-app/main/default/objects/Customer_Type__c/Customer_Type__c.object-meta.xml
<CustomObject>
    <label>Customer Type</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Customer Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Type__c/fields/CodeType__c.field-meta.xml
<CustomField>
    <fullName>CodeType__c</fullName>
    <label>Code Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONSUMERS</fullName>
            </value>
            <value>
                <fullName>CUSTOMERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Type__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Type Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Type__c/fields/CustomerConsumer__c.field-meta.xml
<CustomField>
    <fullName>CustomerConsumer__c</fullName>
    <formula>LEFT( TEXT(CodeType__c ) , 4)</formula>
    <label>CustomerConsumer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Type Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Type__c/fields/Display_Description__c.field-meta.xml
<CustomField>
    <fullName>Display_Description__c</fullName>
    <formula>Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Display Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Type__c/fields/TenantID__c.field-meta.xml
<CustomField>
    <fullName>TenantID__c</fullName>
    <formula>&apos;ALORICAALTRIA&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TenantID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerTypeTriggerHandler.cls
/************************************************************************ 
Author: Randolf Suplito
Date: 08/08/2022
Description: This handler class is for CustomerTypeTrigger
*************************************************************************/

public class CustomerTypeTriggerHandler {
	
    public static Boolean isFirstTime = true;
    
    public static void createCallout(List<Customer_Type__c> triggerNewList, Map<Id,Customer_Type__c> triggerNewMap) {
        
        String lastModifiedUser;
        
        jsonRequestDTO jsonPayload = new jsonRequestDTO();
        List<customerTypeDTO> cusTypeDTOList = new List<customerTypeDTO>();
        
        for(Customer_Type__c cusType : [SELECT Id, LastModifiedBy.CommunityNickname FROM Customer_Type__c WHERE Id IN :triggerNewMap.keyset()]) {
            lastModifiedUser = cusType.LastModifiedBy.CommunityNickname;
        }
        
        for(Customer_Type__c cusType : triggerNewList) {
            customerTypeDTO cusDTO = new customerTypeDTO();
            cusDTO.TENANTID = cusType.TenantID__c != null ? cusType.TenantID__c : '';
            cusDTO.CODETYPE = cusType.CodeType__c != null ? cusType.CodeType__c : '';
            cusDTO.CUSTOMERTYPE = cusType.Customer_Type__c != null ? cusType.Customer_Type__c : '';
            cusDTO.DESCRIPTION = cusType.Description__c != null ? cusType.Description__c : '';
            cusDTO.DISPLAYDESCRIPTION = cusType.Display_Description__c != null ? cusType.Display_Description__c : '';
            cusDTO.CUSTOMERCONSUMER = cusType.CustomerConsumer__c != null ? cusType.CustomerConsumer__c : '';
            if(cusType.IsActive__c != null && cusType.IsActive__c) {
                cusDTO.ACTIVEFLAG = 'Y';
            } else if(cusType.IsActive__c != null && !cusType.IsActive__c) {
                cusDTO.ACTIVEFLAG = 'N';
            } else if(cusType.IsActive__c == null) {
                cusDTO.ACTIVEFLAG = '';
            }
            
            cusTypeDTOList.add(cusDTO);
        }
        
        if(!cusTypeDTOList.isEmpty()) {
            jsonPayload.userName = lastModifiedUser;
            jsonPayload.CustomerType = cusTypeDTOList;
            System.debug('jsonPayload: ' + JSON.Serialize(jsonPayload));
        	APIDataCalloutServices.dataFeedCallout(JSON.Serialize(jsonPayload), ConstantClass.CUSTOMERTYPE_CALLOUT_NAME);
        }
    }
    
    public class jsonRequestDTO {
        public String userName {get; set;}
        public List<customerTypeDTO> CustomerType;
    }
    
    public class customerTypeDTO {
        public String TENANTID {get; set;}
        public String CODETYPE {get; set;}
        public String CUSTOMERTYPE {get; set;}
        public String DESCRIPTION {get; set;}
        public String DISPLAYDESCRIPTION {get; set;}
        public String CUSTOMERCONSUMER {get; set;}
        public String ACTIVEFLAG {get; set;}
    }
}