force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>AnswerID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Answer</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Brand Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/Op_Company__c.field-meta.xml
<CustomField>
    <fullName>Op_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>OpCo</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Hierarchy__c/Brand_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Brand Hierarchy</label>
    <nameField>
        <displayFormat>BH{0000}</displayFormat>
        <label>Brand Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Hierarchy__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>it is only for Brand_Hierarchy_Outbound feed.</description>
    <formula>Brand_Code__r.BrandCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operating_Company__c/fields/OpCo_Description__c.field-meta.xml
<CustomField>
    <fullName>OpCo_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OpCo Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operating_Company__c/fields/OperatingCompany__c.field-meta.xml
<CustomField>
    <fullName>OperatingCompany__c</fullName>
    <label>Operating Company</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRC Direct</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>NAT_SHERMAN</fullName>
            </value>
            <value>
                <fullName>NUMARK</fullName>
            </value>
            <value>
                <fullName>PM Corporate</fullName>
            </value>
            <value>
                <fullName>PMIP</fullName>
            </value>
            <value>
                <fullName>PMUSA</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>USST</fullName>
            </value>
            <value>
                <fullName>USSTC</fullName>
            </value>
            <value>
                <fullName>HELIX</fullName>
            </value>
            <value>
                <fullName>NJOY</fullName>
            </value>
            <value>
                <fullName>6601 Ventures</fullName>
            </value>
            <value>
                <fullName>USSTN</fullName>
            </value>
            <value>
                <fullName>HORIZON</fullName>
            </value>
            <value>
                <fullName>NUMRK</fullName>
                <isActive>false</isActive>
                <label>NUMRK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Line Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/isValidDateCode__c.field-meta.xml
<CustomField>
    <fullName>isValidDateCode__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Date Code on Issue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Op_Company__c.field-meta.xml
<CustomField>
    <fullName>Op_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpCo</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Product Lines</relationshipLabel>
    <relationshipName>Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Store Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Transaction_Management__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Management</label>
    <referenceTo>Transaction_Management__c</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_Type__c/Store_Type__c.object-meta.xml
<CustomObject>
    <label>Store Type</label>
    <nameField>
        <displayFormat>ST{00}</displayFormat>
        <label>Store Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>SurveyId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF( EndDate__c &lt; Today(), false, true)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/Survey_Issue__c.object-meta.xml
<CustomObject>
    <label>Survey Issue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Survey Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Issue__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Survey Issues</relationshipLabel>
    <relationshipName>Survey_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TFN__c/TFN__c.object-meta.xml
<CustomObject>
    <label>TFN</label>
    <nameField>
        <displayFormat>TFN-{0000}</displayFormat>
        <label>TFN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/fields/DNIS__c.field-meta.xml
<CustomField>
    <fullName>DNIS__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DNIS</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFN__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Toll Free Number</relationshipLabel>
    <relationshipName>Toll_Free_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TFN__c/fields/Toll_Free_Number__c.field-meta.xml
<CustomField>
    <fullName>Toll_Free_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Toll Free Number</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/Transaction_Management__c.object-meta.xml
<CustomObject>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Management__c/fields/DNIS__c.field-meta.xml
<CustomField>
    <fullName>DNIS__c</fullName>
    <formula>TFN__r.Toll_Free_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DNIS</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/TFN__c.field-meta.xml
<CustomField>
    <fullName>TFN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DNIS</label>
    <referenceTo>TFN__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewLineTest.cls
/*
  Test Class for Trace Code
  11/23/2016 Infogain – Created.
   */

@isTest
public class NewLineTest
{
    // validate NewLine method 
    public static testmethod void NewLineMethodTest(){
        
            Operating_Company__c testOpCo= new Operating_Company__c();
            testOpCo.OperatingCompany__c = 'PMUSA';
            testOpCo.OpCo_Description__c = 'Test123';
            testOpCo.Active__c = true;
            insert testOpCo;
            
            TFN__c testTFN= new TFN__c();
            testTFN.Operating_Company__c = testOpCo.id;
            testTFN.Toll_Free_Number__c = '1234';
            testTFN.DNIS__c = String.valueOf(123);
            insert testTFN;
            
            Transaction_Management__c testTM= new Transaction_Management__c();
            testTM.Operating_Company__c = testOpCo.Id;
            testTM.TFN__c = testTFN.id;
            insert testTM;
            
            
           Case c = new Case(Comment__c = 'test,',Update_Reason__c =  'test,',MasterId__c = testTM.Name, Op_Company__c = testOpCo.id);
           insert c;
           c.Comment__c = '';
           c.Update_Reason__c = '';
           update c;
           
           Answer__c a = new Answer__c(Answer__c = 'test123');
           insert a;
           
           Attachment_Detail__c ad = new  Attachment_Detail__c(Description__c = 'test123');
           insert ad;
           ad.Description__c  = '';
           update ad;
           
            Product_Line__c testPL= new Product_Line__c();
            testPL.Name = 'SET';
            testPL.Code__c = 'Se';
            testPL.isActive__c = true;
            testPL.isValidDateCode__c = true;
            testPL.Op_Company__c = testOpCo.id;
            testPL.Trace_Code_Location__c =  'CAN';
            insert testPL;
            
            Brand__c testBrand= new Brand__c();
            testBrand.Description__c = 'Brand';
            testBrand.BrandCode__c = 'VR';
            testBrand.Product_Line__c = testPL.id;
            testBrand.Op_Company__c = testOpCo.id;
            insert testBrand;
           
           Brand_Hierarchy__c b= new Brand_Hierarchy__c(Vantive_Id__c = '11', Brand_Code__c = testBrand.id, Product_Line_Code__c = testPL.id , Price_Category__c = 'test123', Product_Desc__c = 'Test123',Product_Type__c = 'test123');
           insert b;
           
           Question__c  q=  new  Question__c(Question__c = 'test123',Type__c = 'Comment');
           insert q;
           
           Store_type__c testStoty = new Store_type__c();
            testStoty.Description__c= 'test123';
            insert testStoty;
           
           Store__c at = new Store__c(Store_Comment__c = 'test123', Store_Type__c = testStoty.id);
           insert at;
           
           Survey__c testSurvey = new Survey__c();
           testSurvey.Survey_Name__c = 'Test123';
           insert testSurvey;
           
           Survey_Issue__c st = new Survey_Issue__c(Survey__c = testSurvey.id, Transaction__c = testTM.id, Issue__c = c.id,Comment__c = 'test123');
           insert  st;
        
            Case caseRec1 = [SELECT Id, IsReviewed__c FROM Case];
            caseRec1.Product_Line__c = 'Tobacco Derived Nicotine pouch';
            caseRec1.PLCode__c = 'TDNP';
            caseRec1.Trace_Code_Location__c = 'Can';
            caseRec1.Mfg_Trace_code__c = 'AA1234';
            update caseRec1;
        
        	Case caseRec2 = [SELECT Id, IsReviewed__c FROM Case];
            caseRec2.Product_Line__c = 'Tobacco Derived Nicotine pouch';
            caseRec2.PLCode__c = 'TDNP';
            caseRec2.Trace_Code_Location__c = 'Can';
            caseRec2.Mfg_Trace_code__c = 'D023U0823';
            update caseRec2;
        
            Case caseRec3 = [SELECT Id, IsReviewed__c FROM Case];
            caseRec3.Product_Line__c = 'NJOY E-CIG TRACE CODE';
            caseRec3.Mfg_Trace_code__c = '02612651124';
            update caseRec3;
            
            Case caseRec4 = [SELECT Id, IsReviewed__c FROM Case];
            caseRec4.PLCode__c = 'AS';
            caseRec4.Mfg_Trace_code__c = 'S363K49S3';
            update caseRec4;
        
        	test.startTest();
            caseRec4.Mfg_Trace_code__c = 'X';
            update caseRec4;
        	caseRec4.Mfg_Trace_code__c = 'U';
            update caseRec4;
        	caseRec4.Mfg_Trace_code__c = 'V';
            update caseRec4;
        	caseRec4.Mfg_Trace_code__c = 'S363A49S3';
        	update caseRec4;
        	caseRec4.Mfg_Trace_code__c = 'S363P49S3';
        	update caseRec4;
        	caseRec4.Mfg_Trace_code__c = 'S363V49S3';
        	update caseRec4;
        	caseRec4.Mfg_Trace_code__c = 'S363X49S3';
        	update caseRec4;
        	test.StopTest();
			
            for(Integer i=0 ; i<7 ; i++){
                //for Baker One
               Case test1 = [SELECT Id, IsReviewed__c FROM Case];
                test1.Product_Line__c = 'Testing Baker one';
                test1.PLCode__c = 'DS';
                test1.Trace_Code_Location__c = 'Can';
                String firstdigit = (i == 0 ? 'K' : (i == 1 ? 'O' : (i == 2 ? 'B' : 'A')));
                String fifthdigit = (i == 0 ? 'G' :
                                     (i == 1 ? 'O' :
                                     (i == 2 ? 'K' :
                                     (i == 3 ? 'T' :
                                     (i == 4 ? 'Y' :
                                     (i == 5 ? 'U' : 'Z'))))));
                test1.Mfg_Trace_code__c = firstdigit+'360'+fifthdigit+'1210';
                update test1;
            }

    }    
}