force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>AnswerID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Answer</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>QuestionID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Question</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Reimbursement</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Reimbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <label>Issue Name</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <formula>Issue__r.Purchase_Price__c</formula>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Transaction_Management_History__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Management_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Management History</label>
    <referenceTo>Transaction_Management_History__c</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Code_Mapping__c/Service_Code_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Service Request vs Service Group Code</description>
    <label>Service Code Mapping</label>
</CustomObject>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Store Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_Type__c.field-meta.xml
<CustomField>
    <fullName>Store_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store Type</label>
    <referenceTo>Store_Type__c</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Transaction_Management__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Management</label>
    <referenceTo>Transaction_Management__c</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_Type__c/Store_Type__c.object-meta.xml
<CustomObject>
    <label>Store Type</label>
    <nameField>
        <displayFormat>ST{00}</displayFormat>
        <label>Store Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>SurveyId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Issue__c/Survey_Issue__c.object-meta.xml
<CustomObject>
    <label>Survey Issue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Survey Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Issue__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Survey Issues</relationshipLabel>
    <relationshipName>Survey_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/fields/isReviewed__c.field-meta.xml
<CustomField>
    <fullName>isReviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for checking if the record is ready to send in feed.</description>
    <label>isReviewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Survey Issues</relationshipLabel>
    <relationshipName>Survey_Issues</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Survey Issues</relationshipLabel>
    <relationshipName>Survey_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Issues</relationshipLabel>
    <relationshipName>Survey_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction Management</label>
    <referenceTo>Transaction_Management__c</referenceTo>
    <relationshipLabel>Survey Issues</relationshipLabel>
    <relationshipName>Survey_Issues</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TFN__c/TFN__c.object-meta.xml
<CustomObject>
    <label>TFN</label>
    <nameField>
        <displayFormat>TFN-{0000}</displayFormat>
        <label>TFN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Toll Free Number</relationshipLabel>
    <relationshipName>Toll_Free_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/Transaction_Management__c.object-meta.xml
<CustomObject>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Management__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/TFN__c.field-meta.xml
<CustomField>
    <fullName>TFN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DNIS</label>
    <referenceTo>TFN__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management_History__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Transaction Management Histories</relationshipLabel>
    <relationshipName>Transaction_Management_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management_History__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <description>Operating company of the transaction.</description>
    <formula>TEXT(Transaction_Management__r.Operating_Company__r.OperatingCompany__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Operating company of the transaction.</inlineHelpText>
    <label>Operating Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IssueReviewDetailControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
/*
test class of issue review page
11/07/2016 Infogain – Created.
*/
@isTest
public class IssueReviewDetailControllerTest {

    // Testing constructor and checkMultipleReimbursements method when there is no reimbursement record created for the Issue
    // of IssueReviewDetailControllerTest controller
    static testMethod void validateIssueReviewDetailControllerNoReimbursement() {
        
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        testCase.IsReviewed__c = true;
        insert testCase;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        ApexPages.currentPage().getParameters().put('sortDirection','asc');
        ApexPages.currentPage().getParameters().put('sortExpression','cn');
        Test.startTest();
            IssueReviewDetailController controller = new IssueReviewDetailController(new ApexPages.StandardController(testCase));
        Test.stopTest();
    }
    
    // Testing constructor and checkMultipleReimbursements method when there is a reimbursement record created for the Issue
    // of IssueReviewDetailControllerTest controller
    static testMethod void validateIssueReviewDetailController() {
        
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
        Reimbursement__c testReimb = TestDataSetup.createReimbursement(testCase, 12);
        insert testReimb;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        Test.startTest();
            IssueReviewDetailController controller = new IssueReviewDetailController(new ApexPages.StandardController(testCase));
        Test.stopTest();
    }
    
    // Testing custom clone method of IssueReviewDetailControllerTest controller
    static testMethod void validateSetReview() {
        
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        testCase.IsReviewed__c = False;
        insert testCase;
        Reimbursement__c testReimb = TestDataSetup.createReimbursement(testCase, 12);
        testReimb.isReviewed__c = False;
        insert testReimb;
        Store_type__c storeTypeTest = TestDataSetup.createStoreType('ST10','Other');
        insert storeTypeTest ; 
        Store__c storeTest = TestDataSetup.createStore('WallMart',storeTypeTest);
        storeTest.Issue__c = testCase.Id;
        storeTest.isReviewed__c = False;
        insert storeTest;
        Question__c testQuest = TestDataSetup.createQuestion('Test Question', '1234','testType');
        insert testQuest;
        Answer__c testAns = TestDataSetup.createAnswer('Answer', '1234');
        insert testAns;
        Survey__c testSurvey = TestDataSetup.createSurvey('Test Survey');
        insert testSurvey;
        Survey_Issue__c testSurvIssue = TestDataSetup.createSurveyIssue(testAns, testQuest, testSurvey, testCase);
        testSurvIssue.isReviewed__c = False;
        testSurvIssue.Transaction__c = testTM.id;
        insert testSurvIssue;
        Transaction_Management_History__c testTMHis= TestDataSetup.createTMHis('CRC', testTM, 'endcall');
        insert testTMHis;
        Service_Code_Mapping__c testSerCode= TestDataSetup.createSerCode('APPROVALS','ISSUE_APPROVED');
        insert testSerCode;
        ApexPages.currentPage().getParameters().put('id',testCase.Id); 
        Test.startTest();
            IssueReviewDetailController controller = new IssueReviewDetailController(new ApexPages.StandardController(testCase));
            controller.setReview();
        Test.stopTest();
        //system.assertEquals(testCase.purchase_price__c,1200);
    }
    static testMethod void sortExpression_bc(){
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        testCase.IsReviewed__c = true;
        insert testCase;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        ApexPages.currentPage().getParameters().put('sortDirection','asc');
        ApexPages.currentPage().getParameters().put('sortExpression','bc');
        Test.startTest();
            IssueReviewDetailController controller = new IssueReviewDetailController(new ApexPages.StandardController(testCase));
        Test.stopTest();
    }
    static testMethod void sortExpression_pl(){
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        testCase.IsReviewed__c = true;
        insert testCase;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        ApexPages.currentPage().getParameters().put('sortDirection','asc');
        ApexPages.currentPage().getParameters().put('sortExpression','pl');
        Test.startTest();
            IssueReviewDetailController controller = new IssueReviewDetailController(new ApexPages.StandardController(testCase));
        Test.stopTest();
    }
    static testMethod void sortExpression_re(){
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        testCase.IsReviewed__c = true;
        insert testCase;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        ApexPages.currentPage().getParameters().put('sortDirection','asc');
        ApexPages.currentPage().getParameters().put('sortExpression','re');
        Test.startTest();
            IssueReviewDetailController controller = new IssueReviewDetailController(new ApexPages.StandardController(testCase));
        Test.stopTest();
    }
    static testMethod void sortExpression_cs(){
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        testCase.IsReviewed__c = true;
        insert testCase;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        ApexPages.currentPage().getParameters().put('sortDirection','asc');
        ApexPages.currentPage().getParameters().put('sortExpression','cs');
        Test.startTest();
            IssueReviewDetailController controller = new IssueReviewDetailController(new ApexPages.StandardController(testCase));
        Test.stopTest();
    }
    static testMethod void sortExpression_contn(){
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        testCase.IsReviewed__c = true;
        insert testCase;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        ApexPages.currentPage().getParameters().put('sortDirection','asc');
        ApexPages.currentPage().getParameters().put('sortExpression','contn');
        Test.startTest();
            IssueReviewDetailController controller = new IssueReviewDetailController(new ApexPages.StandardController(testCase));
        Test.stopTest();
    }
    static testMethod void sortExpression_cl(){
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        testCase.IsReviewed__c = true;
        insert testCase;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        ApexPages.currentPage().getParameters().put('sortDirection','asc');
        ApexPages.currentPage().getParameters().put('sortExpression','cl');
        Test.startTest();
            IssueReviewDetailController controller = new IssueReviewDetailController(new ApexPages.StandardController(testCase));
        Test.stopTest();
    }
    static testMethod void sortExpression_ca(){
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        testCase.IsReviewed__c = true;
        insert testCase;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        ApexPages.currentPage().getParameters().put('sortDirection','asc');
        ApexPages.currentPage().getParameters().put('sortExpression','ca');
        Test.startTest();
            IssueReviewDetailController controller = new IssueReviewDetailController(new ApexPages.StandardController(testCase));
        Test.stopTest();
    }
    
    
    static testMethod void validateGenerateLineValue(){
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        testCase.IsReviewed__c = true;
        insert testCase;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        ApexPages.currentPage().getParameters().put('sortDirection','asc');
        ApexPages.currentPage().getParameters().put('sortExpression','contn');
        Test.startTest();
            IssueReviewDetailController controller = new IssueReviewDetailController(new ApexPages.StandardController(testCase));
        	testCase.DateCodeUnit__c = 'L';
        	testCase.Mfg_Trace_code__c = 'H025L1434';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeUnit__c = 'U';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeUnit__c = 'J';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeUnit__c = 'N';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeUnit__c = 'P';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeUnit__c = 'E';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeRptFactory__c = 'MC_USSTC';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeRptFactory__c = 'PMIP';
        	controller.generateLineValue(testCase);
        	testCase.Product_Line__c = 'TOBACCO DERIVED NICOTINE POUCH';
        	testCase.DateCodeUnit__c = 'U';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeUnit__c = 'J';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeUnit__c = 'N';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeUnit__c = 'P';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeUnit__c = 'E';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeUnit__c = 'XXX';
        	controller.generateLineValue(testCase);
        	testCase.DateCodeRptFactory__c = 'MC_JMC';
        	testCase.Mfg_Trace_code__c = '999999999';
        	testCase.DateCodeUnit__c = 'K';
        	controller.generateLineValue(testCase);
        	controller.generateLineValueDateCodeRptFactoryMCUSSTC('K');
        	controller.generateLineValueDateCodeRptFactoryMCUSSTC('G');
        	controller.generateLineValueDateCodeRptFactoryMCUSSTC('T');
        	controller.generateLineValueDateCodeRptFactoryMCUSSTC('Y');
        	controller.generateLineValueDateCodeRptFactoryMCUSSTC('Z');
        	controller.generateLineValueDateCodeRptFactoryMCUSSTC('XXX');
        
        	
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('A');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('B');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('C');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('E');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('H');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('I');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('L');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('M');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('N');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('P');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('R');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('S');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('V');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('2');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitNumber('XXX');
        
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('E');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('H');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('I');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('L');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('N');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('S');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('V');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('2');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('3');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('4');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('5');
        	controller.generateLineValueDateCodeRptFactoryNSDateCodeUnitAlpha('XXX');
        
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('A');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('B');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('G');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('I');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('J');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('K');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('M');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('O');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('P');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('Y');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('R');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('W');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('X');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('Z');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('XXX');
        
        
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('E');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('F');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('G');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('J');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('K');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('M');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('0');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('W');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('X');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('Y');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('Z');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitNumber('XXX');
        
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('A');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('B');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('G');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('I');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('J');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('K');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('M');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('O');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('P');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('Y');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('R');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('W');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('X');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('Z');
        	controller.generateLineValueDateCodeRptFactoryFPDateCodeUnitAlpha('XXX');
        
        	controller.checkIsAlpha('A');
        	controller.checkIsNumber('5');

        Test.stopTest();
    }
}