force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>AnswerID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Answer</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <description>Feed Outbound - Date format.</description>
    <formula>IF(DATEVALUE(CreatedDate) &gt;=
DATE(YEAR(DATEVALUE(CreatedDate)),3,1)
+
(
14-
CASE(MOD(DATE(YEAR(DATEVALUE(CreatedDate)),3,1)-DATE(1900,1,7),7),
0,7,MOD(DATE ( YEAR (DATEVALUE(CreatedDate)),3,1) - DATE (1900,1,7),7))
)
&amp;&amp;
DATEVALUE(CreatedDate) &lt;
DATE(YEAR(DATEVALUE(CreatedDate)),11,1)
+
(
7-
CASE(MOD(DATE(YEAR(DATEVALUE(CreatedDate)),11,1)-DATE(1900,1,7),7),
0,7,MOD(DATE(YEAR(DATEVALUE(CreatedDate)),11,1)-DATE(1900,1,7),7))
),
MID(TEXT(CreatedDate-4/24),6,2)+&quot;/&quot;
+MID(TEXT(CreatedDate-4/24),9,2)+&quot;/&quot;
+MID(TEXT(CreatedDate-4/24),0,4) + &quot; &quot;
+MID(TEXT(CreatedDate-4/24),11,9)
,
MID( TEXT(CreatedDate-5/24),6,2)+&quot;/&quot;
+MID( TEXT(CreatedDate-5/24),9,2)+&quot;/&quot;
+MID( TEXT(CreatedDate-5/24),0,4)+&quot; &quot;
+MID(TEXT(CreatedDate-5/24),11,9)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CreatedDate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/DefEndPos__c.field-meta.xml
<CustomField>
    <fullName>DefEndPos__c</fullName>
    <description>Feed Outbound - Hardcode value 0.</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DefEndPos</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/DefStartPos__c.field-meta.xml
<CustomField>
    <fullName>DefStartPos__c</fullName>
    <description>FeedOutbound - Hardcode value 0.</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DefStartPos</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/IsDeleted__c.field-meta.xml
<CustomField>
    <fullName>IsDeleted__c</fullName>
    <description>Feed Outbound - IsDeleted Hard code value 0</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsDeleted</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/LastModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedDate__c</fullName>
    <description>Feed Outbound - DateFormat.</description>
    <formula>IF ( DATEVALUE(LastModifiedDate) &gt;=
DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1)
+
(
14-
CASE( MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1) - DATE (1900,1,4),4) ,
0,4,MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1) - DATE (1900,1,4),4))
)
&amp;&amp;
DATEVALUE(LastModifiedDate) &lt;
DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1)
+
(
4-
CASE( MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1) - DATE (1900,1,4),4) ,
0,4,MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1) - DATE (1900,1,4),4))
),
MID( TEXT(LastModifiedDate- 4/24) , 6, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 4/24) , 9, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 4/24) , 0, 4) + &quot; &quot;+MID(TEXT(LastModifiedDate- 4/24), 11, 9)
,
MID( TEXT(LastModifiedDate- 5/24) , 6, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 5/24) , 9, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 5/24) , 0, 4) + &quot; &quot;+MID(TEXT(LastModifiedDate- 5/24), 11, 9)
)</formula>
    <label>LastModifiedDate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/PMAnswerID__c.field-meta.xml
<CustomField>
    <fullName>PMAnswerID__c</fullName>
    <label>PMAnswerID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AnswerTriggerHandler.cls
/************************************************************************ 
Author: Randolf Suplito
Date: 08/22/2022
Description: This handler class is for AnswerTrigger
*************************************************************************/

public class AnswerTriggerHandler {

    public static Boolean isFirstTime = true;
    
    public static void createCallout(List<Answer__c> triggerNewList, Map<Id,Answer__c> triggerNewMap) {
		
        Map<String,String> createdComNameMap = new Map<String,String>();
        Map<String,String> modifiedComNameMap = new Map<String,String>();
        String lastModifiedUser;

		jsonRequestDTO jsonPayload = new jsonRequestDTO();
        List<answerDTO> answerDTOList = new List<answerDTO>();
        
        for(Answer__c answerRec : [SELECT Id, CreatedBy.CommunityNickname, LastModifiedBy.CommunityNickname FROM Answer__c WHERE Id IN :triggerNewMap.keyset()]) {
            createdComNameMap.put(answerRec.Id, answerRec.CreatedBy.CommunityNickname);
            modifiedComNameMap.put(answerRec.Id, answerRec.LastModifiedBy.CommunityNickname);
            lastModifiedUser = answerRec.LastModifiedBy.CommunityNickname;
        }
        
        for(Answer__c answerRec : triggerNewList) {
            answerDTO aDTO = new answerDTO();
            aDTO.ANSWERID = answerRec.Name != null ? answerRec.Name : '';
            aDTO.ANSWER = answerRec.Answer__c != null ? answerRec.Answer__c : '';
            if(answerRec.Active__c != null && answerRec.Active__c) { 
                aDTO.ACTIVEFLAG = '1'; 
            } else if(answerRec.Active__c != null && !answerRec.Active__c) { 
                aDTO.ACTIVEFLAG = '0'; 
            } else if(answerRec.Active__c == null) {
                aDTO.ACTIVEFLAG = '';
            }
            aDTO.PMANSWERID = answerRec.PMAnswerID__c != null ? String.valueOf(answerRec.PMAnswerID__c) : '';
            aDTO.DEFSTARTPOS = answerRec.DefStartPos__c != null ? answerRec.DefStartPos__c : '';
            aDTO.DEFENDPOS = answerRec.DefEndPos__c != null ? answerRec.DefEndPos__c : '';
            aDTO.CREATEDDATE = answerRec.CreatedDate__c != null ? answerRec.CreatedDate__c : '';
            aDTO.CREATEDBY = createdComNameMap.get(answerRec.Id);
            aDTO.MODIFIEDDATE = answerRec.LastModifiedDate__c != null ? answerRec.LastModifiedDate__c : '';
            aDTO.MODIFIEDBY = modifiedComNameMap.get(answerRec.Id);
            aDTO.ISDELETED = answerRec.IsDeleted__c != null ? answerRec.IsDeleted__c : '';
            
            answerDTOList.add(aDTO);
        }
        
        if(!answerDTOList.isEmpty()) {
            jsonPayload.userName = lastModifiedUser;
            jsonPayload.SurveyAnswer = answerDTOList;
            System.debug('jsonPayload: ' + JSON.Serialize(jsonPayload));
        	APIDataCalloutServices.dataFeedCallout(JSON.Serialize(jsonPayload), ConstantClass.ANSWER_CALLOUT_NAME);
        }
    }
    
    public class jsonRequestDTO {
        public String userName {get; set;}
        public List<answerDTO> SurveyAnswer;
    }
    
    public class answerDTO {
        public String ANSWERID {get; set;}
        public String ANSWER {get; set;}
        public String ACTIVEFLAG {get; set;}
        public String PMANSWERID {get; set;}
        public String DEFSTARTPOS {get; set;}
        public String DEFENDPOS {get; set;}
        public String CREATEDDATE {get; set;}
        public String CREATEDBY {get; set;}
        public String MODIFIEDDATE {get; set;}
        public String MODIFIEDBY {get; set;}
        public String ISDELETED {get; set;}
    }
}