force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/BrandCode__c.field-meta.xml
<CustomField>
    <fullName>BrandCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BrandCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/BrandFamily__c.field-meta.xml
<CustomField>
    <fullName>BrandFamily__c</fullName>
    <description>Feed Outbound- Brand</description>
    <encryptionScheme>None</encryptionScheme>
    <label>BrandFamily</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/CodeCategory__c.field-meta.xml
<CustomField>
    <fullName>CodeCategory__c</fullName>
    <description>Feed Outbound- Brand</description>
    <formula>&apos;BRANDS&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/CodeType__c.field-meta.xml
<CustomField>
    <fullName>CodeType__c</fullName>
    <description>Feed Outbound- Brand</description>
    <formula>&apos;ALL&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/CRC_Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>CRC_Operating_Company__c</fullName>
    <label>CRC Operating Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>NAT_SHERMAN</fullName>
            </value>
            <value>
                <fullName>NUMARK</fullName>
            </value>
            <value>
                <fullName>NUMRK</fullName>
            </value>
            <value>
                <fullName>PMIP</fullName>
            </value>
            <value>
                <fullName>PMPR</fullName>
            </value>
            <value>
                <fullName>PMUSA</fullName>
            </value>
            <value>
                <fullName>USST</fullName>
            </value>
            <value>
                <fullName>USSTC</fullName>
            </value>
            <value>
                <fullName>USSTH</fullName>
            </value>
            <value>
                <fullName>USSTN</fullName>
            </value>
            <value>
                <fullName>USSTP</fullName>
            </value>
            <value>
                <fullName>NJOY</fullName>
            </value>
            <value>
                <fullName>USSTV</fullName>
            </value>
            <value>
                <fullName>PMUSAH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Brand Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/DisplayDescription__c.field-meta.xml
<CustomField>
    <fullName>DisplayDescription__c</fullName>
    <description>Feed Outbound - Hard Code empty value.</description>
    <formula>Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DisplayDescription</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>DisplayOrder__c</fullName>
    <description>Feed Outbound - Hardcode value &apos;0&apos;</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DisplayOrder</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/ModuleName__c.field-meta.xml
<CustomField>
    <fullName>ModuleName__c</fullName>
    <description>Feed Outbound -Brand</description>
    <formula>&apos;ALTRIA&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Module Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/ProductLineCode__c.field-meta.xml
<CustomField>
    <fullName>ProductLineCode__c</fullName>
    <description>Feed Outbound - Product Line Code</description>
    <formula>Product_Line__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProductLineCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/ProductLineFlag__c.field-meta.xml
<CustomField>
    <fullName>ProductLineFlag__c</fullName>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProductLineFlag</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/ScreenName__c.field-meta.xml
<CustomField>
    <fullName>ScreenName__c</fullName>
    <formula>&apos;GLOBAL&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Screen Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/TenantId__c.field-meta.xml
<CustomField>
    <fullName>TenantId__c</fullName>
    <description>Feed Outbound -Brand</description>
    <formula>&apos;ALORICAALTRIA&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TenantId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/USTDateType__c.field-meta.xml
<CustomField>
    <fullName>USTDateType__c</fullName>
    <description>Feed Outbound -Brand</description>
    <encryptionScheme>None</encryptionScheme>
    <label>USTDateType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BrandTriggerHandler.cls
/************************************************************************ 
Author: Randolf Suplito
Date: 08/18/2022
Description: This handler class is for BrandTrigger
*************************************************************************/

public class BrandTriggerHandler {

    public static Boolean isFirstTime = true;
    
    public static void createCallout(List<Brand__c> triggerNewList, Map<Id,Brand__c> triggerNewMap) {
        
        Map<String,String> createdComNameMap = new Map<String,String>();
        Map<String,String> modifiedComNameMap = new Map<String,String>();
        String lastModifiedUser;
		
		jsonRequestDTO jsonPayload = new jsonRequestDTO();
        List<brandDTO> brandDTOList = new List<brandDTO>();
        
        for(Brand__c brandRec : [SELECT Id, CreatedBy.CommunityNickname, LastModifiedBy.CommunityNickname FROM Brand__c WHERE Id IN :triggerNewMap.keyset()]) {
            createdComNameMap.put(brandRec.Id, brandRec.CreatedBy.CommunityNickname);
            modifiedComNameMap.put(brandRec.Id, brandRec.LastModifiedBy.CommunityNickname);
            lastModifiedUser = brandRec.LastModifiedBy.CommunityNickname;
        }
        
        for(Brand__c brandRec : triggerNewList) {
            brandDTO bDTO = new brandDTO();
            bDTO.TENANTID = brandRec.TenantId__c != null ? brandRec.TenantId__c : '';
            bDTO.ModuleName = brandRec.ModuleName__c != null ? brandRec.ModuleName__c : '';
            bDTO.ScreenName = brandRec.ScreenName__c != null ? brandRec.ScreenName__c : '';
            bDTO.CodeCategory = brandRec.CodeCategory__c != null ? brandRec.CodeCategory__c : '';
            bDTO.CodeType = brandRec.CodeType__c != null ? brandRec.CodeType__c : '';
            bDTO.Code = brandRec.Code__c != null ? brandRec.Code__c : '';
            bDTO.BrandCode = brandRec.BrandCode__c != null ? brandRec.BrandCode__c : '';
            bDTO.BrandFamily = brandRec.BrandFamily__c != null ? brandRec.BrandFamily__c : '';
            bDTO.Description = brandRec.Description__c != null ? brandRec.Description__c : '';
            bDTO.DisplayDescription = brandRec.DisplayDescription__c != null ? brandRec.DisplayDescription__c : '';
            bDTO.DisplayOrder = brandRec.DisplayOrder__c != null ? brandRec.DisplayOrder__c : '';
            bDTO.ProductLineFlag = brandRec.ProductLineFlag__c != null ? brandRec.ProductLineFlag__c : '';
            bDTO.OperatingCompany = brandRec.Operating_Company__c != null ? brandRec.Operating_Company__c : '';
            bDTO.CRCOperatingCompany = brandRec.CRC_Operating_Company__c != null ? brandRec.CRC_Operating_Company__c : '';
            bDTO.ProductLine = brandRec.ProductLineCode__c != null ? brandRec.ProductLineCode__c : '';
            bDTO.USTDateType = brandRec.USTDateType__c != null ? brandRec.USTDateType__c : '';
            if(brandRec.IsActive__c != null && brandRec.IsActive__c) {
                bDTO.Active_flag = 'Y';
            } else if(brandRec.IsActive__c != null && !brandRec.IsActive__c) {
                bDTO.Active_flag = 'N';
            } else if(brandRec.IsActive__c == null) {
                bDTO.Active_flag = '';
            }
            bDTO.CreatedDate = brandRec.CreatedDate__c != null ? brandRec.CreatedDate__c : '';
            bDTO.CreatedBy = createdComNameMap.get(brandRec.Id);
            bDTO.ModifiedDate = brandRec.LastModifiedDate__c != null ? brandRec.LastModifiedDate__c : '';
            bDTO.ModifiedBy = modifiedComNameMap.get(brandRec.Id);
            
            brandDTOList.add(bDTO);
        }
        
        if(!brandDTOList.isEmpty()) {
            jsonPayload.userName = lastModifiedUser;
            jsonPayload.BrandCode = brandDTOList;
            System.debug('jsonPayload: ' + JSON.Serialize(jsonPayload));
        	APIDataCalloutServices.dataFeedCallout(JSON.Serialize(jsonPayload), ConstantClass.BRAND_CALLOUT_NAME);
        }
    }
    
    public class jsonRequestDTO {
        public String userName {get; set;}
        public List<brandDTO> BrandCode;
    }
    
    public class brandDTO {
        public String TENANTID {get; set;}
        public String ModuleName {get; set;}
        public String ScreenName {get; set;}
        public String CodeCategory {get; set;}
        public String CodeType {get; set;}
        public String Code {get; set;}
        public String BrandCode {get; set;}
        public String BrandFamily {get; set;}
        public String Description {get; set;}
        public String DisplayDescription {get; set;}
        public String DisplayOrder {get; set;}
        public String ProductLineFlag {get; set;}
        public String OperatingCompany {get; set;}
        public String CRCOperatingCompany {get; set;}
        public String ProductLine {get; set;}
        public String USTDateType {get; set;}
        public String Active_flag {get; set;}
        public String CreatedDate {get; set;}
        public String CreatedBy {get; set;}
        public String ModifiedDate {get; set;}
        public String ModifiedBy {get; set;}
    }
}