force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Brand Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Hierarchy__c/Brand_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Brand Hierarchy</label>
    <nameField>
        <displayFormat>BH{0000}</displayFormat>
        <label>Brand Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Hierarchy__c/fields/Brand_Code__c.field-meta.xml
<CustomField>
    <fullName>Brand_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Brand Hierarchies</relationshipLabel>
    <relationshipName>Brand_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Hierarchy__c/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <label>Filter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2A</fullName>
            </value>
            <value>
                <fullName>2A - PI Approved</fullName>
            </value>
            <value>
                <fullName>500mA</fullName>
            </value>
            <value>
                <fullName>500mA - EU</fullName>
            </value>
            <value>
                <fullName>500mA - NZ</fullName>
            </value>
            <value>
                <fullName>500mA - UK</fullName>
            </value>
            <value>
                <fullName>CVR 2.4</fullName>
            </value>
            <value>
                <fullName>CVR2.6.8G</fullName>
            </value>
            <value>
                <fullName>CVR2.6.8G &amp; BVR2.4L</fullName>
            </value>
            <value>
                <fullName>Filter</fullName>
            </value>
            <value>
                <fullName>Filtered</fullName>
            </value>
            <value>
                <fullName>Flavormax</fullName>
            </value>
            <value>
                <fullName>GSAW-001</fullName>
            </value>
            <value>
                <fullName>LED Green</fullName>
            </value>
            <value>
                <fullName>LED Green - UK</fullName>
            </value>
            <value>
                <fullName>LED Red</fullName>
            </value>
            <value>
                <fullName>LED Red - UK</fullName>
            </value>
            <value>
                <fullName>Multifilter</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Non-Filtered</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Original</fullName>
            </value>
            <value>
                <fullName>PI Approved</fullName>
            </value>
            <value>
                <fullName>Plastic</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>US to EU</fullName>
            </value>
            <value>
                <fullName>Vapors</fullName>
            </value>
            <value>
                <fullName>Wood</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Hierarchy__c/fields/Packaging__c.field-meta.xml
<CustomField>
    <fullName>Packaging__c</fullName>
    <label>Packaging</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10-2-Pack Upright Promo 201002</fullName>
            </value>
            <value>
                <fullName>10 Ct Display Of 7 - Pack</fullName>
            </value>
            <value>
                <fullName>10 Ct  Tray-5-Pack</fullName>
            </value>
            <value>
                <fullName>10ct Tray-5-Packpromo201001</fullName>
            </value>
            <value>
                <fullName>10 Ct Tray-5-Packpromo201001</fullName>
            </value>
            <value>
                <fullName>10 Ct Tray Of 7 - Pack</fullName>
            </value>
            <value>
                <fullName>10 - Pack</fullName>
            </value>
            <value>
                <fullName>1 1/2 Oz Packet</fullName>
            </value>
            <value>
                <fullName>12 Oz Can</fullName>
            </value>
            <value>
                <fullName>1 3/8 Oz Packet</fullName>
            </value>
            <value>
                <fullName>14 Oz Can</fullName>
            </value>
            <value>
                <fullName>1-PACK</fullName>
            </value>
            <value>
                <fullName>25 -Count Upright</fullName>
            </value>
            <value>
                <fullName>25 -COUNT UPRIGHT $0.79</fullName>
            </value>
            <value>
                <fullName>25 -COUNT UPRIGHT $0.89</fullName>
            </value>
            <value>
                <fullName>25 -COUNT UPRIGHT $0.99</fullName>
            </value>
            <value>
                <fullName>25 -Count Upright Singles</fullName>
            </value>
            <value>
                <fullName>25 -Ct  Upright</fullName>
            </value>
            <value>
                <fullName>25s Hard Pack</fullName>
            </value>
            <value>
                <fullName>2 Pack</fullName>
            </value>
            <value>
                <fullName>2 Pack 1.49</fullName>
            </value>
            <value>
                <fullName>2 - Pack Foil</fullName>
            </value>
            <value>
                <fullName>2 - Pack Foil- $0.99</fullName>
            </value>
            <value>
                <fullName>2 - Pack Foil- $1.39</fullName>
            </value>
            <value>
                <fullName>2 - PACK FOIL $1.75</fullName>
            </value>
            <value>
                <fullName>2 - Pack Foil B2G $0.50 OFF</fullName>
            </value>
            <value>
                <fullName>2 - Pack Foil CGR</fullName>
            </value>
            <value>
                <fullName>2 - Pack Foil Promo $1.49</fullName>
            </value>
            <value>
                <fullName>2 - Pack Foil Promo $2.29</fullName>
            </value>
            <value>
                <fullName>2 - Pack Foil Promo 1.49</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Hierarchy__c/fields/UPC__c.field-meta.xml
<CustomField>
    <fullName>UPC__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UPC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cause__c/Cause__c.object-meta.xml
<CustomObject>
    <label>Cause</label>
    <nameField>
        <displayFormat>CAU{0000}</displayFormat>
        <label>Cause Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Causes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cause__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cause Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL{0000}</displayFormat>
        <label>Classification Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Classification Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <displayFormat>GR{0000}</displayFormat>
        <label>Group Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Group Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/Issue_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Issue Hierarchy</label>
    <nameField>
        <displayFormat>IH{0000}</displayFormat>
        <label>Issue Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cause</label>
    <referenceTo>Cause__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issue Type</label>
    <referenceTo>Issue_Type__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reason</label>
    <referenceTo>Reason__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Type__c/Issue_Type__c.object-meta.xml
<CustomObject>
    <label>Issue Type</label>
    <nameField>
        <displayFormat>IT{0000}</displayFormat>
        <label>Issue Type  Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IssueTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Issue Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reason__c/Reason__c.object-meta.xml
<CustomObject>
    <label>Reason</label>
    <nameField>
        <displayFormat>REA{0000}</displayFormat>
        <label>Reason Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reason__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store_Type__c/Store_Type__c.object-meta.xml
<CustomObject>
    <label>Store Type</label>
    <nameField>
        <displayFormat>ST{00}</displayFormat>
        <label>Store Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OACValidation.cls
public class OACValidation {
    public  List<string> checkMandatoryFields(IQOSResponseClass.jsonWrapper_CEA jsonBody){
        List<Store_Type__c> ST;
        String valMessage = '';
        String sqlMessage = '';
        boolean isValid = true;
        List<String> finalMessage = new List<String>();
        
        map<string, Brand_Hierarchy__c> BH_Map = new map<string, Brand_Hierarchy__c>();
        map<string, Issue_Hierarchy__c> IH_Map = new map<string, Issue_Hierarchy__c>();
        List<Brand_Hierarchy__c> BH = new List<Brand_Hierarchy__c>();
        List<Issue_Hierarchy__c> IH = new List<Issue_Hierarchy__c>();
        List<String> BHList = new List<String> ();
        List<String> IHList = new List<String> ();
        
        if(jsonBody.IssueInfo.size() > 0){
            //system.assertequals(null, jsonBody.IssueInfo);
            System.debug('test'+jsonBody.IssueInfo);
            for(integer jsonIssue = 0 ; jsonIssue < jsonBody.IssueInfo.size(); jsonIssue++ ){
                if(jsonBody.IssueInfo[jsonIssue].BrandHierarchy != null && jsonBody.IssueInfo[jsonIssue].BrandHierarchy != ''){
                    BHList.add(jsonBody.IssueInfo[jsonIssue].BrandHierarchy);
                }
                if(jsonBody.IssueInfo[jsonIssue].IssueHierarchy != null && jsonBody.IssueInfo[jsonIssue].IssueHierarchy != '' ){
                    IHList.add(jsonBody.IssueInfo[jsonIssue].IssueHierarchy);
                }
            }
        }
        //getting the brand hierarcy
        if(BHList.size() > 0){
            BH = [Select Name, Id, UPC__c, Brand_Code__c, Filter__c, Packaging__c,Brand_Code__r.Name from Brand_Hierarchy__c Where Name IN: BHList ];
        }
        if(BH.size() > 0){
            for(Brand_Hierarchy__c b: BH){
                BH_Map.put(b.Name, b);
            }   
        }//end of brand hierarcy
        
        //getting the issue hierarcy
        if(IHList.size() > 0){
            IH = [Select Name, Id, Classification__c,Issue_Type__c, Group__c,Reason__c, Cause__c, Classification__r.Description__c, Reason__r.Description__c,  Issue_Type__r.Description__c,Cause__r.Description__c,Group__r.Description__c from Issue_Hierarchy__c where  Name IN: IHList];
        }
        if(IH.size() > 0){
            for(Issue_Hierarchy__c i: IH){
                IH_Map.put(i.Name, i);
            }   
        }//end of issue hierarcy
        
        
        //Case fields
        if(jsonBody.IssueInfo.size() > 0){
            for(integer jsonIssue = 0 ; jsonIssue < jsonBody.IssueInfo.size(); jsonIssue++ ){
                String caseValMessage = '';
                String caseSqlMessage = '';
                if(jsonBody.IssueInfo[jsonIssue].BrandHierarchy == ''){
                    caseValMessage = caseValMessage + 'Brand Hierarchy, ';
                    isValid = false;
                }
                else{
                    if(!BH_Map.containskey(jsonBody.IssueInfo[jsonIssue].BrandHierarchy)){
                        caseSqlMessage = caseSqlMessage + 'Brand Hierarchy not Valid, ';
                        isValid = false;
                    }
                }

                if(jsonBody.IssueInfo[jsonIssue].AgentID == ''){
                    caseValMessage = caseValMessage + 'Agent ID, ';
                    isValid = false;
                }
                if(jsonBody.IssueInfo[jsonIssue].Comment == ''){
                    caseValMessage = caseValMessage + 'Comment, ';
                    isValid = false;
                }
                if(jsonBody.IssueInfo[jsonIssue].ComplaintSource == ''){
                    caseValMessage = caseValMessage + 'Complaint Source, ';
                    isValid = false;
                }
                if(jsonBody.IssueInfo[jsonIssue].ReferenceID == ''){
                    caseValMessage = caseValMessage + 'Reference ID, ';
                    isValid = false;
                }
                if(jsonBody.IssueInfo[jsonIssue].IssueHierarchy == ''){
                    caseValMessage = caseValMessage + 'Issue Hierarchy, ';
                    isValid = false;
                }
                else{
                    if(!IH_Map.containskey(jsonBody.IssueInfo[jsonIssue].IssueHierarchy)){
                        caseSqlMessage = caseSqlMessage + 'Issue Hierarchy not Valid, ';
                        isValid = false;
                    }
                }

                if(jsonBody.IssueInfo[jsonIssue].PurchasePrice == null){
                    caseValMessage = caseValMessage + 'Purchase Price, ';
                    isValid = false;
                }
               /* if(jsonBody.IssueInfo[jsonIssue].ReimbursedOrRepIndicator == ''){
                    caseValMessage = caseValMessage + 'Reimbursed Or Replaced Indicator, ';
                    isValid = false;
                }*/
                /*if(jsonBody.IssueInfo[jsonIssue].ThirdPartyRA == null){
                    caseValMessage = caseValMessage + 'Third Party Reimbursement Amount, ';
                    isValid = false;
                }*/
                    
                if(caseValMessage != ''){
                    caseValMessage = caseValMessage.removeEnd(', ') + ' cannot be null for Issue Reference ID: ' + jsonBody.IssueInfo[jsonIssue].ReferenceID;
                    if(caseSqlMessage != ''){
                        caseValMessage = caseSqlMessage + ' ' + caseValMessage;
                    }
                    finalMessage.add(caseValMessage);
                }
                
                if(caseSqlMessage != '' && caseValMessage == ''){
                        caseSqlMessage = caseSqlMessage.removeEnd(', ') + + ' for Issue Reference ID: ' + jsonBody.IssueInfo[jsonIssue].ReferenceID;
                        finalMessage.add(caseSqlMessage);
                }
                
                caseValMessage = '';
                caseSqlMessage = '';
                
            }
            
        }
        

        // End of case fields
        
        //Contact Fields
        if(jsonBody.ContactInfo.firstName == ''){
            valMessage = valMessage + 'First Name, ';
            isValid = false;
        }
        if(jsonBody.ContactInfo.lastName == ''){
            valMessage = valMessage + 'Last Name, ';
            isValid = false;
        }
        if(jsonBody.ContactInfo.addressLine1 == ''){
            valMessage = valMessage + 'Address Line 1, ';
            isValid = false;
        }
        if(jsonBody.ContactInfo.zip == ''){
            valMessage = valMessage + 'Zip, ';
            isValid = false;
        }
        if(jsonBody.ContactInfo.city == ''){
            valMessage = valMessage + 'City, ';
            isValid = false;
        }
        if(jsonBody.ContactInfo.state == ''){
            valMessage = valMessage + 'State, ';
            isValid = false;
        }
        if(jsonBody.ContactInfo.addressVerified == null){
            valMessage = valMessage + 'Address Verified, ';
            isValid = false;
        }
        if(jsonBody.ContactInfo.dob == ''){
            valMessage = valMessage + 'DOB, '; 
            isValid = false;
        }
        if(jsonBody.ContactInfo.ageVerified == null){
            valMessage = valMessage + 'Age Verified, ';
            isValid = false;
        }
        // end of contact fields
        //Store Field
        if(jsonBody.StoreInfo.StoreType == ''){
            valMessage = valMessage + 'Store Type, ';
            isValid = false;
        }
        else{
            ST = [Select Id, Description__c from Store_Type__c where Description__c =: jsonBody.StoreInfo.StoreType limit 1];
            //system.assertequals(null,ST);
            if(ST.isEmpty()){
                sqlMessage = sqlMessage + 'Store Type not Valid. ';
                isValid = false;
            }
        }
        //Store Field
        if(jsonBody.StoreInfo.StoreName == ''){  
            valMessage = valMessage + 'Store Name, ';
            isValid = false;
        }
        
        if(valMessage != ''){
            valMessage = valMessage.removeEnd(', ') + ' cannot be null.';
            if(sqlMessage != ''){
                valMessage = valMessage + ' ' + sqlMessage;
            }
            finalMessage.add(valMessage);
        }
        
        if(sqlMessage != '' && valMessage == ''){
            //sqlMessage = valMessage + ' ' + sqlMessage;
            finalMessage.add(sqlMessage);
        }
        
        if(finalMessage.size() > 0){
            return finalMessage;
        }else{
            finalMessage.clear();
            return finalMessage;
        }
        
        /*if(isValid == false){
            if(valMessage!= ''){
                valMessage = valMessage.removeEnd(',') + ' cannot be null for Issue Reference ID: ' + jsonBody.IssueInfo.ReferenceID;
            }
            if(sqlMessage != ''){
                return valMessage + ' ' + sqlMessage;
            }
            else{
                return valMessage;
            }
        }
        else{
            return null;
        }*/
    }


}