force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/IsCorrespondence__c.field-meta.xml
<CustomField>
    <fullName>IsCorrespondence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCorrespondence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/Op_Company__c.field-meta.xml
<CustomField>
    <fullName>Op_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>OpCo</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence_Fulfilment__c/Correspondence_Fulfilment__c.object-meta.xml
<CustomObject>
    <label>Correspondence &amp; Fulfilment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Correspondence &amp; Fulfilment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence &amp; Fulfilments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence_Fulfilment__c/fields/BCode__c.field-meta.xml
<CustomField>
    <fullName>BCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Brand Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence_Fulfilment__c/fields/Brand_Corres__c.field-meta.xml
<CustomField>
    <fullName>Brand_Corres__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Correspondence &amp; Fulfilments</relationshipLabel>
    <relationshipName>Correspondence_Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence_Fulfilment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence/Fulfilments</relationshipLabel>
    <relationshipName>Correspondence_Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence_Fulfilment__c/fields/DocType__c.field-meta.xml
<CustomField>
    <fullName>DocType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Feed outbound- Correspondence</description>
    <label>Document Type</label>
    <referenceTo>DocumentType__c</referenceTo>
    <relationshipLabel>Correspondence &amp; Fulfilments</relationshipLabel>
    <relationshipName>Correspondence_Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence_Fulfilment__c/fields/MasterId__c.field-meta.xml
<CustomField>
    <fullName>MasterId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Master ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Type__c/Customer_Type__c.object-meta.xml
<CustomObject>
    <label>Customer Type</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Customer Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Type__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Type Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentType__c/DocumentType__c.object-meta.xml
<CustomObject>
    <label>Document Type</label>
    <nameField>
        <displayFormat>DT-{0000000}</displayFormat>
        <label>Document Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentType__c/fields/isReimbursement__c.field-meta.xml
<CustomField>
    <fullName>isReimbursement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isReimbursement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentType__c/fields/isTrade__c.field-meta.xml
<CustomField>
    <fullName>isTrade__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTrade</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentType__c/fields/Op_Company__c.field-meta.xml
<CustomField>
    <fullName>Op_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>OpCo</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Document Types</relationshipLabel>
    <relationshipName>Document_Types</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentType__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <formula>Text(Op_Company__r.OperatingCompany__c)</formula>
    <label>Operating Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentType__c/fields/showMasterField__c.field-meta.xml
<CustomField>
    <fullName>showMasterField__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mater ID Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Op_Company__c.field-meta.xml
<CustomField>
    <fullName>Op_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpCo</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Product Lines</relationshipLabel>
    <relationshipName>Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFN__c/TFN__c.object-meta.xml
<CustomObject>
    <label>TFN</label>
    <nameField>
        <displayFormat>TFN-{0000}</displayFormat>
        <label>TFN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Toll Free Number</relationshipLabel>
    <relationshipName>Toll_Free_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/Transaction_Management__c.object-meta.xml
<CustomObject>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Management__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/TFN__c.field-meta.xml
<CustomField>
    <fullName>TFN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DNIS</label>
    <referenceTo>TFN__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CorrespondenceControllerTest.cls
@isTest
public class CorrespondenceControllerTest {


    //Validate Constructor.
    static testMethod void validateConstructor() {
         
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Customer_Type__c testCustType = TestDataSetup.createCustType('C', 'CONSUMERS', True, 'test');
        insert testCustType;
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL1', testOpCo);
        insert testPL;
        Brand__c testBrand = TestDataSetup.createBrand('Test Brand','12345',testPL, testOpCo);
        insert testBrand;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
        DocumentType__c testDoc = TestDataSetup.createDoc('Description', 'Outbound', 'Test Category', 'TestCode', 'FileTest', testOpCo, '123456');
        testDoc.isTrade__c = True;
        insert testDoc;
        Correspondence_Fulfilment__c testCor = TestDataSetup.createCor('Test Letter', bdate, testBrand);
        testCor.Contact__c = testCont.Id;
        testCor.DocType__c = testDoc.Id;
        testCor.MasterId__c = '12345';
        testCor.isReimbursement__c = True;
        insert testCor;
        Cookie tranId = ApexPages.currentPage().getCookies().get('customerRecType');
    
        // If this is the first time the user is accessing the page, 
        // create a new cookie with name 'counter', an initial value of '1', 
        // path 'null', maxAge '-1', and isSecure 'false'. 
        
         tranId = new Cookie('customerRecType','Consumer',null,-1,false);
        
        // If this isn't the first time the user is accessing the page
        // create a new cookie, incrementing the value of the original count by 1
        // Set the new cookie for the page
         ApexPages.currentPage().setCookies(new Cookie[]{tranId});
        /* checking issueid should not be null*/
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        Test.startTest();
         CorrespondenceController controller = new CorrespondenceController(new ApexPages.StandardController(testCor));
        Test.stopTest();
        
    }
    
   //Test method to cover validateConstructorNoCorrespondence.
    static testMethod void validateConstructorNoCorrespondence() {
         
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL2', testOpCo);
        insert testPL;
        Brand__c testBrand = TestDataSetup.createBrand('Test Brand','12345',testPL, testOpCo);
        insert testBrand;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
        DocumentType__c testDoc = TestDataSetup.createDoc('Description', 'Outbound', 'Test Category', 'TestCode', 'FileTest', testOpCo, '123456');
        testDoc.isTrade__c = True;
        testDoc.IsActive__c = True;
        insert testDoc;
        Correspondence_Fulfilment__c testCor = TestDataSetup.createCor('Test Letter', bdate, testBrand);
        //insert testCor;
        /* checking issueid should not be null*/
        Cookie tranId = ApexPages.currentPage().getCookies().get('customerRecType');
    
        // If this is the first time the user is accessing the page, 
        // create a new cookie with name 'counter', an initial value of '1', 
        // path 'null', maxAge '-1', and isSecure 'false'. 
        
         tranId = new Cookie('customerRecType','trade',null,-1,false);
        
        // If this isn't the first time the user is accessing the page
        // create a new cookie, incrementing the value of the original count by 1
        // Set the new cookie for the page
         ApexPages.currentPage().setCookies(new Cookie[]{tranId});
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        Test.startTest();
         CorrespondenceController controller = new CorrespondenceController(new ApexPages.StandardController(testCor));
        Test.stopTest();
        
    }
    
    //Test method to cover CancelRedirect method.
    static testMethod void validateCancelRedirect() {
         
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL3', testOpCo);
        insert testPL;
        Brand__c testBrand = TestDataSetup.createBrand('Test Brand','12345',testPL, testOpCo);
        insert testBrand;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
        DocumentType__c testDoc = TestDataSetup.createDoc('Description', 'Outbound', 'Test Category', 'TestCode', 'FileTest', testOpCo, '123456');
        testDoc.isTrade__c = false;
        testDoc.isReimbursement__c = false;
        insert testDoc;
        Correspondence_Fulfilment__c testCor = TestDataSetup.createCor('Test Letter', bdate, testBrand);
        testCor.Contact__c = testCont.id;
        testCor.DocType__c = testDoc.Id;
        testCor.isReimbursement__c = True;
        insert testCor;
        /* checking issueid should not be null*/
        Cookie tranId = ApexPages.currentPage().getCookies().get('customerRecType');
    
        // If this is the first time the user is accessing the page, 
        // create a new cookie with name 'counter', an initial value of '1', 
        // path 'null', maxAge '-1', and isSecure 'false'. 
        
         tranId = new Cookie('customerRecType','Consumer',null,-1,false);
        
        // If this isn't the first time the user is accessing the page
        // create a new cookie, incrementing the value of the original count by 1
        // Set the new cookie for the page
         ApexPages.currentPage().setCookies(new Cookie[]{tranId});
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        Test.startTest();
         CorrespondenceController controller = new CorrespondenceController(new ApexPages.StandardController(testCor));
         Pagereference pgRef = controller.CancelRedirect();
        Test.stopTest();
    }
    
    //Test method to cover Clear method.
    static testMethod void validateClear() {
         
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL4', testOpCo);
        insert testPL;
        Brand__c testBrand = TestDataSetup.createBrand('Test Brand','12345',testPL, testOpCo);
        insert testBrand;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
        DocumentType__c testDoc = TestDataSetup.createDoc('Description', 'Outbound', 'Test Category', 'TestCode', 'FileTest', testOpCo, '123456');
        insert testDoc;
        Correspondence_Fulfilment__c testCor = TestDataSetup.createCor('Test Letter', bdate, testBrand);
        testCor.Contact__c = testCont.id;
        testCor.DocType__c = testDoc.Id;
        insert testCor;
        Cookie customerRecType = ApexPages.currentPage().getCookies().get('customerRecType');
    
        // If this is the first time the user is accessing the page, 
        // create a new cookie with name 'counter', an initial value of '1', 
        // path 'null', maxAge '-1', and isSecure 'false'. 
        
         customerRecType = new Cookie('customerRecType','Trade',null,-1,false);
        
        // If this isn't the first time the user is accessing the page
        // create a new cookie, incrementing the value of the original count by 1
        // Set the new cookie for the page
         ApexPages.currentPage().setCookies(new Cookie[]{customerRecType});
        /* checking issueid should not be null*/
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        PageReference pageRef = Page.CorrespondencePage;
        Test.setCurrentPage(pageRef);
        Test.startTest();
         CorrespondenceController controller = new CorrespondenceController(new ApexPages.StandardController(testCor));
         Pagereference pgRef = controller.Clear();
        Test.stopTest();
        
    }
    
    //Test method to cover SaveRecord method.
    static testMethod void validateSaveRecord() {
         
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Customer_Type__c testCustType = TestDataSetup.createCustType('C', 'CONSUMERS', True, 'test');
        insert testCustType;
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL5', testOpCo);
        insert testPL;
        DocumentType__c testDoc = TestDataSetup.createDoc('Description', 'Outbound', 'Test Category', 'TestCode', 'FileTest', testOpCo, '123456');
        insert testDoc;
        Brand__c testBrand = TestDataSetup.createBrand('Test Brand','12345',testPL, testOpCo);
        DocumentType__c doc = [select id,Op_Company__c
                                    from DocumentType__c 
                                    where id=: testDoc.Id Limit 1];
        testBrand.Op_Company__c = doc.Op_Company__c;
        testBrand.IsCorrespondence__c = True;
        system.debug('Test doc Opr: '+testDoc.Operating_Company__c+' Test Brand Opr: '+testBrand.Op_Company__c);
        insert testBrand;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
        Correspondence_Fulfilment__c testCor = TestDataSetup.createCor('Test Letter', bdate, testBrand);
        testCor.Contact__c = testCont.Id;
        testCor.DocType__c = testDoc.Id;
        testCor.Brand_Corres__c  = testBrand.Id;
        testCor.BCode__c = 'test Brand';
        //insert testCor;
        Cookie customerRecType = ApexPages.currentPage().getCookies().get('customerRecType');
    
        // If this is the first time the user is accessing the page, 
        // create a new cookie with name 'counter', an initial value of '1', 
        // path 'null', maxAge '-1', and isSecure 'false'. 
        
         customerRecType = new Cookie('customerRecType','Consumer',null,-1,false);
        
        // If this isn't the first time the user is accessing the page
        // create a new cookie, incrementing the value of the original count by 1
        // Set the new cookie for the page
         ApexPages.currentPage().setCookies(new Cookie[]{customerRecType});
        /* checking issueid should not be null*/
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        Test.startTest();
         CorrespondenceController controller = new CorrespondenceController(new ApexPages.StandardController(testCor));
         controller.SaveRecord();
        Test.stopTest();
    } 
    
    
    //Test method to cover SaveRecord method for trade.
    static testMethod void validateSaveRecordTrade() {
         
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Customer_Type__c testCustType = TestDataSetup.createCustType('C', 'CONSUMERS', True, 'test');
        insert testCustType;
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL5', testOpCo);
        insert testPL;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
        DocumentType__c testDoc = TestDataSetup.createDoc('Description', 'Outbound', 'Test Category', 'TestCode', 'FileTest', testOpCo, '123456');
        insert testDoc;
        Brand__c testBrand = TestDataSetup.createBrand('Test Brand','12345',testPL, testOpCo);
        DocumentType__c doc = [select id,Op_Company__c
                                    from DocumentType__c 
                                    where id=: testDoc.Id Limit 1];
        testBrand.Op_Company__c = doc.Op_Company__c;
        testBrand.IsCorrespondence__c = True;
        insert testBrand;
        Correspondence_Fulfilment__c testCor = TestDataSetup.createCor('Test Letter', bdate, testBrand);
        testCor.Contact__c = testCont.Id;
        testCor.DocType__c = testDoc.Id;
        testCor.Brand_Corres__c  = testBrand.Id;
        testCor.BCode__c = 'test Brand';
        insert testCor;
        Cookie customerRecType = ApexPages.currentPage().getCookies().get('customerRecType');
    
        // If this is the first time the user is accessing the page, 
        // create a new cookie with name 'counter', an initial value of '1', 
        // path 'null', maxAge '-1', and isSecure 'false'. 
        
         customerRecType = new Cookie('customerRecType','Trade',null,-1,false);
        
        // If this isn't the first time the user is accessing the page
        // create a new cookie, incrementing the value of the original count by 1
        // Set the new cookie for the page
         ApexPages.currentPage().setCookies(new Cookie[]{customerRecType});
        /* checking issueid should not be null*/
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        Test.startTest();
         CorrespondenceController controller = new CorrespondenceController(new ApexPages.StandardController(testCor));
         controller.SaveRecord();
        Test.stopTest();
    }
    
    
    //Test method to cover code coverage for SaveRecord.
    static testMethod void validateSaveRecordDocumentShowMaster() {
         
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Customer_Type__c testCustType = TestDataSetup.createCustType('C', 'CONSUMERS', True, 'test');
        insert testCustType;
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL6', testOpCO);
        insert testPL;
        Brand__c testBrand = TestDataSetup.createBrand('Test Brand','12345',testPL, testOpCo);
        insert testBrand;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
        DocumentType__c testDoc = TestDataSetup.createDoc('Description', 'Outbound', 'Test Category', 'TestCode', 'FileTest', testOpCo, '123456');
        testDoc.showMasterField__c = True;
        insert testDoc;
        Correspondence_Fulfilment__c testCor = TestDataSetup.createCor('Test Letter', bdate, testBrand);
        testCor.Contact__c = testCont.Id;
        testCor.DocType__c = testDoc.Id;
        insert testCor;
        Cookie customerRecType = ApexPages.currentPage().getCookies().get('customerRecType');
    
        // If this is the first time the user is accessing the page, 
        // create a new cookie with name 'counter', an initial value of '1', 
        // path 'null', maxAge '-1', and isSecure 'false'. 
        
         customerRecType = new Cookie('customerRecType','Consumer',null,-1,false);
        
        // If this isn't the first time the user is accessing the page
        // create a new cookie, incrementing the value of the original count by 1
        // Set the new cookie for the page
         ApexPages.currentPage().setCookies(new Cookie[]{customerRecType});
        /* checking issueid should not be null*/
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        Test.startTest();
         CorrespondenceController controller = new CorrespondenceController(new ApexPages.StandardController(testCor));
         controller.SaveRecord();
        Test.stopTest();
    }
    
    //Test method to cover code coverage for brandList method.
    static testMethod void validateBrandList() {
         
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Customer_Type__c testCustType = TestDataSetup.createCustType('C', 'CONSUMERS', True, 'test');
        insert testCustType;
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        Product_Line__c testPL = TestDataSetup.createPL('Test Product Line', 'Test PL7', testOpCo);
        insert testPL;
        Brand__c testBrand = TestDataSetup.createBrand('Test Brand','12345',testPL, testOpCo);
        insert testBrand;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        //insert testCase;
        DocumentType__c testDoc = TestDataSetup.createDoc('Description', 'Outbound', 'Test Category', 'TestCode', 'FileTest', testOpCo, '123456');
        testDoc.showMasterField__c = True;
        insert testDoc;
        Correspondence_Fulfilment__c testCor = TestDataSetup.createCor('Test Letter', bdate, testBrand);
        testCor.Contact__c = testCont.Id;
        testCor.DocType__c = testDoc.Id;
        insert testCor;
        Cookie customerRecType = ApexPages.currentPage().getCookies().get('customerRecType');
    
        // If this is the first time the user is accessing the page, 
        // create a new cookie with name 'counter', an initial value of '1', 
        // path 'null', maxAge '-1', and isSecure 'false'. 
        
         customerRecType = new Cookie('customerRecType','trade',null,-1,false);
        
        // If this isn't the first time the user is accessing the page
        // create a new cookie, incrementing the value of the original count by 1
        // Set the new cookie for the page
         ApexPages.currentPage().setCookies(new Cookie[]{customerRecType});
        /* checking issueid should not be null*/
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
        Test.startTest();
         CorrespondenceController controller = new CorrespondenceController(new ApexPages.StandardController(testCor));
         controller.brandList();
        Test.stopTest();
    }
}