force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Hierarchy__c/Brand_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Brand Hierarchy</label>
    <nameField>
        <displayFormat>BH{0000}</displayFormat>
        <label>Brand Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cause__c/Cause__c.object-meta.xml
<CustomObject>
    <label>Cause</label>
    <nameField>
        <displayFormat>CAU{0000}</displayFormat>
        <label>Cause Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Causes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL{0000}</displayFormat>
        <label>Classification Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentType__c/DocumentType__c.object-meta.xml
<CustomObject>
    <label>Document Type</label>
    <nameField>
        <displayFormat>DT-{0000000}</displayFormat>
        <label>Document Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentType__c/fields/isReimbursement__c.field-meta.xml
<CustomField>
    <fullName>isReimbursement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isReimbursement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentType__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <formula>Text(Op_Company__r.OperatingCompany__c)</formula>
    <label>Operating Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <displayFormat>GR{0000}</displayFormat>
        <label>Group Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Hierarchy__c/Issue_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Issue Hierarchy</label>
    <nameField>
        <displayFormat>IH{0000}</displayFormat>
        <label>Issue Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cause</label>
    <referenceTo>Cause__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issue Type</label>
    <referenceTo>Issue_Type__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reason</label>
    <referenceTo>Reason__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Type__c/Issue_Type__c.object-meta.xml
<CustomObject>
    <label>Issue Type</label>
    <nameField>
        <displayFormat>IT{0000}</displayFormat>
        <label>Issue Type  Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IssueTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reason__c/Reason__c.object-meta.xml
<CustomObject>
    <label>Reason</label>
    <nameField>
        <displayFormat>REA{0000}</displayFormat>
        <label>Reason Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement__c/Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Reimbursement</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Reimbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement__c/fields/Cheque_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Amount__c</fullName>
    <label>Check Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service_Code_Mapping__c/Service_Code_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Service Request vs Service Group Code</description>
    <label>Service Code Mapping</label>
</CustomObject>

force-app/main/default/objects/TFN__c/TFN__c.object-meta.xml
<CustomObject>
    <label>TFN</label>
    <nameField>
        <displayFormat>TFN-{0000}</displayFormat>
        <label>TFN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Toll Free Number</relationshipLabel>
    <relationshipName>Toll_Free_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/Transaction_Management__c.object-meta.xml
<CustomObject>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Management__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/TFN__c.field-meta.xml
<CustomField>
    <fullName>TFN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DNIS</label>
    <referenceTo>TFN__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReimbursementEditControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
/*
test class of Reimbursement Edit Controller
07/18/2016 Infogain – Created.
*/

@isTest 
private class ReimbursementEditControllerTest {

    // Testing constructor of ReimbursementEditControllerTestClass controller
    static testMethod void validateValidationBeforeReimbursement() { 
                  
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc ;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
       insert testCont;
       Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
       Reimbursement__c tempReimb = new Reimbursement__c();
       tempReimb = TestDataSetup.createReimbursement(testCase, 4852.0);
       insert tempReimb;
        Cookie tranId = ApexPages.currentPage().getCookies().get('tranId');
    
        // If this is the first time the user is accessing the page, 
        // create a new cookie with name 'counter', an initial value of '1', 
        // path 'null', maxAge '-1', and isSecure 'false'. 
        
            tranId = new Cookie('tranId',testTM.id,null,-1,false);
        
        // If this isn't the first time the user is accessing the page
        // create a new cookie, incrementing the value of the original count by 1
        // Set the new cookie for the page
        ApexPages.currentPage().setCookies(new Cookie[]{tranId});
       ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
       Test.startTest();
       ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
       controller.validationBeforeReimbursement();
       Test.stopTest();
       system.assertEquals(null,controller.reimId);

    }
   // Testing validationBeforeReimbursement method of ReimbursementEditControllerTestClass controller
   static testMethod void validateReimbursementEditController2() {
      
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc ;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
       insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
       Reimbursement__c tempReimb = new Reimbursement__c();
       tempReimb = TestDataSetup.createReimbursement(testCase, 4852.0);
       insert tempReimb;     
       ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
       ApexPages.currentPage().getParameters().put('id',tempReimb.Id); 
       Test.startTest();
       ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
       controller.validationBeforeReimbursement();
       Test.stopTest();
       system.assertEquals(null,controller.reimId);

    }
        // Testing submit method of if condition ReimbursementEditControllerTestClass controller
    static testMethod void validateSubmitMethodAgeVerified() {
        
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc ;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
       insert testCont;
       Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
       Reimbursement__c tempReimb = new Reimbursement__c();
       tempReimb = TestDataSetup.createReimbursement(testCase, 4852.0);
       insert tempReimb;
       ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
       Test.startTest();
       ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
       controller.submit();
       Test.stopTest();
       System.AssertEquals(null,controller.reimId);
    }
    
    
    //Testing submit method of else condition ReimbursementEditControllerTestClass controller
    static testMethod void validateSubmitMethodReimb() {
    
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc ;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
       insert testCont;
       Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        
        
        Reason__c testreason= TestDataSetup.createReason('test desc');
        insert testreason;
        Cause__c testCause= TestDataSetup.createCause('Test Desc');
        insert testCause;
        Group__c testGroup= TestDataSetup.createGroup('Test Desc');
        insert testGroup;
        Issue_Type__c testIT= TestDataSetup.createIT('Test Desc');
        insert testIT;
        Product_Line__c testPL= TestDataSetup.createPL('PL Name','PL Code', testOpCo);
        insert testPL;
        Classification__c testClassify = TestDataSetup.createClassify('Test Desc');
        insert testClassify;
        
        Issue_Hierarchy__c testIH= TestDataSetup.createIH(testClassify, testPL, testIT, testGroup, testCause,testreason, true);
        insert testIH;
        
        Brand__c testBrand= TestDataSetup.createBrand('Test Desc', 'Test Code', testPL, testOpCo);
        insert testBrand;
        
        Brand_Hierarchy__c testBH = TestDataSetup.createBH('Full Flavor', '100s', 'Soft Pack', 'Menthol', 'Filtered', 'Banded Paper Ny', 'Ready', '12345', testBrand, testPL, '12345');
        insert testBH;
        
        Case testCase = TestDataSetup.createTestIssue(testAcc, 1200, testCont.Id, testTM.Id, testOpCo.id,testBH,testIH,testPL);
        insert testCase;
       Reimbursement__c tempReimb = new Reimbursement__c();
       tempReimb = TestDataSetup.createReimbursement(testCase, -1);
       
       ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
       Test.startTest();
       ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
        
        controller.submit();
       Test.stopTest();
       System.AssertEquals(null,controller.reimId);
    }
    

        // Testing submit method of else condition ReimbursementEditControllerTestClass controller
    static testMethod void validateSubmitMethodAgeNotVerified() {
        
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc ;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
       insert testCont;
       Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
       Reimbursement__c tempReimb = new Reimbursement__c();
       tempReimb = TestDataSetup.createReimbursement(testCase, 4852);
       insert tempReimb;
       ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
       Test.startTest();
       ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
       controller.submit();
       Test.stopTest();
       System.AssertEquals(null,controller.reimId);
    }
        // Testing submit method of validation condition ReimbursementEditControllerTestClass controller
   static testMethod void validateSubmitMethodCheckAmount() {
   
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc ;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
       insert testCont;
       Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
       Reimbursement__c tempReimb = new Reimbursement__c();
       tempReimb = TestDataSetup.createReimbursement(testCase, 4852);
       insert tempReimb;
       ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
       Id id=ApexPages.currentPage().getParameters().put('id',tempReimb.Id);
       Test.startTest();
       ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
       controller.submit();
       Test.stopTest();
       System.AssertEquals(null,Id);
    }
    
     static testMethod void validateCheckAmount() {
     
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc ;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,false,'20001',bdate,'Test Street', true, true);
       insert testCont;
       Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        Service_Code_Mapping__c s = TestDataSetup.createSerCode('CRC', 'CREATE_REIMB');
        insert s;
         Service_Code_Mapping__c s1 = TestDataSetup.createSerCode('Correspondence', 'CORSP_OUTBOUND');
        insert s1;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        DocumentType__c d = TestDataSetup.createDoc('test', 'Outbound', 'test', 'test', 'test', testOpCo, 'test');
        d.isActive__c = true;
        d.isReimbursement__c = true;
        insert d;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
       Reimbursement__c tempReimb = new Reimbursement__c();
        Cookie cookie = new Cookie('tranid', testTM.id, null, -1, false);
       ApexPages.currentPage().setCookies(new Cookie[]{cookie});
       ApexPages.currentPage().getParameters().put('issueId',testCase.Id); 
       Test.startTest();
       ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
       controller.reimbursement.Cheque_Amount__c = 2;   
       controller.submit();
       testCont.AVF_GIID_Received__c = true;
       update testCont;  
       Test.stopTest();
    }   
         // Testing cancel method of if condition ReimbursementEditControllerTestClass controller
    static testMethod void validateCancelMethod() {
    
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
       insert testCont;
       Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
       Reimbursement__c tempReimb = new Reimbursement__c();
       tempReimb = TestDataSetup.createReimbursement(testCase, 4852);
       insert tempReimb;
       ApexPages.currentPage().getParameters().put('Id',tempReimb.Id); 
       Test.startTest();
       ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
       controller.cancel();
       Test.stopTest();
       System.AssertEquals(tempReimb.Id,controller.reimId);
      
    }
         // Testing cancel method of else condition ReimbursementEditControllerTestClass controller
   static testMethod void validateCancelMethodelse() {
       
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
       insert testCont;
       Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
       Reimbursement__c tempReimb = new Reimbursement__c();
       tempReimb = TestDataSetup.createReimbursement(testCase, 4852);
       insert tempReimb;
       Test.startTest();
       ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
       PageReference pageref = controller.cancel();
       controller.cancel();
       Test.stopTest();
       System.AssertEquals(null,controller.reimId);
    }
          // Testing cancel method of elseif condition ReimbursementEditControllerTestClass controller
    static testMethod void validateCancelMethodelseElseif() {
       
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
       insert testCont;
       Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
       Reimbursement__c tempReimb = new Reimbursement__c();
       tempReimb = TestDataSetup.createReimbursement(testCase, 4852);
       insert tempReimb;
       ApexPages.currentPage().getParameters().put('issueId',testCase.Id);
       Test.startTest();
       ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
       controller.cancel();
       Test.stopTest();
       System.AssertEquals(null,controller.reimId);
    }
    static testMethod void validateCancelRedirect() {
        
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
       insert testCont;
       Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
       Reimbursement__c tempReimb = new Reimbursement__c();
       tempReimb = TestDataSetup.createReimbursement(testCase, 4852);
       insert tempReimb;
       ApexPages.currentPage().getParameters().put('issueId',testCase.Id);
       Test.startTest();
       ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
       controller.CancelRedirect();
       Test.stopTest();
       System.AssertEquals(null,controller.reimId);
    }
    
    static testMethod void assignValue() {
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        insert testCase;
        Reimbursement__c tempReimb = new Reimbursement__c();
        tempReimb = TestDataSetup.createReimbursement(testCase, 4852);
        insert tempReimb;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id);
        Test.startTest();
        ReimbursementEditController controller = new ReimbursementEditController(new ApexPages.StandardController(tempReimb));
        controller.assignValue();
        Test.stopTest();
        System.AssertEquals(true,controller.showReimbAddtl);
    }
}