force-app/main/default/objects/Attachment_Detail__c/Attachment_Detail__c.object-meta.xml
<CustomObject>
    <label>Attachment Detail</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>IssueAttachmentId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Hierarchy__c/Brand_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Brand Hierarchy</label>
    <nameField>
        <displayFormat>BH{0000}</displayFormat>
        <label>Brand Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cause__c/Cause__c.object-meta.xml
<CustomObject>
    <label>Cause</label>
    <nameField>
        <displayFormat>CAU{0000}</displayFormat>
        <label>Cause Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Causes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL{0000}</displayFormat>
        <label>Classification Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <displayFormat>GR{0000}</displayFormat>
        <label>Group Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Hierarchy__c/Issue_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Issue Hierarchy</label>
    <nameField>
        <displayFormat>IH{0000}</displayFormat>
        <label>Issue Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cause</label>
    <referenceTo>Cause__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issue Type</label>
    <referenceTo>Issue_Type__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reason</label>
    <referenceTo>Reason__c</referenceTo>
    <relationshipLabel>Issue Hierarchies</relationshipLabel>
    <relationshipName>Issue_Hierarchies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Type__c/Issue_Type__c.object-meta.xml
<CustomObject>
    <label>Issue Type</label>
    <nameField>
        <displayFormat>IT{0000}</displayFormat>
        <label>Issue Type  Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IssueTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reason__c/Reason__c.object-meta.xml
<CustomObject>
    <label>Reason</label>
    <nameField>
        <displayFormat>REA{0000}</displayFormat>
        <label>Reason Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/TFN__c.object-meta.xml
<CustomObject>
    <label>TFN</label>
    <nameField>
        <displayFormat>TFN-{0000}</displayFormat>
        <label>TFN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Toll Free Number</relationshipLabel>
    <relationshipName>Toll_Free_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/Transaction_Management__c.object-meta.xml
<CustomObject>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Management__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/TFN__c.field-meta.xml
<CustomField>
    <fullName>TFN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DNIS</label>
    <referenceTo>TFN__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AttachmentUploadTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers. 
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
/*
  Test Class for AttachmentUpload Controller
  09/13/2016 Infogain – Created.
   */

@isTest
public class AttachmentUploadTest
{
    // validate updateAttachment method 
    public static testmethod void updateAttachmentTest(){
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Reason__c testreason= TestDataSetup.createReason('test desc');
        insert testreason;
        Cause__c testCause= TestDataSetup.createCause('Test Desc');
        insert testCause;
        Group__c testGroup= TestDataSetup.createGroup('Test Desc');
        insert testGroup;
        Issue_Type__c testIT= TestDataSetup.createIT('Test Desc');
        insert testIT;
        Product_Line__c testPL= TestDataSetup.createPL('PL Name','PL Code', testOpCo);
        insert testPL;
        Classification__c testClassify = TestDataSetup.createClassify('Test Desc');
        insert testClassify;
        
        Issue_Hierarchy__c testIH= TestDataSetup.createIH(testClassify, testPL, testIT, testGroup, testCause,testreason, true);
        insert testIH;
        
        Brand__c testBrand= TestDataSetup.createBrand('Test Desc', 'Test Code', testPL, testOpCo);
        insert testBrand;
        
        Brand_Hierarchy__c testBH = TestDataSetup.createBH('Full Flavor', '100s', 'Soft Pack', 'Menthol', 'Filtered', 'Banded Paper Ny', 'Ready', '12345', testBrand, testPL, '12345');
        insert testBH;
        
        Case testCase = TestDataSetup.createTestIssue(testAcc, 1200, testCont.Id, testTM.Id, testOpCo.id,testBH,testIH,testPL);
        insert testCase;
        
        Blob blobValue = EncodingUtil.convertFromHex('4A4B4C');
        Attachment  attachment= TestDataSetup.createAttachment ('Test description', 'test name', testCase.id, blobValue);
        insert attachment;
        Attachment_Detail__c testAttDet = TestDataSetup.createAttachmentDet('Test Describe', 'Test File', testCase, attachment.id);
        testAttDet.IsActive__c = True;
        insert testAttDet;
        ApexPages.currentPage().getParameters().put('id',attachment.Id);
        //ApexPages.currentPage().getParameters().put('Comment: Max. 500 character are allowed.',attachment.Id);
        Test.startTest();
        AttachmentUpload controller=new AttachmentUpload (new ApexPages.StandardController(attachment));
        controller.updateAttachment();
        Test.stopTest();
        //Assertions
        system.assertEquals(attachment.Name,'test name');
    }
    
    // validate cancelButton method
     public static testmethod void cancelButtonTest(){
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id, testOpCo.id);
        insert testCase;
        Blob blobValue = EncodingUtil.convertFromHex('4A4B4C');
        Attachment  attachment= TestDataSetup.createAttachment ('Test description', 'test name', testCase.id, blobValue);
        insert attachment;
        ApexPages.currentPage().getParameters().put('Id',attachment.Id);
        Test.startTest();
        AttachmentUpload controller=new AttachmentUpload (new ApexPages.StandardController(attachment));
        controller.cancelButton();
        Test.stopTest();
        //Assertions
        system.assertEquals(attachment.Name,'test name');
    }
    // validate upload method
    public static testmethod void uploadTest(){  
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Reason__c testreason= TestDataSetup.createReason('test desc');
        insert testreason;
        Cause__c testCause= TestDataSetup.createCause('Test Desc');
        insert testCause;
        Group__c testGroup= TestDataSetup.createGroup('Test Desc');
        insert testGroup;
        Issue_Type__c testIT= TestDataSetup.createIT('Test Desc');
        insert testIT;
        Product_Line__c testPL= TestDataSetup.createPL('PL Name','PL Code', testOpCo);
        insert testPL;
        Classification__c testClassify = TestDataSetup.createClassify('Test Desc');
        insert testClassify;
        
        Issue_Hierarchy__c testIH= TestDataSetup.createIH(testClassify, testPL, testIT, testGroup, testCause,testreason, true);
        insert testIH;
        
        Brand__c testBrand= TestDataSetup.createBrand('Test Desc', 'Test Code', testPL, testOpCo);
        insert testBrand;
        
        Brand_Hierarchy__c testBH = TestDataSetup.createBH('Full Flavor', '100s', 'Soft Pack', 'Menthol', 'Filtered', 'Banded Paper Ny', 'Ready', '12345', testBrand, testPL, '12345');
        insert testBH;
        
        Case testCase = TestDataSetup.createTestIssue(testAcc, 1200, testCont.Id, testTM.Id, testOpCo.id,testBH,testIH,testPL);
        insert testCase;
        Blob blobValue = EncodingUtil.convertFromHex('4A4B4C');
        Attachment  attachment= TestDataSetup.createAttachment ('Test description', 'test name', testCase.id, blobValue);
        //insert attachment;
        ApexPages.currentPage().getParameters().put('issueId',testCase.Id);
        //List<Attachment> attachments=[select id, name from Attachment where parent.id=:testCase.id];
        //System.assertEquals(1, attachments.size());
        Test.startTest();
        AttachmentUpload controller=new AttachmentUpload (new ApexPages.StandardController(attachment));
        controller.upload();
        //RITM0734680 - Limit Upload Size to 5MB 
        Attachment  attachment2= TestDataSetup.createAttachment ('Test description', 'Test Size', testCase.id, blobValue);
        AttachmentUpload controller2=new AttachmentUpload (new ApexPages.StandardController(attachment2));
        controller2.upload();
        //JD - 10/22/2020 : Increasing test coverage
        Attachment  attachment3= new Attachment();
        AttachmentUpload controller3=new AttachmentUpload (new ApexPages.StandardController(attachment3));
        controller3.upload();
        Attachment  attachment4= TestDataSetup.createAttachment (null, 'Test Size', testCase.id, blobValue);
        AttachmentUpload controller4=new AttachmentUpload (new ApexPages.StandardController(attachment4));
        controller4.upload();
        Test.stopTest();
        //Assertions 
        
    }
}