force-app/main/default/objects/Correspondence_Fulfilment__c/Correspondence_Fulfilment__c.object-meta.xml
<CustomObject>
    <label>Correspondence &amp; Fulfilment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Correspondence &amp; Fulfilment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence &amp; Fulfilments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence_Fulfilment__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Correspondence_Fulfilment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence/Fulfilments</relationshipLabel>
    <relationshipName>Correspondence_Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence_Fulfilment__c/fields/Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reimbursement</label>
    <referenceTo>Reimbursement__c</referenceTo>
    <relationshipLabel>Correspondence &amp; Fulfilments</relationshipLabel>
    <relationshipName>Correspondence_Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Reimbursement</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Reimbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement__c/fields/Correspondence_Fulfilment__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Fulfilment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fulfilment</label>
    <referenceTo>Correspondence_Fulfilment__c</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <label>Issue Name</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Transaction_Management_History__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Management_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Management History</label>
    <referenceTo>Transaction_Management_History__c</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Code_Mapping__c/Service_Code_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Service Request vs Service Group Code</description>
    <label>Service Code Mapping</label>
</CustomObject>

force-app/main/default/objects/Service_Code_Mapping__c/fields/Service_Group_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Group_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Group Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/Survey_Issue__c.object-meta.xml
<CustomObject>
    <label>Survey Issue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Survey Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Issue__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Survey Issues</relationshipLabel>
    <relationshipName>Survey_Issues</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Issues</relationshipLabel>
    <relationshipName>Survey_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/Transaction_Management__c.object-meta.xml
<CustomObject>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Management__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management_History__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transaction Management Histories</relationshipLabel>
    <relationshipName>Transaction_Management_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management_History__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name of the Customer associated with the parent Transaction.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First Name of the Customer associated with the parent Transaction.</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Management_History__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Transaction Management Histories</relationshipLabel>
    <relationshipName>Transaction_Management_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management_History__c/fields/Issue_Reviewed_By__c.field-meta.xml
<CustomField>
    <fullName>Issue_Reviewed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue Reviewed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transaction_Management_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management_History__c/fields/Issue_Reviewed_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Reviewed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Issue Reviewed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction_Management_History__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name of the Customer associated with the parent Transaction.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Last Name of the Customer associated with the parent Transaction.</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Management_History__c/fields/Service_Group_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Group_Code__c</fullName>
    <label>Service Group Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>CRCAGEVERIFY</fullName>
            </value>
            <value>
                <fullName>CUSTOMERS</fullName>
            </value>
            <value>
                <fullName>ISSUES</fullName>
            </value>
            <value>
                <fullName>SGProgramAllocation</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>TAVDecline</fullName>
            </value>
            <value>
                <fullName>UpdateSurvey</fullName>
            </value>
            <value>
                <fullName>PNASRequest</fullName>
            </value>
            <value>
                <fullName>CRCAGEVERIFYRQ</fullName>
            </value>
            <value>
                <fullName>APPROVALS</fullName>
            </value>
            <value>
                <fullName>SRPROGRAMALLOCATION</fullName>
            </value>
            <value>
                <fullName>CUSTOMER</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>IVR REIMBURSEMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Management_History__c/fields/Service_Request_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Request_Code__c</fullName>
    <description>Denotes the History type.</description>
    <inlineHelpText>Denotes the History type.</inlineHelpText>
    <label>Service Request Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AGE_VERIFY</fullName>
            </value>
            <value>
                <fullName>CCNLOOKUP</fullName>
            </value>
            <value>
                <fullName>CORSP_OUTBOUND</fullName>
            </value>
            <value>
                <fullName>CREATE_REIMB</fullName>
            </value>
            <value>
                <fullName>CREATE_SURVEY</fullName>
            </value>
            <value>
                <fullName>CREATECUST</fullName>
            </value>
            <value>
                <fullName>CREATEISSUE</fullName>
            </value>
            <value>
                <fullName>UPDATE_REIMB</fullName>
            </value>
            <value>
                <fullName>UPDATE_SURVEY</fullName>
            </value>
            <value>
                <fullName>UPDATECUST</fullName>
            </value>
            <value>
                <fullName>UPDATEISSUE</fullName>
            </value>
            <value>
                <fullName>ENDCALL</fullName>
            </value>
            <value>
                <fullName>FULL_SEARCH</fullName>
            </value>
            <value>
                <fullName>AGE_VERIFICATION_REQUEST</fullName>
            </value>
            <value>
                <fullName>ISSUE_APPROVED</fullName>
            </value>
            <value>
                <fullName>SRPROGRAMALLOCATION</fullName>
            </value>
            <value>
                <fullName>CHAT_START</fullName>
            </value>
            <value>
                <fullName>EMAIL_ADDRESS_UPDATE</fullName>
            </value>
            <value>
                <fullName>EMAIL_CONFIRMED_UPDATE</fullName>
            </value>
            <value>
                <fullName>REIMBURSEMENT FOUND</fullName>
            </value>
            <value>
                <fullName>NO REIMBURSEMENT FOUND FOR CONSUMER</fullName>
            </value>
            <value>
                <fullName>MULTIPLE CONSUMERS FOUND</fullName>
            </value>
            <value>
                <fullName>NO CONSUMER FOUND</fullName>
            </value>
            <value>
                <fullName>CONSUMER IS NOT AGE VERIFIED</fullName>
            </value>
            <value>
                <fullName>ONLINE_VF_SENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Management_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Survey associated.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Status of the Survey associated.</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TransactionMgmtHelper.cls
/*
Created By : Infogain
Created Date : 19 Aug 2016
*/

public class TransactionMgmtHelper {
    
    //Method to insert history records based on the source of history.
    public void createTransactionMgmtHistoryRecord(String source, String sObjectId){
        string tranid;
        Transaction_Management_History__c history;
        Transaction_Management__c transactionObj;
        Reimbursement__c reimb;
        Correspondence_Fulfilment__c corrObj;
        Survey_Issue__c si;
        Case currIssue;
        string sobjectName;
        System.debug('test 11'+source);
        if(source == 'CCNLOOKUP'){
            tranid = sObjectId;        
        }
        else if(source == 'ISSUE_APPROVED'){
            tranid = '';
        }
        //Start: For IVR Reimbursement API Entry
        else if(source == 'REIMBURSEMENT FOUND' ||
                source == 'NO REIMBURSEMENT FOUND FOR CONSUMER' ||
               	source == 'MULTIPLE CONSUMERS FOUND' ||
               	source == 'NO CONSUMER FOUND' ||
                source == 'CONSUMER IS NOT AGE VERIFIED'){
            transactionObj = [Select Id, Contact__c, Comments__c FROM Transaction_Management__c Where Id=: sObjectId];
        }
        //End: For IVR Reimbursement API Entry
        else{
            Cookie counter = ApexPages.currentPage().getCookies().get('tranid');
            if(counter != null) {
                tranid = counter.getValue();
            } 
        }
        if(tranid != null && tranid != ''){
            System.debug('test tranid '+tranid);
            transactionObj = [Select Id, Contact__c, Comments__c From Transaction_Management__c Where Id=: tranid];
            System.debug('test transactionObj '+transactionObj);
        }
        if(source == 'ISSUE_APPROVED'){
            if(sObjectId != null && sObjectId != ''){
                history = new Transaction_Management_History__c();
                sobjectName = Id.valueOf(sObjectId).getSObjectType().getDescribe().getName();
                history.Service_Request_Code__c = source;
                if(Service_Code_Mapping__c.getValues(source) != null){
                    history.Service_Group_Code__c = Service_Code_Mapping__c.getValues(source).Service_Group_Code__c;    
                }
                if(sobjectName == 'Case'){
                    currIssue = new Case();
                    currIssue = [Select Id, ContactId, Contact.LastName, Contact.FirstName From Case where Id =: sObjectId limit 1];
                    history.Issue__c = currIssue.id;
                    history.Issue_Reviewed_Date__c = system.now();
                    history.Issue_Reviewed_By__c = UserInfo.getUserId();
                                        
                    if(currIssue.ContactId != null){
                        history.Customer__c = currIssue.ContactId;
                        history.First_Name__c = currIssue.Contact.FirstName;
                        history.Last_Name__c = currIssue.Contact.LastName;
                    }
                    
                    if(history != null && source == 'ISSUE_APPROVED'){
                        Database.SaveResult saveHistoryRst = Database.insert(history);
                    }
                }
            }
        }
        if(transactionObj != null && source != 'ISSUE_APPROVED'){
            system.debug('-----transactionObj-----'+transactionObj);
            history = new Transaction_Management_History__c();
            history.Transaction_Management__c = transactionObj.id;
            if(transactionObj.Contact__c != null){
                history.Customer__c = transactionObj.Contact__c;
                Contact conObj = [Select Id, LastName, FirstName From Contact Where Id =: transactionObj.Contact__c limit 1];
                if(conObj != null){
                    history.First_Name__c = conObj.FirstName;
                    history.Last_Name__c = conObj.LastName;
                }
                list<Transaction_Management_History__c> lstTMH = getHistoryWithoutContact(transactionObj.id);
                if(lstTMH != null && lstTMH.size() > 0){
                    list<Transaction_Management_History__c> lstTMHUpdate = new list<Transaction_Management_History__c>();
                    for(Transaction_Management_History__c tmh : lstTMH){
                        tmh.Customer__c = transactionObj.Contact__c;
                        tmh.First_Name__c = conObj.FirstName;
                        tmh.Last_Name__c = conObj.LastName;
                        lstTMHUpdate.add(tmh);
                    }
                    if(lstTMHUpdate != null && lstTMHUpdate.size() > 0){
                        list<Database.SaveResult> lstSvRst = Database.update(lstTMHUpdate);
                    }
                }
            }
            history.Service_Request_Code__c = source;
            if(Service_Code_Mapping__c.getValues(source) != null){
                history.Service_Group_Code__c = Service_Code_Mapping__c.getValues(source).Service_Group_Code__c;    
            }
           if(source == 'ENDCALL'){
               history.Comments__c = transactionObj.Comments__c;
           }
           if(sObjectId != null && sObjectId != ''){
                sobjectName = Id.valueOf(sObjectId).getSObjectType().getDescribe().getName();
                if(sobjectName == 'Contact'){
                    //JAD: RITM0441447 - Production Implementation for SCR 20-06-03 2020 Wirecard Virtual Pay
                    history.Comments__c = transactionObj.Comments__c;
                    // JAD: RITM0441447 -- end
                }
                if(sobjectName == 'Case' && source == 'CREATE_SURVEY'){
                    currIssue = new Case();
                    currIssue = [Select Id, Survey__c,Survey_Cancel_Reason__c From Case where Id =: sObjectId limit 1];
                    if(currIssue != null){
                        history.Issue__c = currIssue.id;
                        history.Status__c = currIssue.Survey__c;
                        history.Survey_Termination_Reason__c = currIssue.Survey_Cancel_Reason__c;
                    }
                }
                if(sobjectName == 'Case' && source != 'CREATE_SURVEY'){
                    system.debug('-----Case----');
                    currIssue = new Case();
                    currIssue = [Select Id, Update_Reason__c,Transaction_Management_History__c From Case where Id =: sObjectId limit 1];
                    history.Issue__c = currIssue.id;
                    history.Update_Reason__c = currIssue.Update_Reason__c;
                }
                if(sobjectName == 'Reimbursement__c'){
                    system.debug('-----Reimbursement----');
                    reimb = new Reimbursement__c();
                    reimb = [Select Id, Cheque_Amount__c, Issue__c,PackageCode__c, Transaction_Management_History__c From Reimbursement__c Where Id =: sObjectId limit 1];
                    history.Amount__c = reimb.Cheque_Amount__c;
                    history.Issue__c = reimb.Issue__c;
                    history.Package_Code__c = reimb.PackageCode__c;
                }
                if(sobjectName == 'Correspondence_Fulfilment__c'){
                    system.debug('-----Correspondence_Fulfilment__c----');
                    corrObj = new Correspondence_Fulfilment__c();
                    corrObj = [Select Id, LetterDesc__c,  Packagecode__c,Transaction_Management_History__c From Correspondence_Fulfilment__c Where Id=: sObjectId];
                    history.Letter_Type__c = corrObj.LetterDesc__c;
                    history.Package_Code__c = corrObj.Packagecode__c;
                }
                system.debug('test sobjectName  '+sobjectName );
                if(sobjectName == 'Survey_Issue__c'){
                    system.debug('-----Survey_Issue----');
                    si = new Survey_Issue__c();
                    si = [Select id, Issue__c, Issue__r.Survey__c, Issue__r.Survey_Cancel_Reason__c
                                          From Survey_Issue__c Where Id =: sObjectId limit 1];
                    system.debug('test sobjectName si '+si);                          
                    if(si != null){
                        history.Issue__c = si.Issue__c;
                        history.Status__c = si.Issue__r.Survey__c;
                        history.Survey_Termination_Reason__c = si.Issue__r.Survey_Cancel_Reason__c;
                    }
                }
                if(sobjectName == 'Transaction_Management__c')
                {
                    history.Comments__c = transactionObj.Comments__c;
                }
            }
            System.debug('history = ' + history);
            if(history != null){
                Database.SaveResult saveHistoryRst = Database.insert(history);
                system.debug('-----saveHistoryRst----'+saveHistoryRst);
                if(saveHistoryRst.isSuccess()){
                    if(sobjectName != null && sobjectName != ''){
                        if(sobjectName == 'Reimbursement__c' && reimb != null && reimb.id != null){
                            reimb.Transaction_Management_History__c = saveHistoryRst.getId();
                            update reimb;
                        }
                        if(sobjectName == 'Case' && source != 'CREATE_SURVEY' && currIssue != null && currIssue.id != null){
                            currIssue.Transaction_Management_History__c = saveHistoryRst.getId();
                            update currIssue;
                        }
                        if(sobjectName == 'Correspondence_Fulfilment__c' && corrObj != null && corrObj.id != null){
                            corrObj.Transaction_Management_History__c = saveHistoryRst.getId();
                            update corrObj;
                        }
                    }
                }
            }
        }
    }
    public list<Transaction_Management_History__c> getHistoryWithoutContact(string tranid){
        system.debug('inside gethistory');
        list<Transaction_Management_History__c> lstTMH = [Select Id, Customer__c, Transaction_Management__c From Transaction_Management_History__c Where Transaction_Management__c=: tranid and Customer__c = null];
        system.debug('------lstTMH------'+lstTMH);
        if(lstTMH != null){
            return lstTMH;
        }
        return null;
    }
}