force-app/main/default/objects/Reimbursement__c/Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Reimbursement</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Reimbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement__c/fields/Altria_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Altria_File_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Altria File Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Apt_Lot__c.field-meta.xml
<CustomField>
    <fullName>Apt_Lot__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Apt / Lot</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Card Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Cheque_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Amount__c</fullName>
    <label>Check Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City / Locality</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Consumer__c.field-meta.xml
<CustomField>
    <fullName>Consumer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consumer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <description>Feed Outbound</description>
    <formula>Consumer__r.CustomerID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CustomerID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Ecount_ID__c.field-meta.xml
<CustomField>
    <fullName>Ecount_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ecount ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>File Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <label>Issue Name</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/IssueID__c.field-meta.xml
<CustomField>
    <fullName>IssueID__c</fullName>
    <description>Feed Outbound</description>
    <formula>Issue__r.CaseNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Issue ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/OpCo__c.field-meta.xml
<CustomField>
    <fullName>OpCo__c</fullName>
    <formula>Issue__r.Operating_Company__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OpCo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>State / Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street Address / Address1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Transfer_to_Altria_Date__c.field-meta.xml
<CustomField>
    <fullName>Transfer_to_Altria_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Transfer to Altria Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip Code / Postal Code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReimbursementHistoryController.cls
public class ReimbursementHistoryController {
    
    public List<Reimbursement__c> reimbHist{get;set;}
    public Contact conObj {get;set;}
    
    public ReimbursementHistoryController(ApexPages.StandardController stdController){
        String contactID;
        System.debug('Page: ' + ApexPages.currentPage());
		contactId = ApexPages.currentPage().getParameters().get('contactId');
		
        If(contactId != null){
			for(Contact c: [SELECT Zip_Code__c, Street_Address__c 
                            FROM Contact
                            WHERE Id =: contactId]){
             	conObj = c;               
             }
        }
       
        if(conObj != null){
            reimbHist =[SELECT 
                            IssueID__c,Issue__r.CreatedDate, CreatedDate,
                            Cheque_Amount__c, First_Name__c,
                            Last_Name__c, Street_Address__c, Apt_Lot__c, City__c,
                            State__c, Zip_Code__c, CustomerID__c, OpCo__c,
                            Consumer__r.AVF_GIID_Received__c, Transfer_to_Altria_Date__c,
                            Altria_File_Name__c, File_Name__c, Ship_Date__c,
                        	Ecount_ID__c, Card_Number__c
                        FROM Reimbursement__c
                        WHERE  
                        (Zip_Code__c =: conObj.Zip_Code__c AND Street_Address__c =: conObj.Street_Address__c)
                        OR Consumer__c =: conObj.Id
                        ORDER BY IssueID__c DESC];
          
        } 
    }
}