force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Store Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_Address1__c.field-meta.xml
<CustomField>
    <fullName>Store_Address1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Store Address1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_Address2__c.field-meta.xml
<CustomField>
    <fullName>Store_Address2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Store Address2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_City__c.field-meta.xml
<CustomField>
    <fullName>Store_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Store City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_Comment__c.field-meta.xml
<CustomField>
    <fullName>Store_Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Store Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_Name__c.field-meta.xml
<CustomField>
    <fullName>Store_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Store Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_State__c.field-meta.xml
<CustomField>
    <fullName>Store_State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Store State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_Type__c.field-meta.xml
<CustomField>
    <fullName>Store_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store Type</label>
    <referenceTo>Store_Type__c</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_Zip__c.field-meta.xml
<CustomField>
    <fullName>Store_Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Store Zip</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store_Type__c/Store_Type__c.object-meta.xml
<CustomObject>
    <label>Store Type</label>
    <nameField>
        <displayFormat>ST{00}</displayFormat>
        <label>Store Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StoreDetailController.cls
/*
Functionality to the detail page for Store records
06/29/2016 Infogain – Created.
*/

public class StoreDetailController {
    
    public Store__c store{get;set;} /* Object to get store data */
    public String redirectPath;    /* String to store redirection path */
    public String issueId{get;set;} /* Store the issue id from url */
    public id tranid{get;set;}
    public StoreDetailController(ApexPages.StandardController stdController) {
        store = new Store__c(); 
        this.store = (Store__c)stdController.getRecord();
        init();
    }
    
    public StoreDetailController() {    
        store = new Store__c();        
        init();        
    } 
    
    /* Assign values in store object */
    private void init(){
        Cookie counter = ApexPages.currentPage().getCookies().get('tranid');
        if(counter != null) {
            tranid = counter.getValue();
        }
        
        if(this.store != null && this.store.id != null){
            store = [select id,Store_Type__c,Issue__c, Name,Store_Type__r.Description__c,
                     Store_Address1__c,Store_Address2__c,Store_City__c,Store_State__c,
                     Store_Zip__c,Store_Comment__c,Store_Name__c 
                     from Store__c where Id=:this.store.id];
            issueId=store.Issue__c;
        }  
    }
    
   /* Called on click of Edit button and redirects to Store Edit page after validation check */
    public PageReference editStore()
    {
        validationCheck();
        if(ApexPages.hasMessages()){
            return null;
        }
        redirectPath=  '/apex/StoreEditPage?id='+store.Id;   
        PageReference pageRef = new PageReference(redirectPath);
        return pageRef;
    }

    
    /* Validation check - Add error message on Apex page message incase of validation check failure */
    public void validationCheck(){
        if(ApexPages.currentPage().getParameters().get('Id')==Null)
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Store Id not mentioned in the url'));
    }
    
    /* Called on click of Cancel button and return to previous page */
    public PageReference cancelStore()
    {
        PageReference pageRef;
        if(issueId==null || issueId=='')
            pageRef = new PageReference('/a00/o');
        else
            pageRef = new PageReference('/apex/Issue_Detail?id='+ issueId);
        return pageRef;  
    }
}