force-app/main/default/objects/Survey_Issue__c/Survey_Issue__c.object-meta.xml
<CustomObject>
    <label>Survey Issue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Survey Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Issue__c/fields/AnswerText__c.field-meta.xml
<CustomField>
    <fullName>AnswerText__c</fullName>
    <description>It is only for Issue_Survey_Outbound feed.</description>
    <formula>Answer__r.Answer__c</formula>
    <label>AnswerText</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Survey Issues</relationshipLabel>
    <relationshipName>Survey_Issues</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/fields/QuestionText__c.field-meta.xml
<CustomField>
    <fullName>QuestionText__c</fullName>
    <description>It is only for Issue_Survey_Outbound feed.</description>
    <formula>Question__r.Question__c</formula>
    <label>QuestionText</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Issue__c/fields/Survey_Name__c.field-meta.xml
<CustomField>
    <fullName>Survey_Name__c</fullName>
    <description>It is only for Issue_Survey_Outbound feed.</description>
    <formula>Survey__r.Survey_Name__c</formula>
    <label>Survey Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IssueSurveyListController.cls
public class IssueSurveyListController{
    
    public Case issueObj {get; set;}
    public Integer PageSize  {get;set;}
    public boolean ReviewPage {get;set;}     
    public IssueSurveyListController(){
        pageInit();          
    }
    
    public IssueSurveyListController(ApexPages.StandardController controller) {
        pageInit();
    }
    
    private void pageInit(){
        issueObj = [select id,caseNumber,CaseNumber__c from case where id=:ApexPages.currentPage().getParameters().get('Id')];
        ReviewPage = false;
        if(ApexPages.currentPage().getParameters().get('pageSize') != null){
            PageSize = Integer.valueOf(ApexPages.currentPage().getParameters().get('pageSize'));
        }else{
            PageSize = 20;
        }
        if(ApexPages.currentPage().getParameters().get('fromPage') != null && ApexPages.currentPage().getParameters().get('fromPage') == 'review'){
            ReviewPage = true;
        }
    }
    
     public ApexPages.StandardSetController setQun {
         
        get {
            if(setQun == null) {
                setQun = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [SELECT id, Comment__c, Survey_Name__c, QuestionText__c ,AnswerText__c 
                        FROM Survey_Issue__c 
                        Where isActive__c = true
                        and Issue__c =:issueObj.id 
                        order by createddate asc] ));
                
                setQun.setPageSize(PageSize);
 
            }
            return setQun;
        }
        set;
    }
        
    public Boolean hasNext {
        get {
            return setQun.getHasNext();
        }
        set;
    }
    public Boolean hasPrevious {
        get {
            return setQun.getHasPrevious();
        }
        set;
    }
    
    public void previous() {
         setQun.previous();
     }
    
    public void next() {
         setQun.next();
     }
    
    
    // Wrapper list  
    public List<Survey_Issue__c> getIssueSurvyeList() {        
          
        List<Survey_Issue__c> surveyList = new List<Survey_Issue__c>();
        surveyList =setQun.getRecords();
        
        return surveyList ;
    } 
       
     public pagereference cancel(){
          return new PageReference('/'+issueObj.id);
     }
    
}