force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>SurveyId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF( EndDate__c &lt; Today(), false, true)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <description>Feed Outbound - Dateformat</description>
    <formula>IF(DATEVALUE(CreatedDate) &gt;=
DATE(YEAR(DATEVALUE(CreatedDate)),3,1)
+
(
14-
CASE(MOD(DATE(YEAR(DATEVALUE(CreatedDate)),3,1)-DATE(1900,1,7),7),
0,7,MOD(DATE ( YEAR (DATEVALUE(CreatedDate)),3,1) - DATE (1900,1,7),7))
)
&amp;&amp;
DATEVALUE(CreatedDate) &lt;
DATE(YEAR(DATEVALUE(CreatedDate)),11,1)
+
(
7-
CASE(MOD(DATE(YEAR(DATEVALUE(CreatedDate)),11,1)-DATE(1900,1,7),7),
0,7,MOD(DATE(YEAR(DATEVALUE(CreatedDate)),11,1)-DATE(1900,1,7),7))
),
MID(TEXT(CreatedDate-4/24),6,2)+&quot;/&quot;
+MID(TEXT(CreatedDate-4/24),9,2)+&quot;/&quot;
+MID(TEXT(CreatedDate-4/24),0,4) + &quot; &quot;
+MID(TEXT(CreatedDate-4/24),11,9)
,
MID( TEXT(CreatedDate-5/24),6,2)+&quot;/&quot;
+MID( TEXT(CreatedDate-5/24),9,2)+&quot;/&quot;
+MID( TEXT(CreatedDate-5/24),0,4)+&quot; &quot;
+MID(TEXT(CreatedDate-5/24),11,9)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/End_Date_Feed__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Feed__c</fullName>
    <description>Date Format - Feed Outbound.</description>
    <formula>IF( ISNULL(EndDate__c) ,&apos;&apos; ,MID( TEXT(EndDate__c) , 6, 2)+&quot;/&quot;+MID( TEXT(EndDate__c) , 9, 2)+&quot;/&quot;+MID( TEXT(EndDate__c) , 0, 4) + &quot; 00:00:00&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date Feed</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/IsDeleted__c.field-meta.xml
<CustomField>
    <fullName>IsDeleted__c</fullName>
    <description>Feed Outbound - Hardcode value 0.</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsDeleted</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/LastModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedDate__c</fullName>
    <description>Feed Outbound - Date format</description>
    <formula>IF ( DATEVALUE(LastModifiedDate) &gt;=
DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1)
+
(
14-
CASE( MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1) - DATE (1900,1,4),4) ,
0,4,MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1) - DATE (1900,1,4),4))
)
&amp;&amp;
DATEVALUE(LastModifiedDate) &lt;
DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1)
+
(
4-
CASE( MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1) - DATE (1900,1,4),4) ,
0,4,MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1) - DATE (1900,1,4),4))
),
MID( TEXT(LastModifiedDate- 4/24) , 6, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 4/24) , 9, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 4/24) , 0, 4) + &quot; &quot;+MID(TEXT(LastModifiedDate- 4/24), 11, 9)
,
MID( TEXT(LastModifiedDate- 5/24) , 6, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 5/24) , 9, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 5/24) , 0, 4) + &quot; &quot;+MID(TEXT(LastModifiedDate- 5/24), 11, 9)
)</formula>
    <label>Last Modified Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/RequiredFeed__c.field-meta.xml
<CustomField>
    <fullName>RequiredFeed__c</fullName>
    <description>feed outbound</description>
    <formula>if(Required__c,&apos;YES&apos;,&apos;NO&apos;)</formula>
    <label>RequiredFeed</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Survey_Name__c.field-meta.xml
<CustomField>
    <fullName>Survey_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Survey Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SurveyTriggerHandler.cls
/************************************************************************ 
Author: Randolf Suplito
Date: 08/22/2022
Description: This handler class is for SurveyTrigger
*************************************************************************/

public class SurveyTriggerHandler {

    public static Boolean isFirstTime = true;
    
    public static void createCallout(List<Survey__c> triggerNewList, Map<Id,Survey__c> triggerNewMap) {
        
        Map<String,String> createdComNameMap = new Map<String,String>();
        Map<String,String> modifiedComNameMap = new Map<String,String>();
        String lastModifiedUser;
        
        jsonRequestDTO jsonPayload = new jsonRequestDTO();
        List<surveyDTO> surveyDTOList = new List<surveyDTO>();
        
        for(Survey__c surveyRec : [SELECT Id, CreatedBy.CommunityNickname, LastModifiedBy.CommunityNickname FROM Survey__c WHERE Id IN :triggerNewMap.keyset()]) {
            createdComNameMap.put(surveyRec.Id, surveyRec.CreatedBy.CommunityNickname);
            modifiedComNameMap.put(surveyRec.Id, surveyRec.LastModifiedBy.CommunityNickname);
            lastModifiedUser = surveyRec.LastModifiedBy.CommunityNickname;
        }
        
        for(Survey__c surveyRec : triggerNewList) {
            surveyDTO sDTO = new surveyDTO();
            sDTO.SurveyID = surveyRec.Name != null ? surveyRec.Name : '';
            sDTO.SurveyName = surveyRec.Survey_Name__c != null ? surveyRec.Survey_Name__c : '';
            sDTO.StartDate = surveyRec.Start_Date__c != null ? String.valueOf(surveyRec.Start_Date__c) : '';
            sDTO.EndDate = surveyRec.End_Date_Feed__c != null ? surveyRec.End_Date_Feed__c : '';
            if(surveyRec.Active__c != null && surveyRec.Active__c) { 
                sDTO.ActiveFlag = 'Y'; 
            } else if(surveyRec.Active__c != null && !surveyRec.Active__c) { 
                sDTO.ActiveFlag = 'N'; 
            } else if(surveyRec.Active__c == null) {
                sDTO.ActiveFlag = '';
            }
            sDTO.Priority = surveyRec.Priority__c != null ? String.valueOf(surveyRec.Priority__c) : '';
            sDTO.Mandatory = surveyRec.RequiredFeed__c != null ? surveyRec.RequiredFeed__c : '';
            sDTO.CreatedBy = createdComNameMap.get(surveyRec.Id);
            sDTO.ModifiedBy = modifiedComNameMap.get(surveyRec.Id);
            sDTO.CreatedDate = surveyRec.CreatedDate__c != null ? surveyRec.CreatedDate__c : '';
            sDTO.ModifiedDate = surveyRec.LastModifiedDate__c != null ? surveyRec.LastModifiedDate__c : '';
            sDTO.IsDeleted = surveyRec.IsDeleted__c != null ? surveyRec.IsDeleted__c : '';
            
            surveyDTOList.add(sDTO);
        }
        
        if(!surveyDTOList.isEmpty()) {
            jsonPayload.userName = lastModifiedUser;
            jsonPayload.SurveyDefinition = surveyDTOList;
            System.debug('jsonPayload: ' + JSON.Serialize(jsonPayload));
        	APIDataCalloutServices.dataFeedCallout(JSON.Serialize(jsonPayload), ConstantClass.SURVEY_CALLOUT_NAME);
        }
    }
    
    public class jsonRequestDTO {
        public String userName {get; set;}
        public List<surveyDTO> SurveyDefinition;
    }
    
    public class surveyDTO {
        public String SurveyID {get; set;}
        public String SurveyName {get; set;}
        public String StartDate {get; set;}
        public String EndDate {get; set;}
        public String ActiveFlag {get; set;}
        public String Priority {get; set;}
        public String Mandatory {get; set;}
        public String CreatedBy {get; set;}
        public String ModifiedBy {get; set;}
        public String CreatedDate {get; set;}
        public String ModifiedDate {get; set;}
        public String IsDeleted {get; set;}
    }
}