force-app/main/default/objects/Survey_Configuration__c/Survey_Configuration__c.object-meta.xml
<CustomObject>
    <label>Survey Configuration</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Survey Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Configuration__c/fields/Answer_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Answer_Sequence__c</fullName>
    <label>Answer Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/AnswerID__c.field-meta.xml
<CustomField>
    <fullName>AnswerID__c</fullName>
    <description>Feed Outbound</description>
    <formula>Answer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AnswerID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/CommentRequiredFeed__c.field-meta.xml
<CustomField>
    <fullName>CommentRequiredFeed__c</fullName>
    <description>Feed Outbound.</description>
    <formula>IF( CommentRequired__c , &apos;REQUIRED&apos;, &apos;OPTIONAL&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CommentRequiredFeed</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <description>Feed Outbound - Date Format.</description>
    <formula>IF(DATEVALUE(CreatedDate) &gt;=
DATE(YEAR(DATEVALUE(CreatedDate)),3,1)
+
(
14-
CASE(MOD(DATE(YEAR(DATEVALUE(CreatedDate)),3,1)-DATE(1900,1,7),7),
0,7,MOD(DATE ( YEAR (DATEVALUE(CreatedDate)),3,1) - DATE (1900,1,7),7))
)
&amp;&amp;
DATEVALUE(CreatedDate) &lt;
DATE(YEAR(DATEVALUE(CreatedDate)),11,1)
+
(
7-
CASE(MOD(DATE(YEAR(DATEVALUE(CreatedDate)),11,1)-DATE(1900,1,7),7),
0,7,MOD(DATE(YEAR(DATEVALUE(CreatedDate)),11,1)-DATE(1900,1,7),7))
),
MID(TEXT(CreatedDate-4/24),6,2)+&quot;/&quot;
+MID(TEXT(CreatedDate-4/24),9,2)+&quot;/&quot;
+MID(TEXT(CreatedDate-4/24),0,4) + &quot; &quot;
+MID(TEXT(CreatedDate-4/24),11,9)
,
MID( TEXT(CreatedDate-5/24),6,2)+&quot;/&quot;
+MID( TEXT(CreatedDate-5/24),9,2)+&quot;/&quot;
+MID( TEXT(CreatedDate-5/24),0,4)+&quot; &quot;
+MID(TEXT(CreatedDate-5/24),11,9)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CreatedDate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/LastModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedDate__c</fullName>
    <description>Feed Outbound</description>
    <formula>IF ( DATEVALUE(LastModifiedDate) &gt;=
DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1)
+
(
14-
CASE( MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1) - DATE (1900,1,4),4) ,
0,4,MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1) - DATE (1900,1,4),4))
)
&amp;&amp;
DATEVALUE(LastModifiedDate) &lt;
DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1)
+
(
4-
CASE( MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1) - DATE (1900,1,4),4) ,
0,4,MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1) - DATE (1900,1,4),4))
),
MID( TEXT(LastModifiedDate- 4/24) , 6, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 4/24) , 9, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 4/24) , 0, 4) + &quot; &quot;+MID(TEXT(LastModifiedDate- 4/24), 11, 9)
,
MID( TEXT(LastModifiedDate- 5/24) , 6, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 5/24) , 9, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 5/24) , 0, 4) + &quot; &quot;+MID(TEXT(LastModifiedDate- 5/24), 11, 9)
)</formula>
    <label>LastModifiedDate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/MultiAnswers__c.field-meta.xml
<CustomField>
    <fullName>MultiAnswers__c</fullName>
    <description>Feed Outbound.</description>
    <formula>IF(QuestionFrom__r.MultiAnswers__c==&apos;1&apos;, &apos;YES&apos;, &apos;NO&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MultiAnswers</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/PMAnswerID__c.field-meta.xml
<CustomField>
    <fullName>PMAnswerID__c</fullName>
    <formula>TExt(Answer__r.PMAnswerID__c)</formula>
    <label>PMAnswerID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/PMQuestionID__c.field-meta.xml
<CustomField>
    <fullName>PMQuestionID__c</fullName>
    <description>Feed Outbound .</description>
    <formula>TEXT(QuestionFrom__r.PMQuestionID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PMQuestionID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/Question_Required__c.field-meta.xml
<CustomField>
    <fullName>Question_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Question Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/Question_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Question_Sequence__c</fullName>
    <label>Question Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/QuestionID__c.field-meta.xml
<CustomField>
    <fullName>QuestionID__c</fullName>
    <description>Feed Outbound</description>
    <formula>QuestionFrom__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QuestionID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/QuestionToID__c.field-meta.xml
<CustomField>
    <fullName>QuestionToID__c</fullName>
    <description>Feed Outbound.</description>
    <formula>QuestionTo__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QuestionToID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Configuration__c/fields/SurveyID__c.field-meta.xml
<CustomField>
    <fullName>SurveyID__c</fullName>
    <description>Feed Outbound - Survey__r.Name</description>
    <formula>Survey__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Survey ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SurveyConfigurationTriggerHandler.cls
/************************************************************************ 
Author: Randolf Suplito
Date: 08/22/2022
Description: This handler class is for SurveyConfigurationTrigger
*************************************************************************/

public class SurveyConfigurationTriggerHandler {

    public static Boolean isFirstTime = true;
    
    public static void createCallout(List<Survey_Configuration__c> triggerNewList, Map<Id,Survey_Configuration__c> triggerNewMap) {
        
        Map<String,String> createdComNameMap = new Map<String,String>();
        Map<String,String> modifiedComNameMap = new Map<String,String>();
        String lastModifiedUser;
        
        jsonRequestDTO jsonPayload = new jsonRequestDTO();
        List<surveyConfigDTO> surveyConfigDTOList = new List<surveyConfigDTO>();
        
        for(Survey_Configuration__c surveyConfigRec : [SELECT Id, CreatedBy.CommunityNickname, LastModifiedBy.CommunityNickname FROM Survey_Configuration__c WHERE Id IN :triggerNewMap.keyset()]) {
            createdComNameMap.put(surveyConfigRec.Id, surveyConfigRec.CreatedBy.CommunityNickname);
            modifiedComNameMap.put(surveyConfigRec.Id, surveyConfigRec.LastModifiedBy.CommunityNickname);
            lastModifiedUser = surveyConfigRec.LastModifiedBy.CommunityNickname;
        }
        
        for(Survey_Configuration__c surveyConfigRec : triggerNewList) {
            surveyConfigDTO scDTO = new surveyConfigDTO();
            scDTO.SurveyConfigID = surveyConfigRec.Name != null ? surveyConfigRec.Name : '';
            scDTO.SurveyID = surveyConfigRec.SurveyID__c != null ? surveyConfigRec.SurveyID__c : '';
            scDTO.QuestionID = surveyConfigRec.QuestionID__c != null ? surveyConfigRec.QuestionID__c : '';
            scDTO.QuestSequence = surveyConfigRec.Question_Sequence__c != null ? String.valueOf(surveyConfigRec.Question_Sequence__c) : '';
            if(surveyConfigRec.Question_Required__c != null && surveyConfigRec.Question_Required__c) { 
                scDTO.QuestMandatory = 'TRUE'; 
            } else if(surveyConfigRec.Question_Required__c != null && !surveyConfigRec.Question_Required__c) { 
                scDTO.QuestMandatory = 'FALSE'; 
            } else if(surveyConfigRec.Question_Required__c == null) {
                scDTO.QuestMandatory = '';
            }
            scDTO.PMQuestionID = surveyConfigRec.PMQuestionID__c != null ? surveyConfigRec.PMQuestionID__c : '';
            scDTO.QuestMultAnswers = surveyConfigRec.MultiAnswers__c != null ? surveyConfigRec.MultiAnswers__c : '';
            scDTO.AnswerID = surveyConfigRec.AnswerID__c != null ? surveyConfigRec.AnswerID__c : '';
            scDTO.AnsSequence = surveyConfigRec.Answer_Sequence__c != null ? String.valueOf(surveyConfigRec.Answer_Sequence__c) : '';
            scDTO.PMAnswerID = surveyConfigRec.PMAnswerID__c != null ? surveyConfigRec.PMAnswerID__c : '';
            scDTO.AnsComments = surveyConfigRec.CommentRequiredFeed__c != null ? surveyConfigRec.CommentRequiredFeed__c : '';
            scDTO.AnsNextQuestionID = surveyConfigRec.QuestionToID__c != null ? surveyConfigRec.QuestionToID__c : '';
            scDTO.CreatedBy = createdComNameMap.get(surveyConfigRec.Id);
            scDTO.createddate = surveyConfigRec.CreatedDate__c != null ? surveyConfigRec.CreatedDate__c : '';
            scDTO.ModifiedBy = modifiedComNameMap.get(surveyConfigRec.Id);
            scDTO.ModifiedDate = surveyConfigRec.LastModifiedDate__c != null ? surveyConfigRec.LastModifiedDate__c : '';
            
            surveyConfigDTOList.add(scDTO);
        }
        
        if(!surveyConfigDTOList.isEmpty()) {
            jsonPayload.userName = lastModifiedUser;
            jsonPayload.SurveyConfig = surveyConfigDTOList;
            System.debug('jsonPayload: ' + JSON.Serialize(jsonPayload));
        	APIDataCalloutServices.dataFeedCallout(JSON.Serialize(jsonPayload), ConstantClass.SURVEYCONFIG_CALLOUT_NAME);
        }
    }
    
    public class jsonRequestDTO {
        public String userName {get; set;}
        public List<surveyConfigDTO> SurveyConfig;
    }
    
    public class surveyConfigDTO {
        public String SurveyConfigID {get; set;}
        public String SurveyID {get; set;}
        public String QuestionID {get; set;}
        public String QuestSequence {get; set;}
        public String QuestMandatory {get; set;}
        public String PMQuestionID {get; set;}
        public String QuestMultAnswers {get; set;}
        public String AnswerID {get; set;}
        public String AnsSequence {get; set;}
        public String PMAnswerID {get; set;}
        public String AnsComments {get; set;}
        public String AnsNextQuestionID {get; set;}
        public String CreatedBy {get; set;}
        public String createddate {get; set;}
        public String ModifiedBy {get; set;}
        public String ModifiedDate {get; set;}
    }
}