force-app/main/default/objects/Issue_Hierarchy__c/Issue_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Issue Hierarchy</label>
    <nameField>
        <displayFormat>IH{0000}</displayFormat>
        <label>Issue Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Alcs_Investigation_Level__c.field-meta.xml
<CustomField>
    <fullName>Alcs_Investigation_Level__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Alcs Investigation Level</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Alert_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Alert_Distribution__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Alert Distribution</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cause_Code__c.field-meta.xml
<CustomField>
    <fullName>Cause_Code__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Cause__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cause Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cause_Name__c.field-meta.xml
<CustomField>
    <fullName>Cause_Name__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Cause__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cause Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/CauseDisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>CauseDisplayOrder__c</fullName>
    <description>Feed Outbound - Hardcode value 0.</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CauseDisplayOrder</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/CauseId__c.field-meta.xml
<CustomField>
    <fullName>CauseId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CauseId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Classification_Code__c.field-meta.xml
<CustomField>
    <fullName>Classification_Code__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Classification__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Classification Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Classification_Des__c.field-meta.xml
<CustomField>
    <fullName>Classification_Des__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Classification__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Classification Des</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/ClassificationDisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>ClassificationDisplayOrder__c</fullName>
    <description>Feed Outbound - Hardcode value &quot;0&quot;</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Classification Display Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/CodeCategory__c.field-meta.xml
<CustomField>
    <fullName>CodeCategory__c</fullName>
    <formula>&apos;CRC&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CodeCategory</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/CodeType__c.field-meta.xml
<CustomField>
    <fullName>CodeType__c</fullName>
    <description>Feed Outbound - HardCode Value &quot;ISSUEHIERARCHY&quot;.</description>
    <formula>&apos;ISSUEHIERARCHY&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <description>Feed Outbound - DateFormat</description>
    <formula>IF(DATEVALUE(CreatedDate) &gt;=
DATE(YEAR(DATEVALUE(CreatedDate)),3,1)
+
(
14-
CASE(MOD(DATE(YEAR(DATEVALUE(CreatedDate)),3,1)-DATE(1900,1,7),7),
0,7,MOD(DATE ( YEAR (DATEVALUE(CreatedDate)),3,1) - DATE (1900,1,7),7))
)
&amp;&amp;
DATEVALUE(CreatedDate) &lt;
DATE(YEAR(DATEVALUE(CreatedDate)),11,1)
+
(
7-
CASE(MOD(DATE(YEAR(DATEVALUE(CreatedDate)),11,1)-DATE(1900,1,7),7),
0,7,MOD(DATE(YEAR(DATEVALUE(CreatedDate)),11,1)-DATE(1900,1,7),7))
),
MID(TEXT(CreatedDate-4/24),6,2)+&quot;/&quot;
+MID(TEXT(CreatedDate-4/24),9,2)+&quot;/&quot;
+MID(TEXT(CreatedDate-4/24),0,4) + &quot; &quot;
+MID(TEXT(CreatedDate-4/24),11,9)
,
MID( TEXT(CreatedDate-5/24),6,2)+&quot;/&quot;
+MID( TEXT(CreatedDate-5/24),9,2)+&quot;/&quot;
+MID( TEXT(CreatedDate-5/24),0,4)+&quot; &quot;
+MID(TEXT(CreatedDate-5/24),11,9)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Cust_Cons_Flag__c.field-meta.xml
<CustomField>
    <fullName>Cust_Cons_Flag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CustConsFlag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/EscalateFlagFeed__c.field-meta.xml
<CustomField>
    <fullName>EscalateFlagFeed__c</fullName>
    <description>Feed Outbound - EscalateFlag Format Output value.</description>
    <formula>IF( Escalate_Flag__c==TRUE, &apos;1&apos;, &apos;0&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EscalateFlag_Feed</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/FactoryControllableFlagFeed__c.field-meta.xml
<CustomField>
    <fullName>FactoryControllableFlagFeed__c</fullName>
    <description>Feed Outbound - Format Output value.</description>
    <formula>IF( Factory_Controllable_Flag__c==TRUE, &apos;1&apos;, &apos;0&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FactoryControllableFlag_Feed</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Group_Code__c.field-meta.xml
<CustomField>
    <fullName>Group_Code__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Group__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Group_Desc__c.field-meta.xml
<CustomField>
    <fullName>Group_Desc__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Group__r.Description__c</formula>
    <label>Group Desc</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/GroupDisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>GroupDisplayOrder__c</fullName>
    <description>Feed Outbound - Hardcode value 0.</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GroupDisplayOrder</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Issue_Association__c.field-meta.xml
<CustomField>
    <fullName>Issue_Association__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Issue Association</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Issue_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Issue_Rollup__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Issue Rollup</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Issue_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type_Code__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Issue_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Issue Type Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Issue_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type_Name__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Issue_Type__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Issue Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/IssueTypeDisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>IssueTypeDisplayOrder__c</fullName>
    <description>Feed Outbound - Hardcode value 0.</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IssueTypeDisplayOrder</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Manf_Investigation_Level__c.field-meta.xml
<CustomField>
    <fullName>Manf_Investigation_Level__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Manf Investigation Level</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Pqrb_Rtp_Category__c.field-meta.xml
<CustomField>
    <fullName>Pqrb_Rtp_Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pqrb Rtp Category</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Product_Line_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Code__c</fullName>
    <formula>Product_Line__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Product_Line__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Product_Return_Level__c.field-meta.xml
<CustomField>
    <fullName>Product_Return_Level__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Return Level</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/ProductLineDisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>ProductLineDisplayOrder__c</fullName>
    <description>Feed Outbound - Hardcode value 0.</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line Display Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Reason__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reason Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Reason_Name__c.field-meta.xml
<CustomField>
    <fullName>Reason_Name__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>Reason__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reason Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/ReasonDisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>ReasonDisplayOrder__c</fullName>
    <description>Feed Outbound - Hardcode value 0</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ReasonDisplayOrder</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/RptCategory__c.field-meta.xml
<CustomField>
    <fullName>RptCategory__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RptCategory</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Select__c.field-meta.xml
<CustomField>
    <fullName>Select__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Select</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Survey_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Survey_Requirements__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Survey Requirements</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/TenantId__c.field-meta.xml
<CustomField>
    <fullName>TenantId__c</fullName>
    <description>It is only for Issue_Hierarchy_Outbound feed.</description>
    <formula>&apos;ALORICAALTRIA&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TenantId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Threshold_With_Manf_Info__c.field-meta.xml
<CustomField>
    <fullName>Threshold_With_Manf_Info__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Threshold With Manf Info</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Threshold_With_Prod_Desc_Only__c.field-meta.xml
<CustomField>
    <fullName>Threshold_With_Prod_Desc_Only__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Threshold With Prod Desc Only</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Hierarchy__c/fields/Visible__c.field-meta.xml
<CustomField>
    <fullName>Visible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IssueHierarchyTriggerHandler.cls
/************************************************************************ 
Author: Randolf Suplito
Date: 08/19/2022
Description: This handler class is for IssueHierarchyTrigger
*************************************************************************/

public class IssueHierarchyTriggerHandler {

    public static Boolean isFirstTime = true;
    
    public static void createCallout(List<Issue_Hierarchy__c> triggerNewList, Map<Id,Issue_Hierarchy__c> triggerNewMap) {
        
        Map<String,String> createdComNameMap = new Map<String,String>();
        Map<String,String> modifiedComNameMap = new Map<String,String>();
        String lastModifiedUser;

        jsonRequestDTO jsonPayload = new jsonRequestDTO();
        List<issueHierarchyDTO> issueHierarchyDTOList = new List<issueHierarchyDTO>();
        
        for(Issue_Hierarchy__c issueHieRec : [SELECT Id, CreatedBy.CommunityNickname, LastModifiedBy.CommunityNickname FROM Issue_Hierarchy__c WHERE Id IN :triggerNewMap.keyset()]) {
            createdComNameMap.put(issueHieRec.Id, issueHieRec.CreatedBy.CommunityNickname);
            modifiedComNameMap.put(issueHieRec.Id, issueHieRec.LastModifiedBy.CommunityNickname);
            lastModifiedUser = issueHieRec.LastModifiedBy.CommunityNickname;
        }
        
        for(Issue_Hierarchy__c issueHieRec : triggerNewList) {
            issueHierarchyDTO ihDTO = new issueHierarchyDTO();
            ihDTO.TENANTID = issueHieRec.TenantId__c != null ? issueHieRec.TenantId__c : '';
            ihDTO.CODECATEGORY = issueHieRec.CodeCategory__c != null ? issueHieRec.CodeCategory__c : '';
            ihDTO.CODETYPE = issueHieRec.CodeType__c != null ? issueHieRec.CodeType__c : '';
            ihDTO.ISSUEHIERARCHYCODE = issueHieRec.Name != null ? issueHieRec.Name : '';
            ihDTO.CLASSIFICATIONCODE = issueHieRec.Classification_Code__c != null ? issueHieRec.Classification_Code__c : '';
            ihDTO.CLASSIFICATION = issueHieRec.Classification_Des__c != null ? issueHieRec.Classification_Des__c : '';
            ihDTO.CLASSIFICATIONDISPLAYORDER = issueHieRec.ClassificationDisplayOrder__c != null ? issueHieRec.ClassificationDisplayOrder__c : '';
            ihDTO.PRODUCTLINECODE = issueHieRec.Product_Line_Code__c != null ? issueHieRec.Product_Line_Code__c : '';
            ihDTO.PRODUCTLINE = issueHieRec.Product_Line_Name__c != null ? issueHieRec.Product_Line_Name__c : '';
            ihDTO.PRODUCTLINEDISPLAYORDER = issueHieRec.ProductLineDisplayOrder__c != null ? issueHieRec.ProductLineDisplayOrder__c : '';
            ihDTO.ISSUETYPECODE = issueHieRec.Issue_Type_Code__c != null ? issueHieRec.Issue_Type_Code__c : '';
            ihDTO.ISSUETYPE = issueHieRec.Issue_Type_Name__c != null ? issueHieRec.Issue_Type_Name__c : '';
            ihDTO.ISSUETYPEDISPLAYORDER = issueHieRec.IssueTypeDisplayOrder__c != null ? issueHieRec.IssueTypeDisplayOrder__c : '';
            ihDTO.GROUPCODE = issueHieRec.Group_Code__c != null ? issueHieRec.Group_Code__c : '';
            ihDTO.GROUPDESC = issueHieRec.Group_Desc__c != null ? issueHieRec.Group_Desc__c : '';
            ihDTO.GROUPDISPLAYORDER = issueHieRec.GroupDisplayOrder__c != null ? issueHieRec.GroupDisplayOrder__c : '';
            ihDTO.REASONCODE = issueHieRec.Reason_Code__c != null ? issueHieRec.Reason_Code__c : '';
            ihDTO.REASON = issueHieRec.Reason_Name__c != null ? issueHieRec.Reason_Name__c : '';
            ihDTO.REASONDISPLAYORDER = issueHieRec.ReasonDisplayOrder__c != null ? issueHieRec.ReasonDisplayOrder__c : '';
            ihDTO.CAUSECODE = issueHieRec.Cause_Code__c != null ? issueHieRec.Cause_Code__c : '';
            ihDTO.CAUSE = issueHieRec.Cause_Name__c != null ? issueHieRec.Cause_Name__c : '';
            ihDTO.CAUSEDISPLAYORDER = issueHieRec.CauseDisplayOrder__c != null ? issueHieRec.CauseDisplayOrder__c : '';
            ihDTO.CUSTCONSFLAG = issueHieRec.Cust_Cons_Flag__c != null ? issueHieRec.Cust_Cons_Flag__c : '';
            ihDTO.RPTCATEGORY = issueHieRec.RptCategory__c != null ? issueHieRec.RptCategory__c : '';
            ihDTO.ESCALATEFLAG = issueHieRec.EscalateFlagFeed__c != null ? issueHieRec.EscalateFlagFeed__c : '';
            ihDTO.ISSUEASSOCIATION = issueHieRec.Issue_Association__c != null ? issueHieRec.Issue_Association__c : '';
            ihDTO.ISSROLLUP = issueHieRec.Issue_Rollup__c != null ? issueHieRec.Issue_Rollup__c : '';
            ihDTO.FACTORYCONTROLLABLEFLAG = issueHieRec.FactoryControllableFlagFeed__c != null ? issueHieRec.FactoryControllableFlagFeed__c : '';
            ihDTO.PQRBRTPCATEGORY = issueHieRec.Pqrb_Rtp_Category__c != null ? issueHieRec.Pqrb_Rtp_Category__c : '';
            if(issueHieRec.Visible__c != null && issueHieRec.Visible__c) { 
                ihDTO.VISIBLE = 'Y'; 
            } else if(issueHieRec.Visible__c != null && !issueHieRec.Visible__c) { 
                ihDTO.VISIBLE = 'N'; 
            } else if(issueHieRec.Visible__c == null) {
                ihDTO.VISIBLE = '';
            }
            if(issueHieRec.Select__c != null && issueHieRec.Select__c) { 
                ihDTO.SELECT1 = 'Y'; 
            } else if(issueHieRec.Select__c != null && !issueHieRec.Select__c) { 
                ihDTO.SELECT1 = 'N'; 
            } else if(issueHieRec.Select__c == null) {
                ihDTO.SELECT1 = ''; 
            }
            ihDTO.PRODUCTRETURNLEVEL = issueHieRec.Product_Return_Level__c != null ? issueHieRec.Product_Return_Level__c : '';
            ihDTO.ALERTDISTRIBUTION = issueHieRec.Alert_Distribution__c != null ? issueHieRec.Alert_Distribution__c : '';
            ihDTO.ALCSINVESTIGATIONLEVEL = issueHieRec.Alcs_Investigation_Level__c != null ? issueHieRec.Alcs_Investigation_Level__c : '';
            ihDTO.MANFINVESTIGATIONLEVEL = issueHieRec.Manf_Investigation_Level__c != null ? issueHieRec.Manf_Investigation_Level__c : '';
            ihDTO.THRESHOLDWITHMANFINFO = issueHieRec.Threshold_With_Manf_Info__c != null ? issueHieRec.Threshold_With_Manf_Info__c : '';
            ihDTO.THRESHOLDWITHPRODDESCONLY = issueHieRec.Threshold_With_Prod_Desc_Only__c != null ? issueHieRec.Threshold_With_Prod_Desc_Only__c : '';
            ihDTO.SURVEYREQUIREMENTS = issueHieRec.Survey_Requirements__c != null ? issueHieRec.Survey_Requirements__c : '';
            ihDTO.CAUSEID = issueHieRec.CauseId__c != null ? issueHieRec.CauseId__c : '';
            if(issueHieRec.Active__c != null && issueHieRec.Active__c) { 
                ihDTO.ACTIVEFLAG = 'Y'; 
            } else if(issueHieRec.Active__c != null && !issueHieRec.Active__c) { 
                ihDTO.ACTIVEFLAG = 'N'; 
            } else if(issueHieRec.Active__c == null) {
                ihDTO.ACTIVEFLAG = ''; 
            }
            ihDTO.CREATEDDATE = issueHieRec.CreatedDate__c != null ? issueHieRec.CreatedDate__c : '';
            ihDTO.CREATEDBY = createdComNameMap.get(issueHieRec.Id);
            ihDTO.MODIFIEDDATE = issueHieRec.LastModifiedDate__c != null ? issueHieRec.LastModifiedDate__c : '';
            ihDTO.MODIFIEDBY = modifiedComNameMap.get(issueHieRec.Id);
            ihDTO.ARCHIVALDATE = issueHieRec.Archival_Date__c != null ? issueHieRec.Archival_Date__c : '';
            ihDTO.SUBJECT_CODE = issueHieRec.SUBJECT_CODE__c != null ? issueHieRec.SUBJECT_CODE__c : '';
            ihDTO.SUBJECT_DESC = issueHieRec.SUBJECT_DESC__c != null ? issueHieRec.SUBJECT_DESC__c : '';
            
            issueHierarchyDTOList.add(ihDTO);
        }
        
        if(!issueHierarchyDTOList.isEmpty()) {
            jsonPayload.userName = lastModifiedUser;
            jsonPayload.IssueHierarchy = issueHierarchyDTOList;
            System.debug('jsonPayload: ' + JSON.Serialize(jsonPayload));
        	APIDataCalloutServices.dataFeedCallout(JSON.Serialize(jsonPayload), ConstantClass.ISSUEHIERARCHY_CALLOUT_NAME);
        }
    }
    
    public class jsonRequestDTO {
        public String userName {get; set;}
        public List<issueHierarchyDTO> IssueHierarchy;
    }
    
    public class issueHierarchyDTO {
        public String TENANTID {get; set;}
        public String CODECATEGORY {get; set;}
        public String CODETYPE {get; set;}
        public String ISSUEHIERARCHYCODE {get; set;}
        public String CLASSIFICATIONCODE {get; set;}
        public String CLASSIFICATION {get; set;}
        public String CLASSIFICATIONDISPLAYORDER {get; set;}
        public String PRODUCTLINECODE {get; set;}
        public String PRODUCTLINE {get; set;}
        public String PRODUCTLINEDISPLAYORDER {get; set;}
        public String ISSUETYPECODE {get; set;}
        public String ISSUETYPE {get; set;}
        public String ISSUETYPEDISPLAYORDER {get; set;}
        public String GROUPCODE {get; set;}
        public String GROUPDESC {get; set;}
        public String GROUPDISPLAYORDER {get; set;}
        public String REASONCODE {get; set;}
        public String REASON {get; set;}
        public String REASONDISPLAYORDER {get; set;}
        public String CAUSECODE {get; set;}
        public String CAUSE {get; set;}
        public String CAUSEDISPLAYORDER {get; set;}
        public String CUSTCONSFLAG {get; set;}
        public String RPTCATEGORY {get; set;}
        public String ESCALATEFLAG {get; set;}
        public String ISSUEASSOCIATION {get; set;}
        public String ISSROLLUP {get; set;}
        public String FACTORYCONTROLLABLEFLAG {get; set;}
        public String PQRBRTPCATEGORY {get; set;}
        public String VISIBLE {get; set;}
        public String SELECT1 {get; set;}
        public String PRODUCTRETURNLEVEL {get; set;}
        public String ALERTDISTRIBUTION {get; set;}
        public String ALCSINVESTIGATIONLEVEL {get; set;}
        public String MANFINVESTIGATIONLEVEL {get; set;}
        public String THRESHOLDWITHMANFINFO {get; set;}
        public String THRESHOLDWITHPRODDESCONLY {get; set;}
        public String SURVEYREQUIREMENTS {get; set;}
        public String CAUSEID {get; set;}
        public String ACTIVEFLAG {get; set;}
        public String CREATEDDATE {get; set;}
        public String CREATEDBY {get; set;}
        public String MODIFIEDDATE {get; set;}
        public String MODIFIEDBY {get; set;}
        public String ARCHIVALDATE {get; set;}
        public String SUBJECT_CODE {get; set;}
        public String SUBJECT_DESC {get; set;}
    }
}