force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>QuestionID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <description>Feed Outbound - DateFormat.</description>
    <formula>IF(DATEVALUE(CreatedDate) &gt;=
DATE(YEAR(DATEVALUE(CreatedDate)),3,1)
+
(
14-
CASE(MOD(DATE(YEAR(DATEVALUE(CreatedDate)),3,1)-DATE(1900,1,7),7),
0,7,MOD(DATE ( YEAR (DATEVALUE(CreatedDate)),3,1) - DATE (1900,1,7),7))
)
&amp;&amp;
DATEVALUE(CreatedDate) &lt;
DATE(YEAR(DATEVALUE(CreatedDate)),11,1)
+
(
7-
CASE(MOD(DATE(YEAR(DATEVALUE(CreatedDate)),11,1)-DATE(1900,1,7),7),
0,7,MOD(DATE(YEAR(DATEVALUE(CreatedDate)),11,1)-DATE(1900,1,7),7))
),
MID(TEXT(CreatedDate-4/24),6,2)+&quot;/&quot;
+MID(TEXT(CreatedDate-4/24),9,2)+&quot;/&quot;
+MID(TEXT(CreatedDate-4/24),0,4) + &quot; &quot;
+MID(TEXT(CreatedDate-4/24),11,9)
,
MID( TEXT(CreatedDate-5/24),6,2)+&quot;/&quot;
+MID( TEXT(CreatedDate-5/24),9,2)+&quot;/&quot;
+MID( TEXT(CreatedDate-5/24),0,4)+&quot; &quot;
+MID(TEXT(CreatedDate-5/24),11,9)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CreatedDate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/DefEndPos__c.field-meta.xml
<CustomField>
    <fullName>DefEndPos__c</fullName>
    <description>Feed Outbound - hard code value 0</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DefEndPos</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/DefStartPos__c.field-meta.xml
<CustomField>
    <fullName>DefStartPos__c</fullName>
    <description>Feed Outbound - hardcode value 0.</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DefStartPos</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/IsDeleted__c.field-meta.xml
<CustomField>
    <fullName>IsDeleted__c</fullName>
    <description>Feed Outbound - hard code value 0.</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsDeleted</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/LastModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedDate__c</fullName>
    <description>Feed Outbound - Dateformat.</description>
    <formula>IF ( DATEVALUE(LastModifiedDate) &gt;=
DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1)
+
(
14-
CASE( MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1) - DATE (1900,1,4),4) ,
0,4,MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),3,1) - DATE (1900,1,4),4))
)
&amp;&amp;
DATEVALUE(LastModifiedDate) &lt;
DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1)
+
(
4-
CASE( MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1) - DATE (1900,1,4),4) ,
0,4,MOD(DATE ( YEAR (DATEVALUE(LastModifiedDate)),11,1) - DATE (1900,1,4),4))
),
MID( TEXT(LastModifiedDate- 4/24) , 6, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 4/24) , 9, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 4/24) , 0, 4) + &quot; &quot;+MID(TEXT(LastModifiedDate- 4/24), 11, 9)
,
MID( TEXT(LastModifiedDate- 5/24) , 6, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 5/24) , 9, 2)+&quot;/&quot;+MID( TEXT(LastModifiedDate- 5/24) , 0, 4) + &quot; &quot;+MID(TEXT(LastModifiedDate- 5/24), 11, 9)
)</formula>
    <label>LastModifiedDate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/MultiAnswers__c.field-meta.xml
<CustomField>
    <fullName>MultiAnswers__c</fullName>
    <description>Feed Outbound.</description>
    <formula>IF( ISPICKVAL(Type__c, &apos;Multiple Choice&apos;) , &apos;1&apos;, &apos;0&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MultiAnswers</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/PMQuestionID__c.field-meta.xml
<CustomField>
    <fullName>PMQuestionID__c</fullName>
    <label>PMQuestionID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Question</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/QuestionToCheck__c.field-meta.xml
<CustomField>
    <fullName>QuestionToCheck__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>QuestionToCheck</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuestionTriggerHandler.cls
/************************************************************************ 
Author: Randolf Suplito
Date: 08/22/2022
Description: This handler class is for QuestionTrigger
*************************************************************************/

public class QuestionTriggerHandler {

    public static Boolean isFirstTime = true;
    
    public static void createCallout(List<Question__c> triggerNewList, Map<Id,Question__c> triggerNewMap) {
        
        Map<String,String> createdComNameMap = new Map<String,String>();
        Map<String,String> modifiedComNameMap = new Map<String,String>();
        String lastModifiedUser;
        
        jsonRequestDTO jsonPayload = new jsonRequestDTO();
        List<questionDTO> questionDTOList = new List<questionDTO>();
        
        for(Question__c questionRec : [SELECT Id, CreatedBy.CommunityNickname, LastModifiedBy.CommunityNickname FROM Question__c WHERE Id IN :triggerNewMap.keyset()]) {
            createdComNameMap.put(questionRec.Id, questionRec.CreatedBy.CommunityNickname);
            modifiedComNameMap.put(questionRec.Id, questionRec.LastModifiedBy.CommunityNickname);
            lastModifiedUser = questionRec.LastModifiedBy.CommunityNickname;
        }
        
        for(Question__c questionRec : triggerNewList) {
            questionDTO qDTO = new questionDTO();
            qDTO.QUESTIONID = questionRec.Name != null ? questionRec.Name : '';
            qDTO.QUESTION = questionRec.Question__c != null ? questionRec.Question__c : '';
            if(questionRec.Active__c != null && questionRec.Active__c) { 
                qDTO.ACTIVEFLAG = '1'; 
            } else if(questionRec.Active__c != null && !questionRec.Active__c) { 
                qDTO.ACTIVEFLAG = '0'; 
            } else if(questionRec.Active__c == null) {
                qDTO.ACTIVEFLAG = '';
            }
            qDTO.PMQUESTIONID = questionRec.PMQuestionID__c != null ? String.valueOf(questionRec.PMQuestionID__c) : '';
            qDTO.MULTIANSWERS = questionRec.MultiAnswers__c != null ? questionRec.MultiAnswers__c : '';
            qDTO.DEFSTARTPOS = questionRec.DefStartPos__c != null ? questionRec.DefStartPos__c : '';
            qDTO.DEFENDPOS = questionRec.DefEndPos__c != null ? questionRec.DefEndPos__c : '';
            qDTO.CREATEDDATE = questionRec.CreatedDate__c != null ? questionRec.CreatedDate__c : '';
            qDTO.CREATEDBY = createdComNameMap.get(questionRec.Id);
            qDTO.MODIFIEDDATE = questionRec.LastModifiedDate__c != null ? questionRec.LastModifiedDate__c : '';
            qDTO.MODIFIEDBY = modifiedComNameMap.get(questionRec.Id);
            qDTO.ISDELETED = questionRec.IsDeleted__c != null ? questionRec.IsDeleted__c : '';
            qDTO.QUESTIONTOCHECK = questionRec.QuestionToCheck__c != null ? questionRec.QuestionToCheck__c : '';
            
            questionDTOList.add(qDTO);
        }
        
        if(!questionDTOList.isEmpty()) {
            jsonPayload.userName = lastModifiedUser;
            jsonPayload.SurveyQuestion = questionDTOList;
            System.debug('jsonPayload: ' + JSON.Serialize(jsonPayload));
        	APIDataCalloutServices.dataFeedCallout(JSON.Serialize(jsonPayload), ConstantClass.QUESTION_CALLOUT_NAME);
        }
    }
    
    public class jsonRequestDTO {
        public String userName {get; set;}
        public List<questionDTO> SurveyQuestion;
    }
    
    public class questionDTO {
        public String QUESTIONID {get; set;}
        public String QUESTION {get; set;}
        public String ACTIVEFLAG {get; set;}
        public String PMQUESTIONID {get; set;}
        public String MULTIANSWERS {get; set;}
        public String DEFSTARTPOS {get; set;}
        public String DEFENDPOS {get; set;}
        public String CREATEDDATE {get; set;}
        public String CREATEDBY {get; set;}
        public String MODIFIEDDATE {get; set;}
        public String MODIFIEDBY {get; set;}
        public String ISDELETED {get; set;}
        public String QUESTIONTOCHECK {get; set;}
    }
}