force-app/main/default/objects/Profile_Permission_Setting__c/Profile_Permission_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To save the permission for profile to edit records based on the transaction.</description>
    <label>Profile Permission Setting</label>
</CustomObject>

force-app/main/default/objects/Reimbursement__c/Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Reimbursement</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Reimbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement__c/fields/Altria_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Altria_File_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Altria File Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Apt_Lot__c.field-meta.xml
<CustomField>
    <fullName>Apt_Lot__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Apt / Lot</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Card Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Cheque_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Amount__c</fullName>
    <label>Check Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City / Locality</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Consumer__c.field-meta.xml
<CustomField>
    <fullName>Consumer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consumer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Ecount_ID__c.field-meta.xml
<CustomField>
    <fullName>Ecount_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ecount ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>File Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <label>Issue Name</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/IssueID__c.field-meta.xml
<CustomField>
    <fullName>IssueID__c</fullName>
    <description>Feed Outbound</description>
    <formula>Issue__r.CaseNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Issue ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <formula>Issue__r.Purchase_Price__c</formula>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Reimbursement_Type__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Type__c</fullName>
    <label>Reimbursement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plastic</fullName>
                <default>true</default>
                <label>Plastic</label>
            </value>
            <value>
                <fullName>Virtual Card</fullName>
            </value>
            <value>
                <fullName>Virtual Pending</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
                <isActive>false</isActive>
                <label>Check</label>
            </value>
            <value>
                <fullName>Wirecard</fullName>
                <isActive>false</isActive>
                <label>Wirecard</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>State / Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street Address / Address1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Id</label>
    <referenceTo>Transaction_Management__c</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Transfer_to_Altria_Date__c.field-meta.xml
<CustomField>
    <fullName>Transfer_to_Altria_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Transfer to Altria Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip Code / Postal Code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReimbursementDetailController.cls
/*
Functionality to the Reimbursement Detail page
7/5/2016 Infogain – Created.
*/

public class ReimbursementDetailController{
    public Reimbursement__c reimbursement{get;set;} /* Object to get reimbursement data */
    public boolean isCorrespondenceReq{get;set;} /* Boolean flag for corresepondence requirement */
    public boolean isAllowedToEdit{get;set;} /*Boolean flag to set the permission to edit the reimbursement */
    public string tranid{get;set;}
    public string consumerName{get;set;}
    public Boolean showReimbAddtl {get;set;}
    public String inConsole{get;set;}
    
    public ReimbursementDetailController(ApexPages.StandardController controller){
        isAllowedToEdit = false;    
        boolean isCurrTransaction = true;
        boolean isProfileAllowed = true; 
        consumerName = '';       
        String reimbursementId = ApexPages.currentPage().getParameters().get('id');
        try{
            this.reimbursement = [Select Id,Issue__c,IssueID__c,Reimbursement_Type__c,Consumer__c,Status__c,
                                      Cheque_Amount__c,Name,TransactionId__c, Consumer__r.Name,Purchase_Price__c,
                                      First_Name__c, Last_Name__c, Street_Address__c,
                                      Apt_Lot__c, City__c, State__c, Zip_Code__c, Transfer_to_Altria_Date__c,
                                      Altria_File_Name__c, File_Name__c, Ship_Date__c,
                                      Ecount_ID__c, Card_Number__c,
                                  	  Consumer__r.Email, Consumer__r.Email_Verified__c
                                  From Reimbursement__c  Where Id =: reimbursementId Limit 1];
            Cookie counter = ApexPages.currentPage().getCookies().get('tranid');
            if(counter != null) {
                tranid = counter.getValue();
            }
            consumerName = reimbursement.Consumer__r.Name;
            if(tranid != reimbursement.TransactionId__c){
                isCurrTransaction = false;
            }
            string profileName = getCurrentUserprofileName();
            if(profileName != null && profileName != ''){
                Profile_Permission_Setting__c profilePerm = Profile_Permission_Setting__c.getValues(profileName);
                if(profilePerm != null){
                    isProfileAllowed = profilePerm.AllowedToEditReimbursement__c;
                }
            }
            if(isCurrTransaction || isProfileAllowed){
                isAllowedToEdit = true;
            }
        }catch(Exception ex){
        }
        updateStatus();
    }
    
    /*Update Correspondence Status*/
    public void updateStatus(){
        if(reimbursement.Status__c == 'Age Not Verified'){
            isCorrespondenceReq = true;
        }else{
            isCorrespondenceReq = false;
        }
    }
    /* Get the current user profile Name */
    public string getCurrentUserprofileName(){
        string currUserProfileId = UserInfo.getProfileId();
        Profile currProfileName = [Select Name from Profile where Id =: currUserProfileId limit 1];
        string profileName;
        if(currProfileName != null){
            profileName = currProfileName.name;
        }
        return profileName;
    }
    
   //This will assign value passed from javascript to controller
    public void assignValue(){
        if(Test.isRunningTest()){
            inConsole = 'true';
        }
 		String profileName = getCurrentUserprofileName();
        if(profileName == 'CRC Agent'){
        	showReimbAddtl = false;   
        }else
        {
    		showReimbAddtl = Boolean.valueOf(inConsole);
        }
    }

}