force-app/main/default/objects/IntegrationLog__c/IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegrationLog__c/fields/Transaction_Management__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Management</label>
    <referenceTo>Transaction_Management__c</referenceTo>
    <relationshipLabel>Integration Logs</relationshipLabel>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/TFN__c.object-meta.xml
<CustomObject>
    <label>TFN</label>
    <nameField>
        <displayFormat>TFN-{0000}</displayFormat>
        <label>TFN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Toll Free Number</relationshipLabel>
    <relationshipName>Toll_Free_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/Transaction_Management__c.object-meta.xml
<CustomObject>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Management__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/TFN__c.field-meta.xml
<CustomField>
    <fullName>TFN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DNIS</label>
    <referenceTo>TFN__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AcxiomTest.cls
@isTest
public class AcxiomTest {
    
    static testmethod void testAcxiomClasses(){
        
        AcxiomClasses.OpCoQualification aaTest = new AcxiomClasses.OpCoQualification();
        List<AcxiomClasses.OpCoQualification> qIList = new List<AcxiomClasses.OpCoQualification>();
        qIList.add(aaTest);
        AcxiomClasses.QualificationData QAD = new AcxiomClasses.QualificationData();
        QAD.OpCoQualification = qIList;
        
        AcxiomClasses.ContactInfo testcontact = new AcxiomClasses.ContactInfo();
        List<AcxiomClasses.ContactInfo> clist = new List<AcxiomClasses.ContactInfo>();
        clist.add(testcontact);
        AcxiomClasses.AddressType ad = new AcxiomClasses.AddressType();
        ad.ContactInfo = clist;
        
        List<AcxiomClasses.AddressType> adList = new List<AcxiomClasses.AddressType>();
        adList.add(ad);
        
        
        AcxiomClasses.ChannelLevel cl = new AcxiomClasses.ChannelLevel();
        cl.AddressType = adList;
        
        List<AcxiomClasses.ChannelLevel> clSt = new List<AcxiomClasses.ChannelLevel>();
        clSt.add(cl);
        
        AcxiomClasses.Channel cc = new AcxiomClasses.Channel();
        cc.ChannelLevel = clSt;
        
        List<AcxiomClasses.Channel> ccList = new List<AcxiomClasses.Channel>();
        ccList.add(cc);
        
        AcxiomClasses.ChannelData ccData = new AcxiomClasses.ChannelData();
        ccData.Channel = ccList;
        
        AcxiomClasses.Individual inData = new  AcxiomClasses.Individual();
        inData.PID = '1234';
        
        List<AcxiomClasses.AuthenticationData> ad1 = new List<AcxiomClasses.AuthenticationData>();
        
        AcxiomClasses.ConsumerFullSearchResponse fullSrch = new AcxiomClasses.ConsumerFullSearchResponse();
        fullSrch.QualificationData = QAD;
        fullSrch.ChannelData = ccData;
        fullSrch.AuthenticationData = ad1;
        
        AcxiomClasses.CCNLookupResponse cnnSrch = new AcxiomClasses.CCNLookupResponse();
        cnnSrch.QualificationData = QAD;
        cnnSrch.ChannelData = ccData;
		cnnSrch.Individual = inData;
	}
    
    static testmethod void testAcxiomServices(){
        
        IntegrationLog__c iL = new IntegrationLog__c();
        iL = AcxiomServices.getAccessToken();
        
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Test.startTest();
        AcxiomClasses.ConsumerFinalResponse cfr = new AcxiomClasses.ConsumerFinalResponse();
        cfr = AcxiomServices.FullSearchLookupRequest('test', testTM.id, 'test');
        
        AcxiomClasses.CCNLookupFinalResponse ccfr = new AcxiomClasses.CCNLookupFinalResponse();
        ccfr = AcxiomServices.CCNLookupRequest('test', 'test',testTM.id, 'test');
        Test.stopTest();
    }
}