force-app/main/default/objects/IntegrationLog__c/IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purge_Tracking__c/Purge_Tracking__c.object-meta.xml
<CustomObject>
    <label>Purge Tracking</label>
    <nameField>
        <displayFormat>PT{00000}</displayFormat>
        <label>Purge Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purge Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purge_Tracking__c/fields/NumberOfErrors__c.field-meta.xml
<CustomField>
    <fullName>NumberOfErrors__c</fullName>
    <label>NumberOfErrors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purge_Tracking__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attachment</fullName>
            </value>
            <value>
                <fullName>Contact (Consumer and trade  customer)</fullName>
            </value>
            <value>
                <fullName>Correspondence &amp; Fulfilment</fullName>
            </value>
            <value>
                <fullName>Integration Log</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Issue Adjustment (Review Data)</fullName>
            </value>
            <value>
                <fullName>Reimbursement</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>Survey Issue</fullName>
            </value>
            <value>
                <fullName>Transaction Management</fullName>
            </value>
            <value>
                <fullName>Transaction Management History</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurgingMonth__c/PurgingMonth__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Purging Month</label>
</CustomObject>

force-app/main/default/objects/PurgingMonth__c/fields/Month_Count__c.field-meta.xml
<CustomField>
    <fullName>Month_Count__c</fullName>
    <defaultValue>12</defaultValue>
    <label>Month Count</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchApexPurgeIntegrationLogRecords.cls
global class  BatchApexPurgeIntegrationLogRecords implements Database.Batchable<sObject>, Database.Stateful{

    global integer TotalRecordsChanged = 0;
    global integer TotalErrorRecordsChanged = 0;
    global Date startDate; 
    global Integer MonthCount = 0;
    global BatchApexPurgeIntegrationLogRecords (){
       
       PurgingMonth__c monthData = PurgingMonth__c.getInstance();
       
       if(monthData != null && monthData.Month_Count__c != null){
           MonthCount  = Integer.ValueOf(monthData.Month_Count__c);
       }else{
           MonthCount  = 24;
       }    
    }
    
    global database.querylocator start(Database.BatchableContext BC){  
       Date myDate = Date.newInstance(date.today().year(), date.today().month(), 1);
       
       startDate = myDate.addmonths(-MonthCount); 
       String strQuery = '';  
       if(!Test.isRunningTest()){ 
           strQuery = 'Select id from IntegrationLog__c where LastModifiedDate <: startDate';
       }else{
           strQuery = 'Select id from IntegrationLog__c  limit 1';
       }   
       return Database.getQueryLocator(strQuery);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        List<IntegrationLog__c> IntegrationLogList = (List<IntegrationLog__c>)scope;
        TotalRecordsChanged = TotalRecordsChanged + scope.size();
        Database.DeleteResult[] drIntegrationLogList = Database.delete(IntegrationLogList, false);
        
        List<id> idInteg =new List<id>();
        for(Database.DeleteResult dr : drIntegrationLogList) {
            if (dr.isSuccess()) {
               idInteg.add(dr.getId());     
            }else{
                List<Database.Error> errors = dr.getErrors();
                TotalErrorRecordsChanged = TotalErrorRecordsChanged+ errors.size();
            }
        }
        
        if(!idInteg.isEmpty())
            Database.EmptyRecycleBinResult[] emp4 = Database.emptyRecycleBin(idInteg);
        
    }
    
    global void finish(Database.BatchableContext BC) {       
       
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        Purge_Tracking__c purgeObj = new Purge_Tracking__c(NumberOfErrors__c = TotalErrorRecordsChanged, Object_Name__c = 'Integration Log', Status__c = job.Status,Total_Records__c = TotalRecordsChanged);
        
        insert purgeObj;               
    }    
}