force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/TFN__c.object-meta.xml
<CustomObject>
    <label>TFN</label>
    <nameField>
        <displayFormat>TFN-{0000}</displayFormat>
        <label>TFN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Toll Free Number</relationshipLabel>
    <relationshipName>Toll_Free_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/Transaction_Management__c.object-meta.xml
<CustomObject>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Management__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/TFN__c.field-meta.xml
<CustomField>
    <fullName>TFN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DNIS</label>
    <referenceTo>TFN__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailMessageTest.cls
@isTest
public with sharing class EmailMessageTest 
{
	public  static date date1;
	
    public static testmethod void TestEmailMessageInsert()
    {
    	Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        list<Case> lstCase = new list<Case>();
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id, testTM.Id,testOpCo.id);
        lstCase.add(testCase);
        testCase.Incident_Date__c=date1;   
        Case caseobj2=TestDataSetup.createTestCase(testAcc,105.3,testCont.Id, testTM.Id,testOpCo.id);
        lstCase.add(caseobj2);
        insert lstCase;
        //---------------------------
        
        //---------------------------
    	
    	EmailMessage[] newEmail = new EmailMessage[0];
    	
    	newEmail.add(new EmailMessage(FromAddress = 'oldwen.adriano@alorica.com',
		FromName = 'Oldwen',
		ToAddress = 'oldwen.adriano@alorica.com',
		Subject = 'Email Subject',
		TextBody = 'No body',
		HtmlBody = 'Hello',
		ParentId = caseobj2.Id));   // (newCase and newTask are the newly created case and task from earlier code)
		
		//ParentId = caseobj2.Id, 
		//ActivityId = newTask[0].Id));   // (newCase and newTask are the newly created case and task from earlier code)
		 
		
		insert newEmail;
    }
}