force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operating_Company__c/fields/Default_TFN__c.field-meta.xml
<CustomField>
    <fullName>Default_TFN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default TFN</label>
    <referenceTo>TFN__c</referenceTo>
    <relationshipLabel>Operating Companies</relationshipLabel>
    <relationshipName>Operating_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFN__c/TFN__c.object-meta.xml
<CustomObject>
    <label>TFN</label>
    <nameField>
        <displayFormat>TFN-{0000}</displayFormat>
        <label>TFN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Toll Free Number</relationshipLabel>
    <relationshipName>Toll_Free_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ChatConsumerSearchControllerTest.cls
/*
*   @Author: Ariel Tribunal
*   @Date: 7/29/2019
*   @Apex Name: ChatConsumerSearchControllerTest
*   @Description: Test class for ChatConsumerSearchController coverage
*
*/
@isTest
public class ChatConsumerSearchControllerTest{
    
    static TestMethod void TestredirectCustomerSearch(){
        // Setup Data
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        TFN__c testTFN= TestDataSetup.createTFN(True,'0001',1,testOpCo);
        insert testTFN;
        testOpCo.Default_TFN__c = testTFN.Id;
        update testOpCo;
        
        Test.startTest();
        PageReference ActPgref = ChatConsumerSearchController.redirectCustomerSearch();
        Test.stopTest();
        // Validate return PageReference
        PageReference ExpPgref = new pagereference('/apex/ConsumerSearch');
        system.assertNotEquals(ExpPgref, ActPgref);
    }
    
}