force-app/main/default/objects/Operating_Company__c/Operating_Company__c.object-meta.xml
<CustomObject>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operating_Company__c/fields/Default_TFN__c.field-meta.xml
<CustomField>
    <fullName>Default_TFN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default TFN</label>
    <referenceTo>TFN__c</referenceTo>
    <relationshipLabel>Operating Companies</relationshipLabel>
    <relationshipName>Operating_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operating_Company__c/fields/OperatingCompany__c.field-meta.xml
<CustomField>
    <fullName>OperatingCompany__c</fullName>
    <label>Operating Company</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRC Direct</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>NAT_SHERMAN</fullName>
            </value>
            <value>
                <fullName>NUMARK</fullName>
            </value>
            <value>
                <fullName>PM Corporate</fullName>
            </value>
            <value>
                <fullName>PMIP</fullName>
            </value>
            <value>
                <fullName>PMUSA</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>USST</fullName>
            </value>
            <value>
                <fullName>USSTC</fullName>
            </value>
            <value>
                <fullName>HELIX</fullName>
            </value>
            <value>
                <fullName>NJOY</fullName>
            </value>
            <value>
                <fullName>6601 Ventures</fullName>
            </value>
            <value>
                <fullName>USSTN</fullName>
            </value>
            <value>
                <fullName>HORIZON</fullName>
            </value>
            <value>
                <fullName>NUMRK</fullName>
                <isActive>false</isActive>
                <label>NUMRK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operating_Company__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <formula>ISPICKVAL(OperatingCompany__c, &apos;Trade&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trade</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TFN__c/TFN__c.object-meta.xml
<CustomObject>
    <label>TFN</label>
    <nameField>
        <displayFormat>TFN-{0000}</displayFormat>
        <label>TFN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TFN__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Toll Free Number</relationshipLabel>
    <relationshipName>Toll_Free_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/Transaction_Management__c.object-meta.xml
<CustomObject>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Management__c/fields/Operating_Company__c.field-meta.xml
<CustomField>
    <fullName>Operating_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Company</label>
    <referenceTo>Operating_Company__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction_Management__c/fields/TFN__c.field-meta.xml
<CustomField>
    <fullName>TFN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DNIS</label>
    <referenceTo>TFN__c</referenceTo>
    <relationshipLabel>Transaction Managements</relationshipLabel>
    <relationshipName>Transaction_Managements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChatConsumerSearchController.cls
/*
*   @Author: Ariel Tribunal
*   @Date: 5/8/2019
*   @Apex Name: ChatConsumerSearchController
*   @Description: This controller is use by ChatConsumerSearch.page
*
*/
public class ChatConsumerSearchController {
    public static Transaction_Management__c transmgmObj;
    private string customerNumber;
    private string tollNumber;
    private string ucid;
    
    public static PageReference redirectCustomerSearch() {
        PageReference pgRef = null;
        String tranid = '';
        transmgmObj = new Transaction_Management__c();
        List<Operating_Company__c> opCom = new List<Operating_Company__c>([select id,Default_TFN__c,
            OperatingCompany__c,Trade__c from Operating_Company__c where OperatingCompany__c = 'PMUSA']);
        
        transmgmObj.Operating_Company__c = opCom[0].id;
        transmgmObj.Start_Date_Time__c = system.now();
        transmgmObj.TFN__c = opCom[0].Default_TFN__c;
        transmgmObj.Comments__c = 'Chat';
        
        //system.debug('redirectCustomerSearch: transmgmObj=' + transmgmObj);
        
        Database.UpsertResult upsRst =  Database.upsert(transmgmObj); 
            
        if(upsRst != null && upsRst.isSuccess())
            tranid = upsRst.getId();
        system.debug('redirectCustomerSearch: tranid=' + tranid);
        
        if(tranid != null && tranid != ''){
        
            //Set the transaction data in Cookie
            Cookie counter = new Cookie('tranid', tranid ,null,-1,true);
            ApexPages.currentPage().setCookies(new Cookie[]{counter});

            system.debug('redirectCustomerSearch: counter=' + counter);            

            counter = new Cookie('customerRecType', 'consumer',null,-1,true);
            ApexPages.currentPage().setCookies(new Cookie[]{counter});
            pgRef = new pagereference('/apex/ConsumerSearch?tranid='+tranid+'&customerRecType=consumer');
        }
        //system.debug('redirectCustomerSearch: pgRef=' + pgRef);
        return pgRef;
    }
}