force-app/main/default/objects/Issue_Adjustment__c/Issue_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Issue Adjustment</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Issue Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues Adjustment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Adjustment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Issue_Adjustment__c/fields/isReviewed__c.field-meta.xml
<CustomField>
    <fullName>isReviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isReviewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Issue_Adjustment__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Issues Adjustment</relationshipLabel>
    <relationshipName>Cases_Adjustment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Adjustment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IssueAdjustmentReviewDetailController.cls
public class IssueAdjustmentReviewDetailController {

    // Global declaration of variables
    public Case caseObj {get;set;}
    public Issue_Adjustment__c issueAdjustment {get;set;}
    public boolean isUpdateReasonVisible{get;set;}
    public String custName {get;set;} 
    public string custId{get;set;}
    public string customerRecType {get;set;} 
    
    // Constructor
    public IssueAdjustmentReviewDetailController(ApexPages.StandardController controller) {
        this.caseObj = (Case)controller.getRecord();
        issueAdjustment = new Issue_Adjustment__c();
        Id issueAdjust =ApexPages.currentPage().getParameters().get('issueAdjust');
        if(issueAdjust  != null){
            issueAdjustment = [Select id,IsReviewed__c,Issue__c,Status__c,Comment__c from Issue_Adjustment__c where id=: issueAdjust];
            CheckValidation();
            custName  = '';
            custId = '';
            getCustomerDetails();
        }
        
    }
    public void CheckValidation(){     
        if (issueAdjustment.IsReviewed__c == True){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info,'Issue Reviewed'));
        } 
    }
        
    public void getCustomerDetails(){
       Case currIssue = [Select Id, Contact.Name, Contact.CustomerID__c,ContactId, Contact.RecordType.Name From Case Where Id =: this.caseObj.id limit 1];
       if(currIssue.ContactId != null){
            custName  = currIssue.Contact.Name;
            custId = currIssue.Contact.CustomerID__c;
            if(currIssue.Contact.RecordType.Name  == 'Consumer'){
                customerRecType = 'consumer';
            }else{
                customerRecType = 'trade';
            }
       }
    }
    public PageReference setReview(){
       issueAdjustment.IsReviewed__c = True;
       issueAdjustment.Status__c = 'Complete';
       update issueAdjustment; 
       PageReference pg = new Pagereference('/apex/IssueAdjustmentReviewDetail?id='+this.caseObj.id+'&issueAdjust='+issueAdjustment.id);
       pg.setRedirect(true);
       return pg; 
    }        
}