force-app/main/default/objects/Issue_Adjustment__c/Issue_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Issue Adjustment</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Issue Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues Adjustment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Adjustment__c/fields/Adjustment_Code__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Code__c</fullName>
    <label>Adjustment Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>IH</fullName>
            </value>
            <value>
                <fullName>RID</fullName>
            </value>
            <value>
                <fullName>SCF</fullName>
            </value>
            <value>
                <fullName>ST</fullName>
            </value>
            <value>
                <fullName>TC</fullName>
            </value>
            <value>
                <fullName>CCL</fullName>
            </value>
            <value>
                <fullName>FC</fullName>
            </value>
            <value>
                <fullName>ITPD</fullName>
            </value>
            <value>
                <fullName>ITS</fullName>
            </value>
            <value>
                <fullName>ITMT</fullName>
            </value>
            <value>
                <fullName>ITM</fullName>
            </value>
            <value>
                <fullName>ITB</fullName>
            </value>
            <value>
                <fullName>ITF</fullName>
            </value>
            <value>
                <fullName>ITCS</fullName>
            </value>
            <value>
                <fullName>ITVT</fullName>
            </value>
            <value>
                <fullName>ITUD</fullName>
            </value>
            <value>
                <fullName>ITUT</fullName>
            </value>
            <value>
                <fullName>ITSN</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>ITL</fullName>
            </value>
            <value>
                <fullName>ITVD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Adjustment__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IssueAdjustmentHelper.cls
public class IssueAdjustmentHelper {

    public void updateIssueData(list<Issue_Adjustment__c> lstIssueAdjust){
        List<Id> ids = new List<id>();
        for(Issue_Adjustment__c issue : lstIssueAdjust){
            ids.add(issue.id);
        }
        IssueAdjustmentFutureHelper.updateIssue(ids); 
    }
    
    public void updateSequence(list<Issue_Adjustment__c> lstIssueAdjust){
        for(Issue_Adjustment__c issue : lstIssueAdjust){
            if(issue.Adjustment_Code__c == 'BH'){
                issue.Sequence__c = 1;
            }else if(issue.Adjustment_Code__c == 'IH'){
                issue.Sequence__c = 2;
            }else if(issue.Adjustment_Code__c == 'CN'){
                issue.Sequence__c = 3;
            }else if(issue.Adjustment_Code__c == 'RID'){
                issue.Sequence__c = 4;
            }else if(issue.Adjustment_Code__c == 'SCF'){
                issue.Sequence__c = 5;
            }else if(issue.Adjustment_Code__c == 'ST'){
                issue.Sequence__c = 6;
            }else if(issue.Adjustment_Code__c == 'TC'){
                issue.Sequence__c = 7;
            }else if(issue.Adjustment_Code__c == 'DC'){
                issue.Sequence__c = 8;
            }else{
                issue.Sequence__c = 9;
            }
        }
    }  
}