force-app/main/default/objects/Issue_Adjustment__c/Issue_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Issue Adjustment</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Issue Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues Adjustment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Adjustment__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Action Type</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Adjustment__c/fields/Adjustment_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Instructions__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Adjustment Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Issue_Adjustment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Issue_Adjustment__c/fields/isReviewed__c.field-meta.xml
<CustomField>
    <fullName>isReviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isReviewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Issue_Adjustment__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Issues Adjustment</relationshipLabel>
    <relationshipName>Cases_Adjustment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Adjustment__c/fields/IssueNumber__c.field-meta.xml
<CustomField>
    <fullName>IssueNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IssueNumber</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IssueAdjustmentReviewController.cls
public class IssueAdjustmentReviewController{
    
    public Integer PageSize{get;set;}
    private String sortDirection;
    private String sortExp;
    public List<Issue_Adjustment__c> issueList{get;set;}
    public string selectedReviewType {get;set;}
    
    public IssueAdjustmentReviewController(ApexPages.StandardController controller) {
        pageInit();
    }
    
    private void pageInit(){
        issueList = new List<Issue_Adjustment__c>();       
        if(ApexPages.currentPage().getParameters().get('pageSize') != null){
            PageSize = Integer.valueOf(ApexPages.currentPage().getParameters().get('pageSize'));
        }else{
            PageSize = 25;
        }
        if(ApexPages.currentPage().getParameters().get('sortDirection') != null && ApexPages.currentPage().getParameters().get('sortDirection') != ''  && (ApexPages.currentPage().getParameters().get('sortDirection') == 'a' ||  ApexPages.currentPage().getParameters().get('sortDirection') == 'd')){
            sortDirection = ApexPages.currentPage().getParameters().get('sortDirection');
        }else{
            sortDirection = 'a';
        }
        if(ApexPages.currentPage().getParameters().get('ReviewType') != null && ApexPages.currentPage().getParameters().get('ReviewType') != ''){
            selectedReviewType = ApexPages.currentPage().getParameters().get('ReviewType');
        }else{
            selectedReviewType = 'Not Reviewed';
        }
        
        sortExp = 'IssueNumber__c';
        
    }
    
    public String sortExpression{
        get{ return sortExp;}
        set{
            //if the column is clicked on then switch between Ascending and Descending modes
            if (value == sortExp)
                sortDirection = (sortDirection == 'a')? 'd' : 'a';
            else
                sortDirection = 'a';
            sortExp = value;
        }
    }
   
   public String getSortDirection(){
        //if not column is selected 
        if (sortExpression == null || sortExpression == '')
            return 'a';
        else
            return sortDirection;
    }

    public void setSortDirection(String value){
        sortDirection = value;
    }
    
    public ApexPages.StandardSetController setQun {
         
        get {
            if(setQun == null) {
                //build the full sort expression
                string sortFullExp = '';
                if(sortDirection == 'a'){
                    sortFullExp = sortExpression  + ' ASC ';
                }else{
                     sortFullExp = sortExpression  + ' DESC ';
                }    
                System.debug('test '+sortFullExp );
                String ActionType = 'R';
                string queryIssue = '';
                if(selectedReviewType == 'Reviewed'){
                    queryIssue = 'SELECT id, IssueNumber__c, Issue__c, Adjustment_Instructions__c,Comment__c '; 
                    queryIssue  += ' FROM Issue_Adjustment__c Where Issue__c != null and  Action_Type__c = \''+ ActionType  +'\' and IsReviewed__c = true order by ' +sortFullExp + ' limit 1000'; 
                }else{
                    queryIssue = 'SELECT id, IssueNumber__c, Issue__c, Adjustment_Instructions__c,Comment__c '; 
                    queryIssue  += ' FROM Issue_Adjustment__c Where Issue__c != null and  Action_Type__c = \''+ ActionType +'\' and IsReviewed__c = false order by ' +sortFullExp + ' limit 1000'; 
                }  
                System.debug('test queryIssue  '+queryIssue  );
                setQun = new ApexPages.StandardSetController(Database.getQueryLocator(queryIssue));
                setQun.setPageSize(PageSize);
 
            }
            return setQun;
        }
        set;
    }
        
    public Boolean hasNext {
        get {
            return setQun.getHasNext();
        }
        set;
    }
    public Boolean hasPrevious {
        get {
            return setQun.getHasPrevious();
        }
        set;
    }
    
    public void previous() {
         setQun.previous();
     }
    
    public void next() {
         setQun.next();
    } 
    
    public PageReference ViewData(){
        PageReference pageRef = new PageReference('/apex/IssueAdjustmentReview?sortDirection='+sortDirection+'&ReviewType='+selectedReviewType);
        pageRef.setRedirect(true); 
        return pageRef ; 
    }   
    
    // Wrapper list  
    public List<Issue_Adjustment__c> getIssueReviewList() {        
          
        List<Issue_Adjustment__c> issueList = new List<Issue_Adjustment__c>();
        issueList =setQun.getRecords();
        
        return issueList;
    }
    
     public List<SelectOption> getReviewList(){
        List<SelectOption> ReviewDataList = new List<SelectOption>();
        
        
        ReviewDataList.add(new SelectOption('Not Reviewed', 'Not Reviewed'));
        ReviewDataList.add(new SelectOption('Reviewed', 'Reviewed'));  
        
        return ReviewDataList;
    }  
}