force-app/main/default/objects/Store_Type__c/Store_Type__c.object-meta.xml
<CustomObject>
    <label>Store Type</label>
    <nameField>
        <displayFormat>ST{00}</displayFormat>
        <label>Store Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Type__c/fields/AltCode__c.field-meta.xml
<CustomField>
    <fullName>AltCode__c</fullName>
    <formula>RIGHT(Name , LEN(Name)-2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AltCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store_Type__c/fields/Display_Description__c.field-meta.xml
<CustomField>
    <fullName>Display_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Display Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store_Type__c/fields/DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>DisplayOrder__c</fullName>
    <description>Feed Outbound - Hard code value 0</description>
    <formula>&apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DisplayOrder</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store_Type__c/fields/TenantId__c.field-meta.xml
<CustomField>
    <fullName>TenantId__c</fullName>
    <description>Feed Outbound</description>
    <formula>&apos;ALORICAALTRIA&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TenantId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StoreTypeTriggerHandler.cls
/************************************************************************ 
Author: Randolf Suplito
Date: 08/15/2022
Description: This handler class is for StoreTypeTrigger
*************************************************************************/

public class StoreTypeTriggerHandler {

    public static Boolean isFirstTime = true;
    
    public static void createCallout(List<Store_Type__c> triggerNewList, Map<Id,Store_Type__c> triggerNewMap) {
        
        String lastModifiedUser;

        jsonRequestDTO jsonPayload = new jsonRequestDTO();
        List<storeTypeDTO> storeTypeDTOList = new List<storeTypeDTO>();
        
        for(Store_Type__c storeTypeRec : [SELECT Id, LastModifiedBy.CommunityNickname FROM Store_Type__c WHERE Id IN :triggerNewMap.keyset()]) {
            lastModifiedUser = storeTypeRec.LastModifiedBy.CommunityNickname;
        }

        for(Store_Type__c storeTypeRec : triggerNewList) {
            storeTypeDTO stDTO = new storeTypeDTO();
            stDTO.TENANTID = storeTypeRec.TenantId__c != null ? storeTypeRec.TenantId__c : '';
            stDTO.CODE = storeTypeRec.Name != null ? storeTypeRec.Name : '';
            stDTO.ALTCODE = storeTypeRec.AltCode__c != null ? storeTypeRec.AltCode__c : '';
            stDTO.DESCRIPTION = storeTypeRec.Description__c != null ? storeTypeRec.Description__c : '';
            stDTO.DISPLAYDESCRIPTION = storeTypeRec.Display_Description__c != null ? storeTypeRec.Display_Description__c : '';
            if(storeTypeRec.isActive__c != null && storeTypeRec.isActive__c) {
                stDTO.ACTIVEFLAG = 'Y';
            } else if(storeTypeRec.isActive__c != null && !storeTypeRec.isActive__c) {
                stDTO.ACTIVEFLAG = 'N';
            } else if(storeTypeRec.isActive__c == null) {
                stDTO.ACTIVEFLAG = '';
            }
            stDTO.DISPLAYORDER = storeTypeRec.DisplayOrder__c != null ? storeTypeRec.DisplayOrder__c : '';
            
            storeTypeDTOList.add(stDTO);
        }
        
        if(!storeTypeDTOList.isEmpty()) {
            jsonPayload.userName = lastModifiedUser;
            jsonPayload.StoreType = storeTypeDTOList;
            System.debug('jsonPayload: ' + JSON.Serialize(jsonPayload));
        	APIDataCalloutServices.dataFeedCallout(JSON.Serialize(jsonPayload), ConstantClass.STORETYPE_CALLOUT_NAME);
        }
    }
    
    public class jsonRequestDTO {
        public String userName {get; set;}
        public List<storeTypeDTO> StoreType;
    }
    
    public class storeTypeDTO {
        public String TENANTID {get; set;}
        public String CODE {get; set;}
        public String ALTCODE {get; set;}
        public String DESCRIPTION {get; set;}
        public String DISPLAYDESCRIPTION {get; set;}
        public String ACTIVEFLAG {get; set;}
        public String DISPLAYORDER {get; set;}
    }
}